-- 021. 기존 사전 812단어에 난이도(level) 1~4 채우기 (020_word_bank_levels.sql 다음에 실행).
-- app/scripts/vocab/existing-levels.mjs 로 생성한 초안 — 기준은 그 파일 맨 위 주석 참고.
-- 레벨을 바꾸고 싶은 단어는 이 파일을 고치지 말고 SQL Editor에서 update로 덮어써도 된다.

update public.word_bank set level = 1 where id in (
  'a', 'after', 'afternoon', 'again', 'all', 'always', 'an', 'and', 'angry', 'animal', 'answer', 'apple', 'arm', 'ask', 'at', 'baby', 'back', 'bad', 'bag', 'ball', 'balloon', 'banana', 'be', 'bear', 'bed', 'big', 'bird', 'birthday', 'black', 'blue', 'boat', 'body', 'book', 'box', 'boy', 'bread', 'breakfast', 'brother', 'brown', 'bus', 'but', 'by', 'bye', 'cake', 'can', 'candy', 'car', 'card', 'cat', 'chair', 'cheese', 'chicken', 'child', 'class', 'clock', 'close', 'cloud', 'cold', 'color', 'come', 'computer', 'count', 'cow', 'crayon', 'cry', 'cup', 'dad', 'dance', 'day', 'desk', 'dinner', 'do', 'doctor', 'dog', 'doll', 'door', 'down', 'draw', 'drink', 'duck', 'ear', 'eat', 'egg', 'eraser', 'evening', 'eye', 'face', 'family', 'fast', 'father', 'finger', 'fish', 'flower', 'food', 'foot', 'for', 'friend', 'from', 'fruit', 'fun', 'game', 'girl', 'give', 'go', 'good', 'grandmother', 'grape', 'green', 'hair', 'hamburger', 'hand', 'happy', 'hat', 'have', 'he', 'head', 'hear', 'heart', 'hello', 'help', 'hen', 'here', 'hi', 'home', 'horse', 'hot', 'house', 'how', 'hungry', 'I', 'ice', 'in', 'it', 'juice', 'jump', 'kid', 'know', 'leg', 'like', 'lion', 'listen', 'little', 'long', 'look', 'love', 'lunch', 'make', 'man', 'many', 'meat', 'melon', 'milk', 'minute', 'mom', 'money', 'monkey', 'month', 'moon', 'morning', 'mother', 'mouth', 'movie', 'music', 'name', 'never', 'new', 'nice', 'night', 'no', 'nose', 'not', 'now', 'number', 'of', 'oh', 'okay', 'old', 'on', 'open', 'or', 'orange', 'out', 'pants', 'paper', 'park', 'party', 'pear', 'pen', 'pencil', 'people', 'piano', 'picture', 'pig', 'pink', 'plane', 'play', 'please', 'potato', 'put', 'rain', 'rainbow', 'read', 'red', 'rice', 'robot', 'room', 'ruler', 'run', 'sad', 'salad', 'salt', 'say', 'school', 'sea', 'see', 'she', 'sheep', 'ship', 'shirt', 'shoe', 'short', 'shoulder', 'sick', 'sing', 'sister', 'sit', 'skirt', 'sky', 'sleep', 'slow', 'small', 'smile', 'snow', 'soap', 'soccer', 'sock', 'some', 'song', 'sorry', 'soup', 'spoon', 'spring', 'stand', 'star', 'start', 'stop', 'story', 'strawberry', 'student', 'study', 'sugar', 'summer', 'sun', 'sweet', 'swim', 'table', 'take', 'talk', 'tall', 'taxi', 'television', 'tennis', 'thank', 'that', 'the', 'there', 'they', 'think', 'thirsty', 'this', 'tiger', 'time', 'tired', 'to', 'today', 'tomato', 'tomorrow', 'tooth', 'toy', 'train', 'tree', 'truck', 'umbrella', 'under', 'up', 'use', 'very', 'video', 'wait', 'walk', 'want', 'wash', 'watch', 'water', 'we', 'weather', 'week', 'what', 'when', 'where', 'white', 'who', 'why', 'wind', 'window', 'winter', 'with', 'woman', 'word', 'work', 'write', 'yeah', 'year', 'yellow', 'yes', 'yesterday', 'you', 'zero', 'zoo'
);
update public.word_bank set level = 2 where id in (
  'about', 'across', 'act', 'afraid', 'age', 'ago', 'air', 'airport', 'any', 'apartment', 'around', 'arrive', 'as', 'aunt', 'autumn', 'away', 'bank', 'basket', 'bath', 'beach', 'beautiful', 'because', 'before', 'begin', 'behind', 'bell', 'between', 'bicycle', 'board', 'bottle', 'bowl', 'break', 'bring', 'brush', 'busy', 'butter', 'button', 'buy', 'calendar', 'call', 'camera', 'candle', 'cap', 'carry', 'catch', 'chalk', 'change', 'circle', 'city', 'classmate', 'clean', 'climb', 'clothes', 'club', 'coat', 'coffee', 'coin', 'cook', 'cool', 'country', 'cousin', 'cream', 'cut', 'dark', 'date', 'daughter', 'diary', 'dictionary', 'dirty', 'dollar', 'dolphin', 'dream', 'dress', 'drive', 'drum', 'dry', 'early', 'earth', 'east', 'easy', 'empty', 'end', 'enjoy', 'every', 'exercise', 'fall-1', 'fall-2', 'far', 'farm', 'fat', 'feel', 'find', 'fine', 'finish', 'fire', 'flag', 'floor', 'fly', 'follow', 'forget', 'fork', 'front', 'full', 'garden', 'get', 'glad', 'glass', 'glove', 'gold', 'grass', 'gray', 'great', 'grow', 'guitar', 'half', 'hard-1', 'hate', 'heavy', 'hide', 'high', 'hit', 'hold', 'holiday', 'hope', 'hospital', 'hotel', 'hour', 'hundred', 'hurt', 'if', 'keep', 'key', 'kick', 'kind-1', 'king', 'kitchen', 'knee', 'knife', 'lake', 'lamp', 'large', 'late', 'laugh', 'leaf', 'learn', 'leave', 'left', 'lesson', 'let', 'letter', 'library', 'light', 'line', 'lip', 'list', 'live', 'lose', 'lot', 'loud', 'low', 'mad', 'mail', 'map', 'march-1', 'market', 'may-2', 'meet', 'million', 'mirror', 'Miss', 'mountain', 'move', 'Mr', 'Mrs', 'much', 'must', 'near', 'neck', 'need', 'news', 'next', 'north', 'note', 'nurse', 'o''clock', 'off', 'office', 'often', 'oil', 'once', 'only', 'other', 'over', 'page', 'paint', 'parent', 'pay', 'pick', 'picnic', 'pilot', 'place', 'plant', 'pocket', 'point', 'police', 'pool', 'poster', 'practice', 'present-2', 'pretty', 'pull', 'push', 'queen', 'question', 'quick', 'quiet', 'radio', 'ready', 'remember', 'repeat', 'rest', 'restaurant', 'ribbon', 'rich', 'ride', 'right-1', 'right-2', 'ring', 'river', 'road', 'rock', 'rocket', 'roll', 'roof', 'rose', 'round', 'safe', 'same', 'sand', 'score', 'season', 'seat', 'sell', 'send', 'shape', 'shop', 'shout', 'show', 'shower', 'side', 'silver', 'size', 'skate', 'slide', 'smell', 'so', 'soft', 'son', 'soon', 'sound', 'south', 'space', 'speak', 'spell', 'sport', 'square', 'stairs', 'stamp', 'station', 'stay', 'stick', 'stone', 'store', 'street', 'strong', 'subway', 'supermarket', 'surprise', 'sweater', 'swing', 'tape', 'taste', 'tea', 'teach', 'team', 'telephone', 'tell', 'test', 'then', 'thin', 'thing', 'thousand', 'throw', 'ticket', 'together', 'tonight', 'too', 'top', 'touch', 'town', 'trip', 'try', 'tulip', 'turn', 'uncle', 'understand', 'vacation', 'vegetable', 'village', 'violin', 'visit', 'wake', 'wall', 'warm', 'weak', 'wear', 'welcome', 'well', 'west', 'wet', 'which', 'wide', 'will', 'win', 'wing', 'wood', 'world', 'wrong', 'young'
);
update public.word_bank set level = 3 where id in (
  'address', 'album', 'along', 'among', 'band-1', 'band-2', 'become', 'below', 'bench', 'beside', 'blow', 'bridge', 'bright', 'build', 'burn', 'camp', 'captain', 'care-1', 'care-2', 'ceiling', 'center', 'chance', 'cheap', 'chopstick', 'church', 'copy', 'corner', 'cover', 'cross', 'curtain', 'danger', 'dead', 'dear', 'deep', 'die', 'dish', 'drop', 'enough', 'example', 'excellent', 'excite', 'fair', 'famous', 'few', 'field', 'fight', 'fill', 'film', 'fix', 'free', 'fresh', 'gas', 'gate', 'ground', 'group', 'hall', 'happen', 'hard-2', 'hiking', 'hill', 'hole', 'hurry', 'idea', 'ill', 'ink', 'interest', 'into', 'introduce', 'island', 'job', 'join', 'jungle', 'just', 'kind-2', 'knock', 'lady', 'land', 'last', 'lead', 'lie-1', 'luck', 'march-2', 'marry', 'may-1', 'meter', 'middle', 'model', 'narrow', 'noise', 'pair', 'pass', 'peace', 'piece', 'pin', 'pine', 'pipe', 'plan', 'poor', 'post', 'present-1', 'print', 'problem', 'real', 'record', 'return', 'set', 'sheet', 'shoot', 'shut', 'sign', 'sir', 'smoke', 'speed', 'spend', 'step', 'storm', 'stove', 'straight', 'supper', 'sure', 'than', 'thick', 'through', 'tie', 'travel', 'true', 'twice', 'until', 'waste', 'way', 'wonder', 'yet'
);
update public.word_bank set level = 4 where id in (
  'base', 'capital-1', 'capital-2', 'case', 'cassette', 'course', 'dial', 'engine', 'excuse', 'fact', 'fool', 'gentle', 'god', 'handle', 'hose', 'kill', 'lie-2', 'ma''am', 'matter', 'medal', 'pardon', 'service', 'shall', 'steam', 'strange', 'strike', 'stupid', 'switch', 'temple', 'till', 'usual', 'war'
);
