-- 024. 확장 배치 2: 외모·몸·옷·색깔·장소·나라·행사·요일·취미·감정·휴일·집·건강·쇼핑·돈·음악·자연·숫자·사람·학교·
-- 모양·스포츠·크기·우주·장난감·교통·과학기술·상태·위치·의문사·성격·맛·직업·재료·과학·환경·독해 + 숙어·표현.
-- 020, 021, 022 다음에 실행. 여러 번 실행해도 안전(on conflict do nothing). image_url은 그림 파일이 생긴 뒤 별도로 채운다.
-- app/scripts/vocab/build-batches.mjs 로 생성.

insert into public.word_bank
  (id, word, sense_number, part_of_speech, meaning, example_sentence, category, extra_categories, subcategory, level, origin, image_url, sort_order)
values
  ('cute', 'cute', 1, '형용사', '귀여운', 'The baby is cute.', '외모', array['상태']::text[], '인상', 1, 'classbank', null, 1200),
  ('handsome', 'handsome', 1, '형용사', '잘생긴', 'He is a handsome man.', '외모', '{}', '인상', 3, 'classbank', null, 1201),
  ('lovely', 'lovely', 1, '형용사', '사랑스러운', 'What a lovely dress!', '외모', '{}', '인상', 3, 'classbank', null, 1202),
  ('neat', 'neat', 1, '형용사', '단정한', 'Her desk is neat.', '외모', '{}', '인상', 3, 'classbank', null, 1203),
  ('messy', 'messy', 1, '형용사', '지저분한', 'My room is messy.', '외모', '{}', '인상', 3, 'classbank', null, 1204),
  ('curly', 'curly', 1, '형용사', '곱슬곱슬한', 'She has curly hair.', '외모', '{}', '머리카락', 2, 'classbank', null, 1205),
  ('wavy', 'wavy', 1, '형용사', '물결 모양의', 'He has wavy hair.', '외모', '{}', '머리카락', 3, 'classbank', null, 1206),
  ('blond', 'blond', 1, '형용사', '금발의', 'The boy has blond hair.', '외모', '{}', '머리카락', 3, 'classbank', null, 1207),
  ('brown-haired', 'brown-haired', 1, '형용사', '갈색 머리의', 'She is brown-haired.', '외모', '{}', '머리카락', 3, 'classbank', null, 1208),
  ('black-haired', 'black-haired', 1, '형용사', '검은 머리의', 'He is black-haired.', '외모', '{}', '머리카락', 3, 'classbank', null, 1209),
  ('bald', 'bald', 1, '형용사', '대머리의', 'My uncle is bald.', '외모', '{}', '머리카락', 3, 'classbank', null, 1210),
  ('beard', 'beard', 1, '명사', '턱수염', 'He has a long beard.', '외모', '{}', '얼굴 특징', 3, 'classbank', null, 1211),
  ('mustache', 'mustache', 1, '명사', '콧수염', 'The man has a mustache.', '외모', '{}', '얼굴 특징', 3, 'classbank', null, 1212),
  ('freckles', 'freckles', 1, '명사', '주근깨', 'She has freckles.', '외모', '{}', '얼굴 특징', 3, 'classbank', null, 1213),
  ('glasses', 'glasses', 1, '명사', '안경', 'I wear glasses.', '외모', array['옷']::text[], '얼굴 특징', 1, 'classbank', null, 1214),
  ('cool-2', 'cool', 2, '형용사', '멋진', 'Your bag is cool!', '외모', '{}', '인상', 2, 'classbank', null, 1215),
  ('funny', 'funny', 1, '형용사', '웃긴, 재미있는', 'The clown is funny.', '외모', array['상태', '성격']::text[], '인상', 1, 'classbank', null, 1216),
  ('blonde', 'blonde', 1, '형용사', '금발의 (여성)', 'She has blonde hair.', '외모', '{}', '머리카락', 3, 'classbank', null, 1217),
  ('forehead', 'forehead', 1, '명사', '이마', 'My forehead is hot.', '몸', '{}', '얼굴', 2, 'classbank', null, 1218),
  ('eyebrow', 'eyebrow', 1, '명사', '눈썹', 'She has thick eyebrows.', '몸', '{}', '얼굴', 2, 'classbank', null, 1219),
  ('eyelash', 'eyelash', 1, '명사', '속눈썹', 'The baby has long eyelashes.', '몸', '{}', '얼굴', 3, 'classbank', null, 1220),
  ('cheek', 'cheek', 1, '명사', '볼', 'She has a red cheek.', '몸', array['외모']::text[], '얼굴', 2, 'classbank', null, 1221),
  ('chin', 'chin', 1, '명사', '턱', 'He has a small chin.', '몸', array['외모']::text[], '얼굴', 2, 'classbank', null, 1222),
  ('tongue', 'tongue', 1, '명사', '혀', 'Stick out your tongue.', '몸', '{}', '얼굴', 2, 'classbank', null, 1223),
  ('teeth', 'teeth', 1, '명사', '이, 치아 (복수)', 'I brush my teeth.', '몸', '{}', '얼굴', 2, 'classbank', null, 1224),
  ('skin', 'skin', 1, '명사', '피부', 'The baby has soft skin.', '몸', array['외모']::text[], '속·피부', 2, 'classbank', null, 1225),
  ('elbow', 'elbow', 1, '명사', '팔꿈치', 'My elbow hurts.', '몸', '{}', '팔·손', 2, 'classbank', null, 1226),
  ('wrist', 'wrist', 1, '명사', '손목', 'She wears a watch on her wrist.', '몸', '{}', '팔·손', 3, 'classbank', null, 1227),
  ('thumb', 'thumb', 1, '명사', '엄지손가락', 'I hurt my thumb.', '몸', '{}', '팔·손', 2, 'classbank', null, 1228),
  ('chest', 'chest', 1, '명사', '가슴', 'My chest is warm.', '몸', '{}', '몸통', 2, 'classbank', null, 1229),
  ('stomach', 'stomach', 1, '명사', '배, 위', 'My stomach hurts.', '몸', '{}', '몸통', 2, 'classbank', null, 1230),
  ('waist', 'waist', 1, '명사', '허리', 'The belt is on my waist.', '몸', '{}', '몸통', 3, 'classbank', null, 1231),
  ('hip', 'hip', 1, '명사', '엉덩이, 골반', 'She put her hands on her hips.', '몸', '{}', '몸통', 3, 'classbank', null, 1232),
  ('ankle', 'ankle', 1, '명사', '발목', 'I hurt my ankle.', '몸', '{}', '다리·발', 3, 'classbank', null, 1233),
  ('feet', 'feet', 1, '명사', '발 (복수)', 'My feet are cold.', '몸', '{}', '다리·발', 1, 'classbank', null, 1234),
  ('toe', 'toe', 1, '명사', '발가락', 'I have ten toes.', '몸', '{}', '다리·발', 1, 'classbank', null, 1235),
  ('bone', 'bone', 1, '명사', '뼈', 'The dog has a bone.', '몸', '{}', '속·피부', 2, 'classbank', null, 1236),
  ('brain', 'brain', 1, '명사', '뇌, 머리', 'Use your brain.', '몸', '{}', '속·피부', 2, 'classbank', null, 1237),
  ('blood', 'blood', 1, '명사', '피', 'The cut has blood.', '몸', '{}', '속·피부', 2, 'classbank', null, 1238),
  ('back-2', 'back', 2, '명사', '등', 'My back hurts.', '몸', '{}', '몸통', 1, 'classbank', null, 1239),
  ('t-shirt', 'T-shirt', 1, '명사', '티셔츠', 'I wear a T-shirt.', '옷', '{}', '윗옷', 1, 'classbank', null, 1240),
  ('blouse', 'blouse', 1, '명사', '블라우스', 'She wears a white blouse.', '옷', '{}', '윗옷', 3, 'classbank', null, 1241),
  ('sweatshirt', 'sweatshirt', 1, '명사', '맨투맨 티셔츠', 'I wear a sweatshirt.', '옷', '{}', '윗옷', 3, 'classbank', null, 1242),
  ('hoodie', 'hoodie', 1, '명사', '후드티', 'My hoodie is warm.', '옷', '{}', '윗옷', 3, 'classbank', null, 1243),
  ('jacket', 'jacket', 1, '명사', '재킷, 점퍼', 'Put on your jacket.', '옷', '{}', '윗옷', 2, 'classbank', null, 1244),
  ('vest', 'vest', 1, '명사', '조끼', 'He wears a vest.', '옷', '{}', '윗옷', 3, 'classbank', null, 1245),
  ('trousers', 'trousers', 1, '명사', '바지', 'These trousers are long.', '옷', '{}', '아래옷', 3, 'classbank', null, 1246),
  ('jeans', 'jeans', 1, '명사', '청바지', 'I like blue jeans.', '옷', '{}', '아래옷', 2, 'classbank', null, 1247),
  ('shorts', 'shorts', 1, '명사', '반바지', 'I wear shorts in summer.', '옷', '{}', '아래옷', 1, 'classbank', null, 1248),
  ('pajamas', 'pajamas', 1, '명사', '잠옷', 'I wear pajamas at night.', '옷', '{}', '잠옷·속옷', 2, 'classbank', null, 1249),
  ('underwear', 'underwear', 1, '명사', '속옷', 'Put your underwear in the bag.', '옷', '{}', '잠옷·속옷', 2, 'classbank', null, 1250),
  ('swimsuit', 'swimsuit', 1, '명사', '수영복', 'I wear a swimsuit at the pool.', '옷', '{}', '잠옷·속옷', 2, 'classbank', null, 1251),
  ('uniform', 'uniform', 1, '명사', '교복, 제복', 'I wear a school uniform.', '옷', '{}', '잠옷·속옷', 2, 'classbank', null, 1252),
  ('sneakers', 'sneakers', 1, '명사', '운동화', 'I run in my sneakers.', '옷', '{}', '신발·양말', 2, 'classbank', null, 1253),
  ('boots', 'boots', 1, '명사', '부츠', 'I wear boots in winter.', '옷', '{}', '신발·양말', 2, 'classbank', null, 1254),
  ('sandals', 'sandals', 1, '명사', '샌들', 'I wear sandals in summer.', '옷', '{}', '신발·양말', 2, 'classbank', null, 1255),
  ('slippers', 'slippers', 1, '명사', '슬리퍼', 'Put on your slippers.', '옷', '{}', '신발·양말', 2, 'classbank', null, 1256),
  ('helmet', 'helmet', 1, '명사', '헬멧', 'Wear a helmet on your bike.', '옷', array['스포츠']::text[], '모자·소품', 2, 'classbank', null, 1257),
  ('scarf', 'scarf', 1, '명사', '목도리', 'I wear a scarf in winter.', '옷', '{}', '모자·소품', 2, 'classbank', null, 1258),
  ('mittens', 'mittens', 1, '명사', '벙어리장갑', 'The baby has red mittens.', '옷', '{}', '모자·소품', 3, 'classbank', null, 1259),
  ('belt', 'belt', 1, '명사', '허리띠', 'He wears a black belt.', '옷', '{}', '모자·소품', 2, 'classbank', null, 1260),
  ('zipper', 'zipper', 1, '명사', '지퍼', 'Close the zipper.', '옷', '{}', '모자·소품', 3, 'classbank', null, 1261),
  ('sunglasses', 'sunglasses', 1, '명사', '선글라스', 'I wear sunglasses in summer.', '옷', '{}', '모자·소품', 2, 'classbank', null, 1262),
  ('backpack', 'backpack', 1, '명사', '배낭, 책가방', 'My backpack is heavy.', '옷', array['학교/문구']::text[], '모자·소품', 1, 'classbank', null, 1263),
  ('handbag', 'handbag', 1, '명사', '핸드백', 'Mom has a new handbag.', '옷', '{}', '모자·소품', 3, 'classbank', null, 1264),
  ('tie-2', 'tie', 2, '명사', '넥타이', 'Dad wears a tie.', '옷', '{}', '모자·소품', 3, 'classbank', null, 1265),
  ('socks', 'socks', 1, '명사', '양말', 'I wear socks in winter.', '옷', '{}', '신발·양말', 1, 'classbank', null, 1266),
  ('shoes', 'shoes', 1, '명사', '신발', 'I put on my shoes.', '옷', '{}', '신발·양말', 1, 'classbank', null, 1267),
  ('gloves', 'gloves', 1, '명사', '장갑', 'I wear gloves in winter.', '옷', '{}', '모자·소품', 2, 'classbank', null, 1268),
  ('purple', 'purple', 1, '형용사', '보라색의', 'I like purple grapes.', '색깔', '{}', null, 1, 'classbank', null, 1269),
  ('violet', 'violet', 1, '형용사', '제비꽃색의, 보라색의', 'The flower is violet.', '색깔', '{}', null, 3, 'classbank', null, 1270),
  ('golden', 'golden', 1, '형용사', '황금빛의', 'She has golden hair.', '색깔', '{}', null, 3, 'classbank', null, 1271),
  ('beige', 'beige', 1, '형용사', '베이지색의', 'The sofa is beige.', '색깔', '{}', null, 3, 'classbank', null, 1272),
  ('navy', 'navy', 1, '형용사', '남색의', 'He wears a navy jacket.', '색깔', '{}', null, 3, 'classbank', null, 1273),
  ('sky-blue', 'sky blue', 1, '형용사', '하늘색의', 'The sky is sky blue.', '색깔', '{}', null, 2, 'classbank', null, 1274),
  ('light-blue', 'light blue', 1, '형용사', '연한 파란색의', 'I have a light blue bag.', '색깔', '{}', null, 2, 'classbank', null, 1275),
  ('dark-blue', 'dark blue', 1, '형용사', '진한 파란색의', 'The sea is dark blue.', '색깔', '{}', null, 2, 'classbank', null, 1276),
  ('light-green', 'light green', 1, '형용사', '연두색의', 'The leaf is light green.', '색깔', '{}', null, 2, 'classbank', null, 1277),
  ('dark-green', 'dark green', 1, '형용사', '진한 초록색의', 'The tree is dark green.', '색깔', '{}', null, 2, 'classbank', null, 1278),
  ('turquoise', 'turquoise', 1, '형용사', '청록색의', 'The water is turquoise.', '색깔', '{}', null, 3, 'classbank', null, 1279),
  ('mint', 'mint', 1, '형용사', '민트색의', 'I have a mint bag.', '색깔', '{}', null, 3, 'classbank', null, 1280),
  ('coral', 'coral', 1, '형용사', '산호색의', 'She wears a coral dress.', '색깔', '{}', null, 3, 'classbank', null, 1281),
  ('colorful', 'colorful', 1, '형용사', '알록달록한', 'The kite is colorful.', '색깔', array['상태']::text[], null, 2, 'classbank', null, 1282),
  ('orange-2', 'orange', 2, '형용사', '주황색의', 'The pumpkin is orange.', '색깔', '{}', null, 1, 'classbank', null, 1283),
  ('peach-2', 'peach', 2, '형용사', '복숭아색의', 'She has a peach dress.', '색깔', '{}', null, 3, 'classbank', null, 1284),
  ('cream-2', 'cream', 2, '형용사', '크림색의', 'The wall is cream.', '색깔', '{}', null, 3, 'classbank', null, 1285),
  ('grey', 'grey', 1, '형용사', '회색의', 'The cat is grey.', '색깔', '{}', null, 2, 'classbank', null, 1286),
  ('neighborhood', 'neighborhood', 1, '명사', '동네', 'I live in a nice neighborhood.', '장소', '{}', '동네·건물', 2, 'classbank', null, 1287),
  ('building', 'building', 1, '명사', '건물', 'The building is tall.', '장소', '{}', '동네·건물', 2, 'classbank', null, 1288),
  ('factory', 'factory', 1, '명사', '공장', 'My uncle works in a factory.', '장소', '{}', '동네·건물', 3, 'classbank', null, 1289),
  ('bus-stop', 'bus stop', 1, '명사', '버스 정류장', 'I wait at the bus stop.', '장소', array['교통']::text[], '동네·건물', 2, 'classbank', null, 1290),
  ('subway-station', 'subway station', 1, '명사', '지하철역', 'The subway station is near.', '장소', '{}', '동네·건물', 2, 'classbank', null, 1291),
  ('playground', 'playground', 1, '명사', '놀이터, 운동장', 'We play at the playground.', '장소', array['학교/문구']::text[], '놀이·문화', 1, 'classbank', null, 1292),
  ('movie-theater', 'movie theater', 1, '명사', '영화관', 'We go to the movie theater.', '장소', '{}', '놀이·문화', 2, 'classbank', null, 1293),
  ('museum', 'museum', 1, '명사', '박물관', 'We visit the museum.', '장소', '{}', '놀이·문화', 2, 'classbank', null, 1294),
  ('aquarium', 'aquarium', 1, '명사', '수족관', 'I see fish at the aquarium.', '장소', '{}', '놀이·문화', 2, 'classbank', null, 1295),
  ('clinic', 'clinic', 1, '명사', '병원, 의원', 'The clinic is near my house.', '장소', array['건강/질병']::text[], '공공시설', 3, 'classbank', null, 1296),
  ('pharmacy', 'pharmacy', 1, '명사', '약국', 'I buy medicine at the pharmacy.', '장소', array['건강/질병']::text[], '공공시설', 2, 'classbank', null, 1297),
  ('post-office', 'post office', 1, '명사', '우체국', 'I send a letter at the post office.', '장소', '{}', '공공시설', 2, 'classbank', null, 1298),
  ('police-station', 'police station', 1, '명사', '경찰서', 'The police station is on the street.', '장소', '{}', '공공시설', 2, 'classbank', null, 1299),
  ('fire-station', 'fire station', 1, '명사', '소방서', 'The fire station has a red truck.', '장소', '{}', '공공시설', 2, 'classbank', null, 1300),
  ('bakery', 'bakery', 1, '명사', '빵집', 'I buy bread at the bakery.', '장소', '{}', '가게', 2, 'classbank', null, 1301),
  ('cafe', 'cafe', 1, '명사', '카페', 'We drink juice at the cafe.', '장소', '{}', '가게', 2, 'classbank', null, 1302),
  ('bookstore', 'bookstore', 1, '명사', '서점', 'I buy a book at the bookstore.', '장소', '{}', '가게', 2, 'classbank', null, 1303),
  ('toy-store', 'toy store', 1, '명사', '장난감 가게', 'I want to go to the toy store.', '장소', '{}', '가게', 2, 'classbank', null, 1304),
  ('clothing-store', 'clothing store', 1, '명사', '옷 가게', 'We go to the clothing store.', '장소', '{}', '가게', 2, 'classbank', null, 1305),
  ('department-store', 'department store', 1, '명사', '백화점', 'Mom is at the department store.', '장소', '{}', '가게', 2, 'classbank', null, 1306),
  ('shopping-mall', 'shopping mall', 1, '명사', '쇼핑몰', 'The shopping mall is big.', '장소', '{}', '가게', 2, 'classbank', null, 1307),
  ('grocery-store', 'grocery store', 1, '명사', '식료품점', 'We buy milk at the grocery store.', '장소', '{}', '가게', 3, 'classbank', null, 1308),
  ('korea', 'Korea', 1, '명사', '한국', 'I live in Korea.', '나라/세계', '{}', '아시아', 1, 'classbank', null, 1309),
  ('south-korea', 'South Korea', 1, '명사', '대한민국', 'South Korea is in Asia.', '나라/세계', '{}', '아시아', 2, 'classbank', null, 1310),
  ('china', 'China', 1, '명사', '중국', 'China is a big country.', '나라/세계', '{}', '아시아', 1, 'classbank', null, 1311),
  ('japan', 'Japan', 1, '명사', '일본', 'Japan is near Korea.', '나라/세계', '{}', '아시아', 1, 'classbank', null, 1312),
  ('india', 'India', 1, '명사', '인도', 'India is a big country.', '나라/세계', '{}', '아시아', 2, 'classbank', null, 1313),
  ('thailand', 'Thailand', 1, '명사', '태국', 'I want to visit Thailand.', '나라/세계', '{}', '아시아', 2, 'classbank', null, 1314),
  ('vietnam', 'Vietnam', 1, '명사', '베트남', 'Vietnam is warm.', '나라/세계', '{}', '아시아', 2, 'classbank', null, 1315),
  ('philippines', 'Philippines', 1, '명사', '필리핀', 'The Philippines has many islands.', '나라/세계', '{}', '아시아', 3, 'classbank', null, 1316),
  ('indonesia', 'Indonesia', 1, '명사', '인도네시아', 'Indonesia has many islands.', '나라/세계', '{}', '아시아', 3, 'classbank', null, 1317),
  ('singapore', 'Singapore', 1, '명사', '싱가포르', 'Singapore is a small country.', '나라/세계', '{}', '아시아', 3, 'classbank', null, 1318),
  ('malaysia', 'Malaysia', 1, '명사', '말레이시아', 'Malaysia is warm all year.', '나라/세계', '{}', '아시아', 3, 'classbank', null, 1319),
  ('australia', 'Australia', 1, '명사', '호주', 'Kangaroos live in Australia.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1320),
  ('new-zealand', 'New Zealand', 1, '명사', '뉴질랜드', 'New Zealand has many sheep.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1321),
  ('canada', 'Canada', 1, '명사', '캐나다', 'It is cold in Canada.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1322),
  ('united-states', 'United States', 1, '명사', '미국', 'He is from the United States.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1323),
  ('america', 'America', 1, '명사', '미국, 아메리카', 'She lives in America.', '나라/세계', '{}', '아메리카·오세아니아', 1, 'classbank', null, 1324),
  ('mexico', 'Mexico', 1, '명사', '멕시코', 'I want to visit Mexico.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1325),
  ('brazil', 'Brazil', 1, '명사', '브라질', 'Brazil is a big country.', '나라/세계', '{}', '아메리카·오세아니아', 2, 'classbank', null, 1326),
  ('argentina', 'Argentina', 1, '명사', '아르헨티나', 'Argentina is in South America.', '나라/세계', '{}', '아메리카·오세아니아', 3, 'classbank', null, 1327),
  ('united-kingdom', 'United Kingdom', 1, '명사', '영국', 'London is in the United Kingdom.', '나라/세계', '{}', '유럽·아프리카', 3, 'classbank', null, 1328),
  ('england', 'England', 1, '명사', '잉글랜드, 영국', 'England is a country.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1329),
  ('france', 'France', 1, '명사', '프랑스', 'Paris is in France.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1330),
  ('germany', 'Germany', 1, '명사', '독일', 'Germany is in Europe.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1331),
  ('italy', 'Italy', 1, '명사', '이탈리아', 'Pizza is from Italy.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1332),
  ('spain', 'Spain', 1, '명사', '스페인', 'Spain is a warm country.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1333),
  ('greece', 'Greece', 1, '명사', '그리스', 'Greece is in Europe.', '나라/세계', '{}', '유럽·아프리카', 3, 'classbank', null, 1334),
  ('egypt', 'Egypt', 1, '명사', '이집트', 'The pyramids are in Egypt.', '나라/세계', '{}', '유럽·아프리카', 2, 'classbank', null, 1335),
  ('south-africa', 'South Africa', 1, '명사', '남아프리카 공화국', 'South Africa is in Africa.', '나라/세계', '{}', '유럽·아프리카', 3, 'classbank', null, 1336),
  ('turkey-2', 'Turkey', 2, '명사', '튀르키예(터키)', 'Turkey is a country.', '나라/세계', '{}', '유럽·아프리카', 3, 'classbank', null, 1337),
  ('language', 'language', 1, '명사', '언어, 말', 'English is a language.', '나라/세계', '{}', '언어·국적', 2, 'classbank', null, 1338),
  ('korean', 'Korean', 1, '명사', '한국어, 한국인', 'I speak Korean.', '나라/세계', array['학교/문구']::text[], '언어·국적', 1, 'classbank', null, 1339),
  ('chinese', 'Chinese', 1, '명사', '중국어, 중국인', 'She speaks Chinese.', '나라/세계', '{}', '언어·국적', 2, 'classbank', null, 1340),
  ('japanese', 'Japanese', 1, '명사', '일본어, 일본인', 'He speaks Japanese.', '나라/세계', '{}', '언어·국적', 2, 'classbank', null, 1341),
  ('english', 'English', 1, '명사', '영어, 영국인', 'I study English.', '나라/세계', array['학교/문구']::text[], '언어·국적', 1, 'classbank', null, 1342),
  ('american', 'American', 1, '명사', '미국인, 미국의', 'He is American.', '나라/세계', '{}', '언어·국적', 2, 'classbank', null, 1343),
  ('canadian', 'Canadian', 1, '명사', '캐나다인, 캐나다의', 'She is Canadian.', '나라/세계', '{}', '언어·국적', 3, 'classbank', null, 1344),
  ('australian', 'Australian', 1, '명사', '호주인, 호주의', 'He is Australian.', '나라/세계', '{}', '언어·국적', 3, 'classbank', null, 1345),
  ('french', 'French', 1, '명사', '프랑스어, 프랑스인', 'She speaks French.', '나라/세계', '{}', '언어·국적', 2, 'classbank', null, 1346),
  ('german', 'German', 1, '명사', '독일어, 독일인', 'He speaks German.', '나라/세계', '{}', '언어·국적', 3, 'classbank', null, 1347),
  ('italian', 'Italian', 1, '명사', '이탈리아어, 이탈리아인', 'I like Italian food.', '나라/세계', '{}', '언어·국적', 3, 'classbank', null, 1348),
  ('spanish', 'Spanish', 1, '명사', '스페인어, 스페인인', 'She speaks Spanish.', '나라/세계', '{}', '언어·국적', 3, 'classbank', null, 1349),
  ('festival', 'festival', 1, '명사', '축제', 'We go to the festival.', '행사/활동', '{}', '축제·대회', 2, 'classbank', null, 1350),
  ('celebration', 'celebration', 1, '명사', '축하, 기념 행사', 'We have a big celebration.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1351),
  ('ceremony', 'ceremony', 1, '명사', '의식, 식', 'The ceremony starts at ten.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1352),
  ('wedding', 'wedding', 1, '명사', '결혼식', 'We go to a wedding.', '행사/활동', '{}', '축제·대회', 2, 'classbank', null, 1353),
  ('concert', 'concert', 1, '명사', '음악회, 콘서트', 'We go to a concert.', '행사/활동', array['취미/오락']::text[], '축제·대회', 2, 'classbank', null, 1354),
  ('parade', 'parade', 1, '명사', '퍼레이드, 행진', 'I see a parade.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1355),
  ('contest', 'contest', 1, '명사', '대회, 경연', 'She won the contest.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1356),
  ('competition', 'competition', 1, '명사', '시합, 경쟁', 'We have a dance competition.', '행사/활동', '{}', '축제·대회', 4, 'classbank', null, 1357),
  ('talent-show', 'talent show', 1, '명사', '장기 자랑', 'I sing in the talent show.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1358),
  ('flea-market', 'flea market', 1, '명사', '벼룩시장', 'We go to the flea market.', '행사/활동', '{}', '축제·대회', 3, 'classbank', null, 1359),
  ('bazaar', 'bazaar', 1, '명사', '바자회', 'We sell toys at the bazaar.', '행사/활동', '{}', '축제·대회', 4, 'classbank', null, 1360),
  ('field-trip', 'field trip', 1, '명사', '현장 학습, 소풍', 'We go on a field trip.', '행사/활동', '{}', '학교 행사', 2, 'classbank', null, 1361),
  ('sports-day', 'sports day', 1, '명사', '운동회', 'Sports day is in May.', '행사/활동', '{}', '학교 행사', 2, 'classbank', null, 1362),
  ('school-festival', 'school festival', 1, '명사', '학교 축제', 'We sing at the school festival.', '행사/활동', '{}', '학교 행사', 3, 'classbank', null, 1363),
  ('graduation', 'graduation', 1, '명사', '졸업', 'Graduation is in February.', '행사/활동', '{}', '학교 행사', 3, 'classbank', null, 1364),
  ('entrance-ceremony', 'entrance ceremony', 1, '명사', '입학식', 'The entrance ceremony is in March.', '행사/활동', '{}', '학교 행사', 3, 'classbank', null, 1365),
  ('summer-camp', 'summer camp', 1, '명사', '여름 캠프', 'I go to summer camp.', '행사/활동', '{}', '학교 행사', 2, 'classbank', null, 1366),
  ('winter-camp', 'winter camp', 1, '명사', '겨울 캠프', 'I go to winter camp.', '행사/활동', '{}', '학교 행사', 3, 'classbank', null, 1367),
  ('family-day', 'family day', 1, '명사', '가족의 날', 'We eat out on family day.', '행사/활동', '{}', '기념일', 3, 'classbank', null, 1368),
  ('parents-day', 'parents'' day', 1, '명사', '어버이날', 'Parents'' day is in May.', '행사/활동', array['휴일/기념일']::text[], '기념일', 3, 'classbank', null, 1369),
  ('children-s-day', 'children''s day', 1, '명사', '어린이날', 'Children''s Day is on May 5.', '행사/활동', array['휴일/기념일']::text[], '기념일', 2, 'classbank', null, 1370),
  ('teacher-s-day', 'teacher''s day', 1, '명사', '스승의 날', 'I make a card for Teacher''s Day.', '행사/활동', array['휴일/기념일']::text[], '기념일', 3, 'classbank', null, 1371),
  ('monday', 'Monday', 1, '명사', '월요일', 'I go to school on Monday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1372),
  ('tuesday', 'Tuesday', 1, '명사', '화요일', 'We have art on Tuesday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1373),
  ('wednesday', 'Wednesday', 1, '명사', '수요일', 'I have piano on Wednesday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1374),
  ('thursday', 'Thursday', 1, '명사', '목요일', 'We swim on Thursday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1375),
  ('friday', 'Friday', 1, '명사', '금요일', 'Friday is fun.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1376),
  ('saturday', 'Saturday', 1, '명사', '토요일', 'I play on Saturday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1377),
  ('sunday', 'Sunday', 1, '명사', '일요일', 'I rest on Sunday.', '요일/달력', '{}', '요일', 1, 'classbank', null, 1378),
  ('weekday', 'weekday', 1, '명사', '평일', 'I go to school on a weekday.', '요일/달력', '{}', '요일', 3, 'classbank', null, 1379),
  ('weekend', 'weekend', 1, '명사', '주말', 'I play soccer on the weekend.', '요일/달력', '{}', '요일', 2, 'classbank', null, 1380),
  ('january', 'January', 1, '명사', '1월', 'It is cold in January.', '요일/달력', '{}', '월', 1, 'classbank', null, 1381),
  ('february', 'February', 1, '명사', '2월', 'February is short.', '요일/달력', '{}', '월', 2, 'classbank', null, 1382),
  ('april', 'April', 1, '명사', '4월', 'Flowers bloom in April.', '요일/달력', '{}', '월', 1, 'classbank', null, 1383),
  ('june', 'June', 1, '명사', '6월', 'My birthday is in June.', '요일/달력', '{}', '월', 1, 'classbank', null, 1384),
  ('july', 'July', 1, '명사', '7월', 'It is hot in July.', '요일/달력', '{}', '월', 1, 'classbank', null, 1385),
  ('august', 'August', 1, '명사', '8월', 'We go to the beach in August.', '요일/달력', '{}', '월', 2, 'classbank', null, 1386),
  ('september', 'September', 1, '명사', '9월', 'School starts in September.', '요일/달력', '{}', '월', 2, 'classbank', null, 1387),
  ('october', 'October', 1, '명사', '10월', 'Leaves fall in October.', '요일/달력', '{}', '월', 2, 'classbank', null, 1388),
  ('november', 'November', 1, '명사', '11월', 'It is cool in November.', '요일/달력', '{}', '월', 2, 'classbank', null, 1389),
  ('december', 'December', 1, '명사', '12월', 'Christmas is in December.', '요일/달력', '{}', '월', 2, 'classbank', null, 1390),
  ('cartoon', 'cartoon', 1, '명사', '만화 영화', 'I watch a cartoon.', '취미/오락', '{}', '영상·놀이', 1, 'classbank', null, 1391),
  ('animation', 'animation', 1, '명사', '애니메이션', 'I like animation.', '취미/오락', '{}', '영상·놀이', 3, 'classbank', null, 1392),
  ('comic', 'comic', 1, '명사', '만화책', 'I read a comic.', '취미/오락', '{}', '영상·놀이', 2, 'classbank', null, 1393),
  ('tv', 'TV', 1, '명사', '텔레비전', 'I watch TV after dinner.', '취미/오락', array['과학기술']::text[], '영상·놀이', 1, 'classbank', null, 1394),
  ('youtube', 'YouTube', 1, '명사', '유튜브', 'I watch YouTube.', '취미/오락', '{}', '영상·놀이', 2, 'classbank', null, 1395),
  ('theater', 'theater', 1, '명사', '극장', 'We go to the theater.', '취미/오락', '{}', '영상·놀이', 3, 'classbank', null, 1396),
  ('photograph', 'photograph', 1, '명사', '사진', 'This is a photograph of my family.', '취미/오락', '{}', '영상·놀이', 3, 'classbank', null, 1397),
  ('photo', 'photo', 1, '명사', '사진', 'I take a photo.', '취미/오락', array['과학기술']::text[], '영상·놀이', 2, 'classbank', null, 1398),
  ('puzzle', 'puzzle', 1, '명사', '퍼즐', 'I like puzzles.', '취미/오락', array['장난감']::text[], '게임', 2, 'classbank', null, 1399),
  ('board-game', 'board game', 1, '명사', '보드게임', 'We play a board game.', '취미/오락', array['장난감']::text[], '게임', 2, 'classbank', null, 1400),
  ('card-game', 'card game', 1, '명사', '카드 게임', 'We play a card game.', '취미/오락', '{}', '게임', 2, 'classbank', null, 1401),
  ('computer-game', 'computer game', 1, '명사', '컴퓨터 게임', 'I play a computer game.', '취미/오락', '{}', '게임', 2, 'classbank', null, 1402),
  ('video-game', 'video game', 1, '명사', '비디오 게임', 'He plays a video game.', '취미/오락', '{}', '게임', 2, 'classbank', null, 1403),
  ('karaoke', 'karaoke', 1, '명사', '노래방', 'We go to karaoke.', '취미/오락', '{}', '게임', 3, 'classbank', null, 1404),
  ('magic', 'magic', 1, '명사', '마술, 마법', 'I like magic.', '취미/오락', '{}', '게임', 2, 'classbank', null, 1405),
  ('hobby', 'hobby', 1, '명사', '취미', 'My hobby is drawing.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1406),
  ('camping', 'camping', 1, '명사', '캠핑', 'We go camping.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1407),
  ('fishing', 'fishing', 1, '명사', '낚시', 'Dad goes fishing.', '취미/오락', array['스포츠']::text[], '취미 활동', 2, 'classbank', null, 1408),
  ('drawing', 'drawing', 1, '명사', '그림 그리기', 'Drawing is fun.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1409),
  ('painting', 'painting', 1, '명사', '그림, 색칠하기', 'I like painting.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1410),
  ('reading', 'reading', 1, '명사', '독서', 'Reading is my hobby.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1411),
  ('singing', 'singing', 1, '명사', '노래 부르기', 'Singing is fun.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1412),
  ('dancing', 'dancing', 1, '명사', '춤추기', 'I like dancing.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1413),
  ('cooking', 'cooking', 1, '명사', '요리하기', 'Cooking is fun.', '취미/오락', '{}', '취미 활동', 2, 'classbank', null, 1414),
  ('collecting', 'collecting', 1, '명사', '수집하기', 'Collecting stamps is my hobby.', '취미/오락', '{}', '취미 활동', 3, 'classbank', null, 1415),
  ('excited', 'excited', 1, '형용사', '신나는, 들뜬', 'I am excited about the trip.', '감정', '{}', '기쁨', 2, 'classbank', null, 1416),
  ('cheerful', 'cheerful', 1, '형용사', '쾌활한, 명랑한', 'She is a cheerful girl.', '감정', array['성격']::text[], '기쁨', 3, 'classbank', null, 1417),
  ('joyful', 'joyful', 1, '형용사', '아주 기쁜', 'The children are joyful.', '감정', '{}', '기쁨', 4, 'classbank', null, 1418),
  ('proud', 'proud', 1, '형용사', '자랑스러운', 'I am proud of you.', '감정', '{}', '기쁨', 3, 'classbank', null, 1419),
  ('thankful', 'thankful', 1, '형용사', '감사하는', 'I am thankful for my friends.', '감정', '{}', '기쁨', 3, 'classbank', null, 1420),
  ('grateful', 'grateful', 1, '형용사', '고마워하는', 'I am grateful to my teacher.', '감정', '{}', '기쁨', 4, 'classbank', null, 1421),
  ('surprised', 'surprised', 1, '형용사', '놀란', 'I am surprised.', '감정', '{}', '놀람·두려움', 2, 'classbank', null, 1422),
  ('scared', 'scared', 1, '형용사', '무서워하는', 'I am scared of dogs.', '감정', '{}', '놀람·두려움', 2, 'classbank', null, 1423),
  ('frightened', 'frightened', 1, '형용사', '겁먹은', 'The kitten is frightened.', '감정', '{}', '놀람·두려움', 3, 'classbank', null, 1424),
  ('worried', 'worried', 1, '형용사', '걱정하는', 'Mom is worried.', '감정', '{}', '놀람·두려움', 3, 'classbank', null, 1425),
  ('nervous', 'nervous', 1, '형용사', '긴장한', 'I am nervous before the test.', '감정', '{}', '놀람·두려움', 3, 'classbank', null, 1426),
  ('shy', 'shy', 1, '형용사', '수줍어하는', 'She is shy.', '감정', array['성격']::text[], '놀람·두려움', 2, 'classbank', null, 1427),
  ('embarrassed', 'embarrassed', 1, '형용사', '부끄러운, 당황한', 'I am embarrassed.', '감정', '{}', '놀람·두려움', 4, 'classbank', null, 1428),
  ('sleepy', 'sleepy', 1, '형용사', '졸린', 'I am sleepy.', '감정', '{}', '피곤·지루함', 1, 'classbank', null, 1429),
  ('bored', 'bored', 1, '형용사', '지루한', 'I am bored.', '감정', '{}', '피곤·지루함', 2, 'classbank', null, 1430),
  ('lonely', 'lonely', 1, '형용사', '외로운', 'The old man is lonely.', '감정', '{}', '슬픔·화', 3, 'classbank', null, 1431),
  ('upset', 'upset', 1, '형용사', '속상한', 'She is upset.', '감정', '{}', '슬픔·화', 3, 'classbank', null, 1432),
  ('disappointed', 'disappointed', 1, '형용사', '실망한', 'I am disappointed.', '감정', '{}', '슬픔·화', 4, 'classbank', null, 1433),
  ('jealous', 'jealous', 1, '형용사', '질투하는', 'He is jealous of his brother.', '감정', '{}', '슬픔·화', 4, 'classbank', null, 1434),
  ('confused', 'confused', 1, '형용사', '혼란스러운', 'I am confused.', '감정', '{}', '생각·마음 상태', 4, 'classbank', null, 1435),
  ('interested', 'interested', 1, '형용사', '관심 있는', 'I am interested in space.', '감정', '{}', '생각·마음 상태', 3, 'classbank', null, 1436),
  ('curious', 'curious', 1, '형용사', '궁금한', 'The cat is curious.', '감정', array['성격']::text[], '생각·마음 상태', 3, 'classbank', null, 1437),
  ('brave', 'brave', 1, '형용사', '용감한', 'The firefighter is brave.', '감정', array['성격']::text[], '생각·마음 상태', 2, 'classbank', null, 1438),
  ('calm', 'calm', 1, '형용사', '침착한, 고요한', 'Stay calm.', '감정', '{}', '생각·마음 상태', 3, 'classbank', null, 1439),
  ('relaxed', 'relaxed', 1, '형용사', '느긋한', 'I feel relaxed.', '감정', '{}', '생각·마음 상태', 3, 'classbank', null, 1440),
  ('comfortable', 'comfortable', 1, '형용사', '편안한', 'The sofa is comfortable.', '감정', '{}', '생각·마음 상태', 3, 'classbank', null, 1441),
  ('uncomfortable', 'uncomfortable', 1, '형용사', '불편한', 'These shoes are uncomfortable.', '감정', '{}', '생각·마음 상태', 4, 'classbank', null, 1442),
  ('friendly', 'friendly', 1, '형용사', '친절한, 다정한', 'My teacher is friendly.', '감정', array['성격']::text[], '생각·마음 상태', 2, 'classbank', null, 1443),
  ('silly', 'silly', 1, '형용사', '어리석은, 우스꽝스러운', 'You are so silly!', '감정', array['성격']::text[], '생각·마음 상태', 3, 'classbank', null, 1444),
  ('serious', 'serious', 1, '형용사', '진지한', 'He looks serious.', '감정', array['성격']::text[], '생각·마음 상태', 3, 'classbank', null, 1445),
  ('new-year-s-day', 'New Year''s Day', 1, '명사', '설날 (1월 1일)', 'We eat rice cake soup on New Year''s Day.', '휴일/기념일', '{}', '명절', 2, 'classbank', null, 1446),
  ('lunar-new-year', 'Lunar New Year', 1, '명사', '설날 (음력 새해)', 'We bow to elders on Lunar New Year.', '휴일/기념일', '{}', '명절', 3, 'classbank', null, 1447),
  ('seollal', 'Seollal', 1, '명사', '설날', 'We wear hanbok on Seollal.', '휴일/기념일', '{}', '명절', 3, 'classbank', null, 1448),
  ('chuseok', 'Chuseok', 1, '명사', '추석', 'We see the full moon on Chuseok.', '휴일/기념일', '{}', '명절', 2, 'classbank', null, 1449),
  ('valentine-s-day', 'Valentine''s Day', 1, '명사', '밸런타인데이', 'I give chocolate on Valentine''s Day.', '휴일/기념일', '{}', '서양 기념일', 2, 'classbank', null, 1450),
  ('easter', 'Easter', 1, '명사', '부활절', 'We hunt for eggs at Easter.', '휴일/기념일', '{}', '서양 기념일', 3, 'classbank', null, 1451),
  ('halloween', 'Halloween', 1, '명사', '핼러윈', 'I wear a costume on Halloween.', '휴일/기념일', '{}', '서양 기념일', 2, 'classbank', null, 1452),
  ('thanksgiving', 'Thanksgiving', 1, '명사', '추수감사절', 'We eat turkey on Thanksgiving.', '휴일/기념일', '{}', '서양 기념일', 3, 'classbank', null, 1453),
  ('christmas', 'Christmas', 1, '명사', '크리스마스', 'I love Christmas.', '휴일/기념일', '{}', '서양 기념일', 1, 'classbank', null, 1454),
  ('christmas-eve', 'Christmas Eve', 1, '명사', '크리스마스 이브', 'We eat cake on Christmas Eve.', '휴일/기념일', '{}', '서양 기념일', 2, 'classbank', null, 1455),
  ('gift', 'gift', 1, '명사', '선물', 'This gift is for you.', '휴일/기념일', '{}', '기념일 물건', 1, 'classbank', null, 1456),
  ('costume', 'costume', 1, '명사', '의상, 분장 옷', 'I wear a witch costume.', '휴일/기념일', '{}', '기념일 물건', 3, 'classbank', null, 1457),
  ('pumpkin', 'pumpkin', 1, '명사', '호박', 'The pumpkin is orange.', '휴일/기념일', '{}', '기념일 물건', 2, 'classbank', null, 1458),
  ('santa-claus', 'Santa Claus', 1, '명사', '산타 할아버지', 'Santa Claus brings gifts.', '휴일/기념일', '{}', '기념일 물건', 1, 'classbank', null, 1459),
  ('reindeer', 'reindeer', 1, '명사', '순록', 'The reindeer pulls the sleigh.', '휴일/기념일', '{}', '기념일 물건', 3, 'classbank', null, 1460),
  ('snowman', 'snowman', 1, '명사', '눈사람', 'We make a snowman.', '휴일/기념일', '{}', '기념일 물건', 1, 'classbank', null, 1461),
  ('christmas-tree', 'Christmas tree', 1, '명사', '크리스마스 트리', 'The Christmas tree has lights.', '휴일/기념일', '{}', '기념일 물건', 1, 'classbank', null, 1462),
  ('stocking', 'stocking', 1, '명사', '(크리스마스) 양말', 'I hang a stocking.', '휴일/기념일', '{}', '기념일 물건', 3, 'classbank', null, 1463),
  ('lucky-bag', 'lucky bag', 1, '명사', '복주머니', 'I got a lucky bag.', '휴일/기념일', '{}', '기념일 물건', 3, 'classbank', null, 1464),
  ('rice-cake', 'rice cake', 1, '명사', '떡', 'We eat rice cake soup.', '휴일/기념일', '{}', '기념일 물건', 2, 'classbank', null, 1465),
  ('living-room', 'living room', 1, '명사', '거실', 'We watch TV in the living room.', '집/가구', '{}', '방·공간', 1, 'classbank', null, 1466),
  ('bedroom', 'bedroom', 1, '명사', '침실', 'I sleep in my bedroom.', '집/가구', '{}', '방·공간', 1, 'classbank', null, 1467),
  ('bathroom', 'bathroom', 1, '명사', '욕실, 화장실', 'The bathroom is clean.', '집/가구', '{}', '방·공간', 1, 'classbank', null, 1468),
  ('dining-room', 'dining room', 1, '명사', '식당 (집의)', 'We eat in the dining room.', '집/가구', '{}', '방·공간', 3, 'classbank', null, 1469),
  ('balcony', 'balcony', 1, '명사', '발코니', 'I have plants on the balcony.', '집/가구', '{}', '방·공간', 3, 'classbank', null, 1470),
  ('yard', 'yard', 1, '명사', '마당', 'The dog plays in the yard.', '집/가구', '{}', '방·공간', 2, 'classbank', null, 1471),
  ('garage', 'garage', 1, '명사', '차고', 'The car is in the garage.', '집/가구', '{}', '방·공간', 3, 'classbank', null, 1472),
  ('sofa', 'sofa', 1, '명사', '소파', 'I sit on the sofa.', '집/가구', '{}', '가구', 1, 'classbank', null, 1473),
  ('couch', 'couch', 1, '명사', '긴 의자, 소파', 'The cat is on the couch.', '집/가구', '{}', '가구', 3, 'classbank', null, 1474),
  ('pillow', 'pillow', 1, '명사', '베개', 'I hug my pillow.', '집/가구', '{}', '가구', 2, 'classbank', null, 1475),
  ('blanket', 'blanket', 1, '명사', '담요', 'I have a warm blanket.', '집/가구', '{}', '가구', 2, 'classbank', null, 1476),
  ('shelf', 'shelf', 1, '명사', '선반', 'The book is on the shelf.', '집/가구', array['쇼핑']::text[], '가구', 2, 'classbank', null, 1477),
  ('bookshelf', 'bookshelf', 1, '명사', '책장', 'The bookshelf has many books.', '집/가구', '{}', '가구', 2, 'classbank', null, 1478),
  ('closet', 'closet', 1, '명사', '옷장, 벽장', 'My clothes are in the closet.', '집/가구', '{}', '가구', 3, 'classbank', null, 1479),
  ('wardrobe', 'wardrobe', 1, '명사', '옷장', 'The wardrobe is big.', '집/가구', '{}', '가구', 4, 'classbank', null, 1480),
  ('drawer', 'drawer', 1, '명사', '서랍', 'Open the drawer.', '집/가구', '{}', '가구', 2, 'classbank', null, 1481),
  ('refrigerator', 'refrigerator', 1, '명사', '냉장고', 'The milk is in the refrigerator.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1482),
  ('fridge', 'fridge', 1, '명사', '냉장고', 'Put it in the fridge.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1483),
  ('freezer', 'freezer', 1, '명사', '냉동실', 'The ice cream is in the freezer.', '집/가구', '{}', '가전제품', 3, 'classbank', null, 1484),
  ('oven', 'oven', 1, '명사', '오븐', 'The cake is in the oven.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1485),
  ('microwave', 'microwave', 1, '명사', '전자레인지', 'Heat it in the microwave.', '집/가구', '{}', '가전제품', 3, 'classbank', null, 1486),
  ('sink', 'sink', 1, '명사', '싱크대, 세면대', 'Wash your hands in the sink.', '집/가구', array['과학']::text[], '가전제품', 2, 'classbank', null, 1487),
  ('dishwasher', 'dishwasher', 1, '명사', '식기세척기', 'The dishwasher is on.', '집/가구', '{}', '가전제품', 4, 'classbank', null, 1488),
  ('washing-machine', 'washing machine', 1, '명사', '세탁기', 'The washing machine is loud.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1489),
  ('fan', 'fan', 1, '명사', '선풍기, 부채', 'Turn on the fan.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1490),
  ('air-conditioner', 'air conditioner', 1, '명사', '에어컨', 'Turn on the air conditioner.', '집/가구', '{}', '가전제품', 2, 'classbank', null, 1491),
  ('bathtub', 'bathtub', 1, '명사', '욕조', 'I take a bath in the bathtub.', '집/가구', '{}', '욕실·식탁', 3, 'classbank', null, 1492),
  ('toilet', 'toilet', 1, '명사', '변기, 화장실', 'Where is the toilet?', '집/가구', '{}', '욕실·식탁', 2, 'classbank', null, 1493),
  ('towel', 'towel', 1, '명사', '수건', 'I dry my hands with a towel.', '집/가구', '{}', '욕실·식탁', 2, 'classbank', null, 1494),
  ('toothbrush', 'toothbrush', 1, '명사', '칫솔', 'This is my toothbrush.', '집/가구', '{}', '욕실·식탁', 2, 'classbank', null, 1495),
  ('toothpaste', 'toothpaste', 1, '명사', '치약', 'I need toothpaste.', '집/가구', '{}', '욕실·식탁', 2, 'classbank', null, 1496),
  ('plate', 'plate', 1, '명사', '접시', 'The plate is on the table.', '집/가구', '{}', '욕실·식탁', 1, 'classbank', null, 1497),
  ('chopsticks', 'chopsticks', 1, '명사', '젓가락', 'I use chopsticks.', '집/가구', '{}', '욕실·식탁', 2, 'classbank', null, 1498),
  ('healthy', 'healthy', 1, '형용사', '건강한', 'Vegetables are healthy.', '건강/질병', '{}', '건강 상태', 2, 'classbank', null, 1499),
  ('unhealthy', 'unhealthy', 1, '형용사', '건강하지 않은', 'Too much candy is unhealthy.', '건강/질병', '{}', '건강 상태', 4, 'classbank', null, 1500),
  ('health', 'health', 1, '명사', '건강', 'Health is important.', '건강/질병', '{}', '건강 상태', 3, 'classbank', null, 1501),
  ('pain', 'pain', 1, '명사', '아픔, 통증', 'I feel pain in my leg.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1502),
  ('flu', 'flu', 1, '명사', '독감', 'I have the flu.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1503),
  ('fever', 'fever', 1, '명사', '열', 'I have a fever.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1504),
  ('cough', 'cough', 1, '명사', '기침', 'I have a cough.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1505),
  ('headache', 'headache', 1, '명사', '두통', 'I have a headache.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1506),
  ('stomachache', 'stomachache', 1, '명사', '복통', 'I have a stomachache.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1507),
  ('toothache', 'toothache', 1, '명사', '치통', 'I have a toothache.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1508),
  ('earache', 'earache', 1, '명사', '귀앓이', 'I have an earache.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1509),
  ('sore-throat', 'sore throat', 1, '명사', '목이 아픔', 'I have a sore throat.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1510),
  ('runny-nose', 'runny nose', 1, '명사', '콧물', 'I have a runny nose.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1511),
  ('sneeze', 'sneeze', 1, '동사', '재채기하다', 'I sneeze a lot.', '건강/질병', '{}', '증상', 3, 'classbank', null, 1512),
  ('bruise', 'bruise', 1, '명사', '멍', 'I have a bruise on my knee.', '건강/질병', '{}', '증상', 4, 'classbank', null, 1513),
  ('broken', 'broken', 1, '형용사', '부러진, 고장 난', 'My arm is broken.', '건강/질병', array['상태']::text[], '증상', 2, 'classbank', null, 1514),
  ('medicine', 'medicine', 1, '명사', '약', 'Take your medicine.', '건강/질병', '{}', '치료', 2, 'classbank', null, 1515),
  ('bandage', 'bandage', 1, '명사', '붕대, 반창고', 'I put a bandage on my finger.', '건강/질병', '{}', '치료', 3, 'classbank', null, 1516),
  ('cold-2', 'cold', 2, '명사', '감기', 'I have a cold.', '건강/질병', '{}', '증상', 2, 'classbank', null, 1517),
  ('noodle', 'noodle', 1, '명사', '국수, 면', 'I eat noodles for lunch.', '음식', '{}', '곡물·빵·면', 1, 'classbank', null, 1518),
  ('mall', 'mall', 1, '명사', '쇼핑센터', 'We go to the mall.', '쇼핑', '{}', '가게·사람', 2, 'classbank', null, 1519),
  ('customer', 'customer', 1, '명사', '손님, 고객', 'The customer buys a toy.', '쇼핑', '{}', '가게·사람', 3, 'classbank', null, 1520),
  ('clerk', 'clerk', 1, '명사', '점원', 'The clerk is kind.', '쇼핑', '{}', '가게·사람', 3, 'classbank', null, 1521),
  ('cashier', 'cashier', 1, '명사', '계산원', 'I pay the cashier.', '쇼핑', '{}', '가게·사람', 3, 'classbank', null, 1522),
  ('seller', 'seller', 1, '명사', '파는 사람', 'The seller has fruit.', '쇼핑', '{}', '가게·사람', 3, 'classbank', null, 1523),
  ('buyer', 'buyer', 1, '명사', '사는 사람', 'The buyer likes the bag.', '쇼핑', '{}', '가게·사람', 4, 'classbank', null, 1524),
  ('cart', 'cart', 1, '명사', '카트, 수레', 'Put it in the cart.', '쇼핑', '{}', '가게 물건', 2, 'classbank', null, 1525),
  ('counter', 'counter', 1, '명사', '계산대', 'Pay at the counter.', '쇼핑', '{}', '가게 물건', 3, 'classbank', null, 1526),
  ('receipt', 'receipt', 1, '명사', '영수증', 'Keep the receipt.', '쇼핑', '{}', '가게 물건', 3, 'classbank', null, 1527),
  ('price', 'price', 1, '명사', '가격', 'What is the price?', '쇼핑', array['돈']::text[], '값', 2, 'classbank', null, 1528),
  ('cost', 'cost', 1, '명사', '값, 비용', 'The cost is ten dollars.', '쇼핑', array['돈']::text[], '값', 3, 'classbank', null, 1529),
  ('sale', 'sale', 1, '명사', '할인 판매, 세일', 'The shoes are on sale.', '쇼핑', '{}', '값', 2, 'classbank', null, 1530),
  ('discount', 'discount', 1, '명사', '할인', 'I get a discount.', '쇼핑', '{}', '값', 3, 'classbank', null, 1531),
  ('expensive', 'expensive', 1, '형용사', '비싼', 'This bag is expensive.', '쇼핑', array['돈']::text[], '값', 2, 'classbank', null, 1532),
  ('cash', 'cash', 1, '명사', '현금', 'I pay in cash.', '쇼핑', array['돈']::text[], '값', 2, 'classbank', null, 1533),
  ('closed', 'closed', 1, '형용사', '닫은, 영업이 끝난', 'The shop is closed.', '쇼핑', array['상태']::text[], '가게 상태', 2, 'classbank', null, 1534),
  ('medium', 'medium', 1, '형용사', '중간의, M 사이즈의', 'I want a medium size.', '쇼핑', '{}', '가게 상태', 3, 'classbank', null, 1535),
  ('bill', 'bill', 1, '명사', '지폐, 계산서', 'I have a one-dollar bill.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1536),
  ('credit-card', 'credit card', 1, '명사', '신용카드', 'Mom pays with a credit card.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1537),
  ('wallet', 'wallet', 1, '명사', '지갑', 'My wallet is in my bag.', '돈', '{}', '돈 종류', 2, 'classbank', null, 1538),
  ('purse', 'purse', 1, '명사', '작은 지갑, 핸드백', 'She has a red purse.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1539),
  ('won', 'won', 1, '명사', '원 (한국 돈)', 'It is one thousand won.', '돈', '{}', '돈 종류', 2, 'classbank', null, 1540),
  ('cent', 'cent', 1, '명사', '센트', 'This candy is fifty cents.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1541),
  ('penny', 'penny', 1, '명사', '1센트 동전', 'I found a penny.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1542),
  ('save', 'save', 1, '동사', '저축하다, 아끼다', 'I save my money.', '돈', array['과학기술', '환경']::text[], '저축', 2, 'classbank', null, 1543),
  ('account', 'account', 1, '명사', '계좌', 'I have a bank account.', '돈', '{}', '저축', 4, 'classbank', null, 1544),
  ('allowance', 'allowance', 1, '명사', '용돈', 'I get an allowance every week.', '돈', '{}', '저축', 3, 'classbank', null, 1545),
  ('instrument', 'instrument', 1, '명사', '악기', 'The piano is an instrument.', '음악', '{}', '악기', 3, 'classbank', null, 1546),
  ('keyboard', 'keyboard', 1, '명사', '건반, 키보드', 'I play the keyboard.', '음악', array['과학기술']::text[], '악기', 2, 'classbank', null, 1547),
  ('electric-guitar', 'electric guitar', 1, '명사', '전기 기타', 'He plays the electric guitar.', '음악', '{}', '악기', 3, 'classbank', null, 1548),
  ('bass', 'bass', 1, '명사', '베이스 (악기)', 'He plays the bass.', '음악', '{}', '악기', 4, 'classbank', null, 1549),
  ('cello', 'cello', 1, '명사', '첼로', 'She plays the cello.', '음악', '{}', '악기', 3, 'classbank', null, 1550),
  ('drums', 'drums', 1, '명사', '드럼', 'I play the drums.', '음악', '{}', '악기', 2, 'classbank', null, 1551),
  ('flute', 'flute', 1, '명사', '플루트', 'She plays the flute.', '음악', '{}', '악기', 3, 'classbank', null, 1552),
  ('recorder', 'recorder', 1, '명사', '리코더', 'I play the recorder.', '음악', '{}', '악기', 2, 'classbank', null, 1553),
  ('trumpet', 'trumpet', 1, '명사', '트럼펫', 'He plays the trumpet.', '음악', '{}', '악기', 3, 'classbank', null, 1554),
  ('trombone', 'trombone', 1, '명사', '트롬본', 'The trombone is loud.', '음악', '{}', '악기', 4, 'classbank', null, 1555),
  ('saxophone', 'saxophone', 1, '명사', '색소폰', 'He plays the saxophone.', '음악', '{}', '악기', 4, 'classbank', null, 1556),
  ('clarinet', 'clarinet', 1, '명사', '클라리넷', 'She plays the clarinet.', '음악', '{}', '악기', 4, 'classbank', null, 1557),
  ('harmonica', 'harmonica', 1, '명사', '하모니카', 'I play the harmonica.', '음악', '{}', '악기', 3, 'classbank', null, 1558),
  ('tambourine', 'tambourine', 1, '명사', '탬버린', 'I shake the tambourine.', '음악', '{}', '악기', 3, 'classbank', null, 1559),
  ('triangle', 'triangle', 1, '명사', '트라이앵글 (악기, 삼각형)', 'I hit the triangle.', '음악', array['모양']::text[], '악기', 2, 'classbank', null, 1560),
  ('xylophone', 'xylophone', 1, '명사', '실로폰', 'I play the xylophone.', '음악', '{}', '악기', 3, 'classbank', null, 1561),
  ('cymbal', 'cymbal', 1, '명사', '심벌즈', 'The cymbal is loud.', '음악', '{}', '악기', 4, 'classbank', null, 1562),
  ('microphone', 'microphone', 1, '명사', '마이크', 'I sing into the microphone.', '음악', array['과학기술']::text[], '악기', 3, 'classbank', null, 1563),
  ('orchestra', 'orchestra', 1, '명사', '오케스트라', 'The orchestra plays a song.', '음악', '{}', '음악 요소', 4, 'classbank', null, 1564),
  ('melody', 'melody', 1, '명사', '멜로디, 가락', 'I like this melody.', '음악', '{}', '음악 요소', 3, 'classbank', null, 1565),
  ('rhythm', 'rhythm', 1, '명사', '리듬', 'Clap to the rhythm.', '음악', '{}', '음악 요소', 3, 'classbank', null, 1566),
  ('beat', 'beat', 1, '명사', '박자', 'I like the beat.', '음악', '{}', '음악 요소', 3, 'classbank', null, 1567),
  ('nature', 'nature', 1, '명사', '자연', 'I love nature.', '자연/날씨', array['환경']::text[], '자연 풍경', 2, 'classbank', null, 1568),
  ('valley', 'valley', 1, '명사', '계곡, 골짜기', 'The valley is green.', '자연/날씨', '{}', '자연 풍경', 3, 'classbank', null, 1569),
  ('pond', 'pond', 1, '명사', '연못', 'Ducks swim in the pond.', '자연/날씨', '{}', '자연 풍경', 2, 'classbank', null, 1570),
  ('ocean', 'ocean', 1, '명사', '바다, 대양', 'The ocean is big.', '자연/날씨', array['환경']::text[], '자연 풍경', 2, 'classbank', null, 1571),
  ('waterfall', 'waterfall', 1, '명사', '폭포', 'The waterfall is beautiful.', '자연/날씨', '{}', '자연 풍경', 3, 'classbank', null, 1572),
  ('forest', 'forest', 1, '명사', '숲', 'Deer live in the forest.', '자연/날씨', array['환경']::text[], '자연 풍경', 2, 'classbank', null, 1573),
  ('woods', 'woods', 1, '명사', '숲, 삼림', 'We walk in the woods.', '자연/날씨', '{}', '자연 풍경', 3, 'classbank', null, 1574),
  ('desert', 'desert', 1, '명사', '사막', 'The desert is hot.', '자연/날씨', '{}', '자연 풍경', 3, 'classbank', null, 1575),
  ('leaves', 'leaves', 1, '명사', '나뭇잎 (복수)', 'The leaves turn red.', '자연/날씨', '{}', '식물', 2, 'classbank', null, 1576),
  ('branch', 'branch', 1, '명사', '나뭇가지', 'A bird is on the branch.', '자연/날씨', '{}', '식물', 3, 'classbank', null, 1577),
  ('root', 'root', 1, '명사', '뿌리', 'The plant has long roots.', '자연/날씨', '{}', '식물', 3, 'classbank', null, 1578),
  ('seed', 'seed', 1, '명사', '씨앗', 'I plant a seed.', '자연/날씨', '{}', '식물', 2, 'classbank', null, 1579),
  ('soil', 'soil', 1, '명사', '흙', 'Plants grow in the soil.', '자연/날씨', array['재료']::text[], '식물', 3, 'classbank', null, 1580),
  ('mud', 'mud', 1, '명사', '진흙', 'My shoes are in the mud.', '자연/날씨', '{}', '식물', 3, 'classbank', null, 1581),
  ('sunny', 'sunny', 1, '형용사', '화창한', 'It is sunny today.', '자연/날씨', '{}', '날씨', 1, 'classbank', null, 1582),
  ('cloudy', 'cloudy', 1, '형용사', '흐린', 'It is cloudy today.', '자연/날씨', '{}', '날씨', 1, 'classbank', null, 1583),
  ('rainy', 'rainy', 1, '형용사', '비가 오는', 'It is a rainy day.', '자연/날씨', '{}', '날씨', 1, 'classbank', null, 1584),
  ('snowy', 'snowy', 1, '형용사', '눈이 오는', 'It is a snowy day.', '자연/날씨', '{}', '날씨', 1, 'classbank', null, 1585),
  ('windy', 'windy', 1, '형용사', '바람 부는', 'It is windy today.', '자연/날씨', '{}', '날씨', 1, 'classbank', null, 1586),
  ('foggy', 'foggy', 1, '형용사', '안개 낀', 'It is foggy this morning.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1587),
  ('stormy', 'stormy', 1, '형용사', '폭풍우 치는', 'It is a stormy night.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1588),
  ('humid', 'humid', 1, '형용사', '습한', 'Summer is hot and humid.', '자연/날씨', '{}', '날씨', 4, 'classbank', null, 1589),
  ('freezing', 'freezing', 1, '형용사', '몹시 추운', 'It is freezing outside.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1590),
  ('temperature', 'temperature', 1, '명사', '온도, 기온', 'The temperature is low.', '자연/날씨', array['과학']::text[], '날씨', 3, 'classbank', null, 1591),
  ('degree', 'degree', 1, '명사', '도 (온도 단위)', 'It is twenty degrees.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1592),
  ('sunshine', 'sunshine', 1, '명사', '햇빛', 'I like the sunshine.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1593),
  ('fog', 'fog', 1, '명사', '안개', 'There is fog on the road.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1594),
  ('thunder', 'thunder', 1, '명사', '천둥', 'I hear thunder.', '자연/날씨', '{}', '날씨', 2, 'classbank', null, 1595),
  ('lightning', 'lightning', 1, '명사', '번개', 'I see lightning.', '자연/날씨', '{}', '날씨', 2, 'classbank', null, 1596),
  ('snowflake', 'snowflake', 1, '명사', '눈송이', 'A snowflake is on my hand.', '자연/날씨', '{}', '날씨', 3, 'classbank', null, 1597),
  ('one', 'one', 1, '수사', '하나, 1', 'I have one pencil.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1598),
  ('two', 'two', 1, '수사', '둘, 2', 'I have two eyes.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1599),
  ('three', 'three', 1, '수사', '셋, 3', 'I see three birds.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1600),
  ('four', 'four', 1, '수사', '넷, 4', 'A cat has four legs.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1601),
  ('five', 'five', 1, '수사', '다섯, 5', 'I have five fingers.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1602),
  ('six', 'six', 1, '수사', '여섯, 6', 'I am six years old.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1603),
  ('seven', 'seven', 1, '수사', '일곱, 7', 'There are seven days.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1604),
  ('eight', 'eight', 1, '수사', '여덟, 8', 'A spider has eight legs.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1605),
  ('nine', 'nine', 1, '수사', '아홉, 9', 'I get up at nine.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1606),
  ('ten', 'ten', 1, '수사', '열, 10', 'I have ten toes.', '숫자/시간', '{}', '기수', 1, 'classbank', null, 1607),
  ('eleven', 'eleven', 1, '수사', '열하나, 11', 'A soccer team has eleven players.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1608),
  ('twelve', 'twelve', 1, '수사', '열둘, 12', 'There are twelve months.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1609),
  ('thirteen', 'thirteen', 1, '수사', '열셋, 13', 'My brother is thirteen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1610),
  ('fourteen', 'fourteen', 1, '수사', '열넷, 14', 'She is fourteen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1611),
  ('fifteen', 'fifteen', 1, '수사', '열다섯, 15', 'I have fifteen cards.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1612),
  ('sixteen', 'sixteen', 1, '수사', '열여섯, 16', 'He is sixteen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1613),
  ('seventeen', 'seventeen', 1, '수사', '열일곱, 17', 'She is seventeen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1614),
  ('eighteen', 'eighteen', 1, '수사', '열여덟, 18', 'He is eighteen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1615),
  ('nineteen', 'nineteen', 1, '수사', '열아홉, 19', 'She is nineteen.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1616),
  ('twenty', 'twenty', 1, '수사', '스물, 20', 'I have twenty stickers.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1617),
  ('thirty', 'thirty', 1, '수사', '서른, 30', 'There are thirty days.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1618),
  ('forty', 'forty', 1, '수사', '마흔, 40', 'My uncle is forty.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1619),
  ('fifty', 'fifty', 1, '수사', '쉰, 50', 'I have fifty won.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1620),
  ('sixty', 'sixty', 1, '수사', '예순, 60', 'One hour is sixty minutes.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1621),
  ('seventy', 'seventy', 1, '수사', '일흔, 70', 'My grandpa is seventy.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1622),
  ('eighty', 'eighty', 1, '수사', '여든, 80', 'She is eighty years old.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1623),
  ('ninety', 'ninety', 1, '수사', '아흔, 90', 'The bus has ninety seats.', '숫자/시간', '{}', '기수', 2, 'classbank', null, 1624),
  ('first', 'first', 1, '수사', '첫 번째의', 'I am first.', '숫자/시간', array['독해/이야기']::text[], '서수', 1, 'classbank', null, 1625),
  ('second', 'second', 1, '수사', '두 번째의, 초', 'I am second.', '숫자/시간', '{}', '서수', 1, 'classbank', null, 1626),
  ('third', 'third', 1, '수사', '세 번째의', 'She is third.', '숫자/시간', '{}', '서수', 1, 'classbank', null, 1627),
  ('fourth', 'fourth', 1, '수사', '네 번째의', 'I am in the fourth grade.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1628),
  ('fifth', 'fifth', 1, '수사', '다섯 번째의', 'Today is the fifth.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1629),
  ('sixth', 'sixth', 1, '수사', '여섯 번째의', 'I am in the sixth grade.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1630),
  ('seventh', 'seventh', 1, '수사', '일곱 번째의', 'July is the seventh month.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1631),
  ('eighth', 'eighth', 1, '수사', '여덟 번째의', 'August is the eighth month.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1632),
  ('ninth', 'ninth', 1, '수사', '아홉 번째의', 'September is the ninth month.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1633),
  ('tenth', 'tenth', 1, '수사', '열 번째의', 'October is the tenth month.', '숫자/시간', '{}', '서수', 2, 'classbank', null, 1634),
  ('plus', 'plus', 1, '전치사', '더하기', 'Two plus two is four.', '숫자/시간', '{}', '계산', 2, 'classbank', null, 1635),
  ('minus', 'minus', 1, '전치사', '빼기', 'Five minus two is three.', '숫자/시간', '{}', '계산', 2, 'classbank', null, 1636),
  ('equal', 'equal', 1, '형용사', '같은', 'Two and two equal four.', '숫자/시간', '{}', '계산', 3, 'classbank', null, 1637),
  ('more', 'more', 1, '형용사', '더 많은', 'I want more.', '숫자/시간', '{}', '계산', 2, 'classbank', null, 1638),
  ('less', 'less', 1, '형용사', '더 적은', 'I want less.', '숫자/시간', '{}', '계산', 3, 'classbank', null, 1639),
  ('o-clock', 'o''clock', 1, '부사', '~시 (정각)', 'It is three o''clock.', '숫자/시간', '{}', '시간', 1, 'classbank', null, 1640),
  ('quarter', 'quarter', 1, '명사', '4분의 1, 15분', 'It is a quarter past two.', '숫자/시간', '{}', '시간', 3, 'classbank', null, 1641),
  ('noon', 'noon', 1, '명사', '정오', 'We eat lunch at noon.', '숫자/시간', '{}', '시간', 3, 'classbank', null, 1642),
  ('midnight', 'midnight', 1, '명사', '한밤중, 자정', 'I sleep at midnight.', '숫자/시간', '{}', '시간', 3, 'classbank', null, 1643),
  ('daily', 'daily', 1, '형용사', '매일의', 'I have a daily routine.', '숫자/시간', '{}', '빈도', 3, 'classbank', null, 1644),
  ('every-day', 'every day', 1, '부사', '매일', 'I read every day.', '숫자/시간', '{}', '빈도', 2, 'classbank', null, 1645),
  ('usually', 'usually', 1, '부사', '보통, 대개', 'I usually walk to school.', '숫자/시간', '{}', '빈도', 2, 'classbank', null, 1646),
  ('sometimes', 'sometimes', 1, '부사', '가끔', 'I sometimes play games.', '숫자/시간', '{}', '빈도', 2, 'classbank', null, 1647),
  ('person', 'person', 1, '명사', '사람', 'He is a nice person.', '사람/가족', '{}', '사람', 2, 'classbank', null, 1648),
  ('children', 'children', 1, '명사', '아이들 (복수)', 'The children play outside.', '사람/가족', '{}', '사람', 1, 'classbank', null, 1649),
  ('adult', 'adult', 1, '명사', '어른', 'The adult is kind.', '사람/가족', '{}', '사람', 3, 'classbank', null, 1650),
  ('neighbor', 'neighbor', 1, '명사', '이웃', 'My neighbor is friendly.', '사람/가족', '{}', '사람', 3, 'classbank', null, 1651),
  ('teacher', 'teacher', 1, '명사', '선생님', 'My teacher is kind.', '사람/가족', array['학교/문구', '직업']::text[], '사람', 1, 'classbank', null, 1652),
  ('grandma', 'grandma', 1, '명사', '할머니', 'I love my grandma.', '사람/가족', '{}', '가족', 1, 'classbank', null, 1653),
  ('grandpa', 'grandpa', 1, '명사', '할아버지', 'I love my grandpa.', '사람/가족', '{}', '가족', 1, 'classbank', null, 1654),
  ('grandfather', 'grandfather', 1, '명사', '할아버지', 'My grandfather is old.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1655),
  ('parents', 'parents', 1, '명사', '부모님', 'My parents are kind.', '사람/가족', '{}', '가족', 1, 'classbank', null, 1656),
  ('grandparents', 'grandparents', 1, '명사', '조부모님', 'I visit my grandparents.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1657),
  ('older-sister', 'older sister', 1, '명사', '언니, 누나', 'I have an older sister.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1658),
  ('younger-sister', 'younger sister', 1, '명사', '여동생', 'I have a younger sister.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1659),
  ('older-brother', 'older brother', 1, '명사', '형, 오빠', 'I have an older brother.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1660),
  ('younger-brother', 'younger brother', 1, '명사', '남동생', 'I have a younger brother.', '사람/가족', '{}', '가족', 2, 'classbank', null, 1661),
  ('classroom', 'classroom', 1, '명사', '교실', 'Our classroom is big.', '학교/문구', '{}', '학교 공간', 1, 'classbank', null, 1662),
  ('gym', 'gym', 1, '명사', '체육관', 'We play in the gym.', '학교/문구', '{}', '학교 공간', 2, 'classbank', null, 1663),
  ('cafeteria', 'cafeteria', 1, '명사', '구내식당', 'We eat in the cafeteria.', '학교/문구', '{}', '학교 공간', 3, 'classbank', null, 1664),
  ('recess', 'recess', 1, '명사', '쉬는 시간', 'We play at recess.', '학교/문구', '{}', '학교 공간', 3, 'classbank', null, 1665),
  ('subject', 'subject', 1, '명사', '과목', 'My favorite subject is art.', '학교/문구', '{}', '과목', 2, 'classbank', null, 1666),
  ('math', 'math', 1, '명사', '수학', 'I like math.', '학교/문구', '{}', '과목', 1, 'classbank', null, 1667),
  ('science', 'science', 1, '명사', '과학', 'Science is fun.', '학교/문구', '{}', '과목', 1, 'classbank', null, 1668),
  ('social-studies', 'social studies', 1, '명사', '사회', 'We study maps in social studies.', '학교/문구', '{}', '과목', 3, 'classbank', null, 1669),
  ('art', 'art', 1, '명사', '미술', 'I like art.', '학교/문구', '{}', '과목', 1, 'classbank', null, 1670),
  ('p-e', 'P.E.', 1, '명사', '체육', 'We have P.E. today.', '학교/문구', '{}', '과목', 2, 'classbank', null, 1671),
  ('textbook', 'textbook', 1, '명사', '교과서', 'Open your textbook.', '학교/문구', '{}', '학용품', 2, 'classbank', null, 1672),
  ('workbook', 'workbook', 1, '명사', '문제집, 워크북', 'Do your workbook.', '학교/문구', '{}', '학용품', 2, 'classbank', null, 1673),
  ('notebook', 'notebook', 1, '명사', '공책', 'I write in my notebook.', '학교/문구', '{}', '학용품', 1, 'classbank', null, 1674),
  ('scissors', 'scissors', 1, '명사', '가위', 'I cut paper with scissors.', '학교/문구', '{}', '학용품', 1, 'classbank', null, 1675),
  ('marker', 'marker', 1, '명사', '마커, 매직펜', 'I draw with a marker.', '학교/문구', '{}', '학용품', 2, 'classbank', null, 1676),
  ('colored-pencil', 'colored pencil', 1, '명사', '색연필', 'I have colored pencils.', '학교/문구', '{}', '학용품', 2, 'classbank', null, 1677),
  ('pencil-case', 'pencil case', 1, '명사', '필통', 'My pencil case is blue.', '학교/문구', '{}', '학용품', 1, 'classbank', null, 1678),
  ('whiteboard', 'whiteboard', 1, '명사', '화이트보드', 'Write on the whiteboard.', '학교/문구', '{}', '학용품', 2, 'classbank', null, 1679),
  ('tablet', 'tablet', 1, '명사', '태블릿', 'I use a tablet in class.', '학교/문구', array['과학기술']::text[], '학용품', 3, 'classbank', null, 1680),
  ('homework', 'homework', 1, '명사', '숙제', 'I do my homework.', '학교/문구', '{}', '수업', 1, 'classbank', null, 1681),
  ('quiz', 'quiz', 1, '명사', '퀴즈, 간단한 시험', 'We have a quiz today.', '학교/문구', '{}', '수업', 2, 'classbank', null, 1682),
  ('sentence', 'sentence', 1, '명사', '문장', 'Read the sentence.', '학교/문구', '{}', '수업', 3, 'classbank', null, 1683),
  ('rectangle', 'rectangle', 1, '명사', '직사각형', 'The door is a rectangle.', '모양', '{}', '도형', 2, 'classbank', null, 1684),
  ('oval', 'oval', 1, '명사', '타원형', 'The mirror is an oval.', '모양', '{}', '도형', 3, 'classbank', null, 1685),
  ('diamond', 'diamond', 1, '명사', '마름모, 다이아몬드', 'The kite is a diamond.', '모양', '{}', '도형', 3, 'classbank', null, 1686),
  ('pentagon', 'pentagon', 1, '명사', '오각형', 'A pentagon has five sides.', '모양', '{}', '도형', 4, 'classbank', null, 1687),
  ('hexagon', 'hexagon', 1, '명사', '육각형', 'A hexagon has six sides.', '모양', '{}', '도형', 4, 'classbank', null, 1688),
  ('octagon', 'octagon', 1, '명사', '팔각형', 'A stop sign is an octagon.', '모양', '{}', '도형', 4, 'classbank', null, 1689),
  ('dot', 'dot', 1, '명사', '점', 'Draw a dot.', '모양', '{}', '선·모양', 2, 'classbank', null, 1690),
  ('curve', 'curve', 1, '명사', '곡선', 'The road has a curve.', '모양', '{}', '선·모양', 3, 'classbank', null, 1691),
  ('flat', 'flat', 1, '형용사', '평평한', 'The table is flat.', '모양', '{}', '선·모양', 3, 'classbank', null, 1692),
  ('bottom', 'bottom', 1, '명사', '맨 아래, 바닥', 'Look at the bottom of the page.', '모양', '{}', '선·모양', 2, 'classbank', null, 1693),
  ('football', 'football', 1, '명사', '축구, 미식축구', 'He plays football.', '스포츠', '{}', '구기 종목', 2, 'classbank', null, 1694),
  ('baseball', 'baseball', 1, '명사', '야구', 'I play baseball.', '스포츠', '{}', '구기 종목', 1, 'classbank', null, 1695),
  ('basketball', 'basketball', 1, '명사', '농구', 'I play basketball.', '스포츠', '{}', '구기 종목', 1, 'classbank', null, 1696),
  ('volleyball', 'volleyball', 1, '명사', '배구', 'We play volleyball.', '스포츠', '{}', '구기 종목', 1, 'classbank', null, 1697),
  ('badminton', 'badminton', 1, '명사', '배드민턴', 'We play badminton.', '스포츠', '{}', '구기 종목', 2, 'classbank', null, 1698),
  ('table-tennis', 'table tennis', 1, '명사', '탁구', 'I play table tennis.', '스포츠', '{}', '구기 종목', 2, 'classbank', null, 1699),
  ('golf', 'golf', 1, '명사', '골프', 'Dad plays golf.', '스포츠', '{}', '구기 종목', 2, 'classbank', null, 1700),
  ('bowling', 'bowling', 1, '명사', '볼링', 'We go bowling.', '스포츠', '{}', '구기 종목', 2, 'classbank', null, 1701),
  ('swimming', 'swimming', 1, '명사', '수영', 'I like swimming.', '스포츠', '{}', '운동 활동', 1, 'classbank', null, 1702),
  ('running', 'running', 1, '명사', '달리기', 'Running is fun.', '스포츠', '{}', '운동 활동', 1, 'classbank', null, 1703),
  ('jogging', 'jogging', 1, '명사', '조깅', 'I go jogging.', '스포츠', '{}', '운동 활동', 2, 'classbank', null, 1704),
  ('cycling', 'cycling', 1, '명사', '자전거 타기', 'Cycling is fun.', '스포츠', '{}', '운동 활동', 2, 'classbank', null, 1705),
  ('skating', 'skating', 1, '명사', '스케이트 타기', 'I like skating.', '스포츠', '{}', '운동 활동', 2, 'classbank', null, 1706),
  ('skiing', 'skiing', 1, '명사', '스키 타기', 'We go skiing in winter.', '스포츠', '{}', '운동 활동', 2, 'classbank', null, 1707),
  ('snowboarding', 'snowboarding', 1, '명사', '스노보드 타기', 'Snowboarding is exciting.', '스포츠', '{}', '운동 활동', 3, 'classbank', null, 1708),
  ('surfing', 'surfing', 1, '명사', '서핑', 'Surfing is fun.', '스포츠', '{}', '운동 활동', 3, 'classbank', null, 1709),
  ('boxing', 'boxing', 1, '명사', '권투', 'He likes boxing.', '스포츠', '{}', '무술·개인 종목', 3, 'classbank', null, 1710),
  ('wrestling', 'wrestling', 1, '명사', '레슬링', 'Wrestling is a strong sport.', '스포츠', '{}', '무술·개인 종목', 3, 'classbank', null, 1711),
  ('gymnastics', 'gymnastics', 1, '명사', '체조', 'She does gymnastics.', '스포츠', '{}', '무술·개인 종목', 3, 'classbank', null, 1712),
  ('taekwondo', 'taekwondo', 1, '명사', '태권도', 'I learn taekwondo.', '스포츠', '{}', '무술·개인 종목', 2, 'classbank', null, 1713),
  ('karate', 'karate', 1, '명사', '가라테', 'He learns karate.', '스포츠', '{}', '무술·개인 종목', 3, 'classbank', null, 1714),
  ('yoga', 'yoga', 1, '명사', '요가', 'Mom does yoga.', '스포츠', '{}', '무술·개인 종목', 3, 'classbank', null, 1715),
  ('player', 'player', 1, '명사', '선수, 경기자', 'He is a good player.', '스포츠', '{}', '경기 용어', 2, 'classbank', null, 1716),
  ('coach', 'coach', 1, '명사', '코치, 감독', 'The coach is kind.', '스포츠', '{}', '경기 용어', 3, 'classbank', null, 1717),
  ('bat', 'bat', 1, '명사', '야구 방망이', 'He has a baseball bat.', '스포츠', '{}', '경기 용어', 2, 'classbank', null, 1718),
  ('racket', 'racket', 1, '명사', '라켓', 'I hold a racket.', '스포츠', '{}', '경기 용어', 3, 'classbank', null, 1719),
  ('goal', 'goal', 1, '명사', '골, 목표', 'He scores a goal.', '스포츠', '{}', '경기 용어', 2, 'classbank', null, 1720),
  ('race', 'race', 1, '명사', '경주, 달리기 시합', 'I win the race.', '스포츠', '{}', '경기 용어', 2, 'classbank', null, 1721),
  ('match', 'match', 1, '명사', '경기, 시합', 'We win the match.', '스포츠', '{}', '경기 용어', 3, 'classbank', null, 1722),
  ('huge', 'huge', 1, '형용사', '거대한', 'The whale is huge.', '크기', '{}', null, 3, 'classbank', null, 1723),
  ('giant', 'giant', 1, '형용사', '아주 큰', 'The giant tree is old.', '크기', '{}', null, 3, 'classbank', null, 1724),
  ('tiny', 'tiny', 1, '형용사', '아주 작은', 'The ant is tiny.', '크기', '{}', null, 3, 'classbank', null, 1725),
  ('shallow', 'shallow', 1, '형용사', '얕은', 'The pond is shallow.', '크기', '{}', null, 4, 'classbank', null, 1726),
  ('different', 'different', 1, '형용사', '다른', 'We are different.', '크기', array['상태']::text[], null, 2, 'classbank', null, 1727),
  ('bigger', 'bigger', 1, '형용사', '더 큰', 'A lion is bigger than a cat.', '크기', '{}', null, 2, 'classbank', null, 1728),
  ('smaller', 'smaller', 1, '형용사', '더 작은', 'A mouse is smaller than a cat.', '크기', '{}', null, 2, 'classbank', null, 1729),
  ('taller', 'taller', 1, '형용사', '더 키가 큰', 'He is taller than me.', '크기', '{}', null, 2, 'classbank', null, 1730),
  ('shorter', 'shorter', 1, '형용사', '더 짧은, 더 키가 작은', 'My hair is shorter now.', '크기', '{}', null, 2, 'classbank', null, 1731),
  ('longer', 'longer', 1, '형용사', '더 긴', 'The river is longer than the road.', '크기', '{}', null, 3, 'classbank', null, 1732),
  ('heavier', 'heavier', 1, '형용사', '더 무거운', 'The rock is heavier than the ball.', '크기', '{}', null, 3, 'classbank', null, 1733),
  ('lighter', 'lighter', 1, '형용사', '더 가벼운', 'The feather is lighter than a coin.', '크기', '{}', null, 3, 'classbank', null, 1734),
  ('height', 'height', 1, '명사', '키, 높이', 'What is your height?', '크기', '{}', null, 3, 'classbank', null, 1735),
  ('length', 'length', 1, '명사', '길이', 'Measure the length.', '크기', '{}', null, 3, 'classbank', null, 1736),
  ('weight', 'weight', 1, '명사', '무게', 'What is your weight?', '크기', '{}', null, 3, 'classbank', null, 1737),
  ('universe', 'universe', 1, '명사', '우주', 'The universe is big.', '우주', '{}', '우주 공간', 4, 'classbank', null, 1738),
  ('galaxy', 'galaxy', 1, '명사', '은하', 'Our galaxy has many stars.', '우주', '{}', '우주 공간', 4, 'classbank', null, 1739),
  ('solar-system', 'solar system', 1, '명사', '태양계', 'The solar system has eight planets.', '우주', '{}', '우주 공간', 4, 'classbank', null, 1740),
  ('planet', 'planet', 1, '명사', '행성', 'Earth is a planet.', '우주', '{}', '행성', 3, 'classbank', null, 1741),
  ('mercury', 'Mercury', 1, '명사', '수성', 'Mercury is near the sun.', '우주', '{}', '행성', 4, 'classbank', null, 1742),
  ('venus', 'Venus', 1, '명사', '금성', 'Venus is bright.', '우주', '{}', '행성', 4, 'classbank', null, 1743),
  ('mars', 'Mars', 1, '명사', '화성', 'Mars is red.', '우주', '{}', '행성', 3, 'classbank', null, 1744),
  ('jupiter', 'Jupiter', 1, '명사', '목성', 'Jupiter is a big planet.', '우주', '{}', '행성', 4, 'classbank', null, 1745),
  ('saturn', 'Saturn', 1, '명사', '토성', 'Saturn has rings.', '우주', '{}', '행성', 4, 'classbank', null, 1746),
  ('uranus', 'Uranus', 1, '명사', '천왕성', 'Uranus is a cold planet.', '우주', '{}', '행성', 4, 'classbank', null, 1747),
  ('neptune', 'Neptune', 1, '명사', '해왕성', 'Neptune is far from the sun.', '우주', '{}', '행성', 4, 'classbank', null, 1748),
  ('comet', 'comet', 1, '명사', '혜성', 'A comet has a long tail.', '우주', '{}', '천체·현상', 4, 'classbank', null, 1749),
  ('asteroid', 'asteroid', 1, '명사', '소행성', 'An asteroid is a small rock.', '우주', '{}', '천체·현상', 4, 'classbank', null, 1750),
  ('meteor', 'meteor', 1, '명사', '유성', 'I see a meteor at night.', '우주', '{}', '천체·현상', 4, 'classbank', null, 1751),
  ('gravity', 'gravity', 1, '명사', '중력', 'Gravity pulls things down.', '우주', '{}', '천체·현상', 4, 'classbank', null, 1752),
  ('spaceship', 'spaceship', 1, '명사', '우주선', 'The spaceship flies to Mars.', '우주', '{}', '우주 탐사', 2, 'classbank', null, 1753),
  ('astronaut', 'astronaut', 1, '명사', '우주 비행사', 'The astronaut is in space.', '우주', '{}', '우주 탐사', 3, 'classbank', null, 1754),
  ('alien', 'alien', 1, '명사', '외계인', 'The alien is green.', '우주', '{}', '우주 탐사', 3, 'classbank', null, 1755),
  ('satellite', 'satellite', 1, '명사', '인공위성', 'A satellite goes around Earth.', '우주', '{}', '우주 탐사', 4, 'classbank', null, 1756),
  ('telescope', 'telescope', 1, '명사', '망원경', 'I see stars with a telescope.', '우주', '{}', '우주 탐사', 3, 'classbank', null, 1757),
  ('teddy-bear', 'teddy bear', 1, '명사', '곰 인형', 'I hug my teddy bear.', '장난감', '{}', '인형·장난감', 1, 'classbank', null, 1758),
  ('stuffed-animal', 'stuffed animal', 1, '명사', '동물 인형', 'I have a stuffed animal.', '장난감', '{}', '인형·장난감', 2, 'classbank', null, 1759),
  ('puppet', 'puppet', 1, '명사', '꼭두각시, 손인형', 'The puppet is funny.', '장난감', '{}', '인형·장난감', 3, 'classbank', null, 1760),
  ('toy-car', 'toy car', 1, '명사', '장난감 자동차', 'I have a toy car.', '장난감', '{}', '인형·장난감', 1, 'classbank', null, 1761),
  ('airplane', 'airplane', 1, '명사', '비행기', 'The airplane flies high.', '장난감', array['교통']::text[], '인형·장난감', 1, 'classbank', null, 1762),
  ('helicopter', 'helicopter', 1, '명사', '헬리콥터', 'The helicopter is loud.', '장난감', array['교통']::text[], '인형·장난감', 2, 'classbank', null, 1763),
  ('block', 'block', 1, '명사', '블록, 덩어리', 'I stack a block.', '장난감', '{}', '만들기·놀이', 1, 'classbank', null, 1764),
  ('blocks', 'blocks', 1, '명사', '블록들, 쌓기 나무', 'I play with blocks.', '장난감', '{}', '만들기·놀이', 1, 'classbank', null, 1765),
  ('lego', 'lego', 1, '명사', '레고', 'I build with Lego.', '장난감', '{}', '만들기·놀이', 2, 'classbank', null, 1766),
  ('kite', 'kite', 1, '명사', '연', 'I fly a kite.', '장난감', '{}', '만들기·놀이', 1, 'classbank', null, 1767),
  ('yo-yo', 'yo-yo', 1, '명사', '요요', 'I play with a yo-yo.', '장난감', '{}', '만들기·놀이', 2, 'classbank', null, 1768),
  ('marble', 'marble', 1, '명사', '구슬', 'I have a blue marble.', '장난감', '{}', '만들기·놀이', 2, 'classbank', null, 1769),
  ('spinning-top', 'spinning top', 1, '명사', '팽이', 'I spin the spinning top.', '장난감', '{}', '만들기·놀이', 3, 'classbank', null, 1770),
  ('dice', 'dice', 1, '명사', '주사위', 'Roll the dice.', '장난감', '{}', '만들기·놀이', 2, 'classbank', null, 1771),
  ('jump-rope', 'jump rope', 1, '명사', '줄넘기 줄', 'I jump rope every day.', '장난감', '{}', '탈 것·운동 도구', 2, 'classbank', null, 1772),
  ('hula-hoop', 'hula hoop', 1, '명사', '훌라후프', 'I spin a hula hoop.', '장난감', '{}', '탈 것·운동 도구', 3, 'classbank', null, 1773),
  ('scooter', 'scooter', 1, '명사', '킥보드', 'I ride a scooter.', '장난감', array['교통']::text[], '탈 것·운동 도구', 2, 'classbank', null, 1774),
  ('bike', 'bike', 1, '명사', '자전거', 'I ride my bike.', '장난감', array['교통']::text[], '탈 것·운동 도구', 1, 'classbank', null, 1775),
  ('skateboard', 'skateboard', 1, '명사', '스케이트보드', 'He rides a skateboard.', '장난감', '{}', '탈 것·운동 도구', 3, 'classbank', null, 1776),
  ('transportation', 'transportation', 1, '명사', '교통, 교통수단', 'A bus is transportation.', '교통', '{}', '탈 것', 4, 'classbank', null, 1777),
  ('van', 'van', 1, '명사', '승합차', 'We go by van.', '교통', '{}', '탈 것', 2, 'classbank', null, 1778),
  ('motorcycle', 'motorcycle', 1, '명사', '오토바이', 'He rides a motorcycle.', '교통', '{}', '탈 것', 3, 'classbank', null, 1779),
  ('ferry', 'ferry', 1, '명사', '여객선', 'We take a ferry.', '교통', '{}', '탈 것', 3, 'classbank', null, 1780),
  ('ambulance', 'ambulance', 1, '명사', '구급차', 'The ambulance is fast.', '교통', '{}', '특수 차량', 2, 'classbank', null, 1781),
  ('police-car', 'police car', 1, '명사', '경찰차', 'The police car is loud.', '교통', '{}', '특수 차량', 2, 'classbank', null, 1782),
  ('fire-engine', 'fire engine', 1, '명사', '소방차', 'The fire engine is red.', '교통', '{}', '특수 차량', 2, 'classbank', null, 1783),
  ('school-bus', 'school bus', 1, '명사', '통학 버스', 'I take the school bus.', '교통', '{}', '특수 차량', 2, 'classbank', null, 1784),
  ('traffic-light', 'traffic light', 1, '명사', '신호등', 'Stop at the traffic light.', '교통', '{}', '길·규칙', 2, 'classbank', null, 1785),
  ('crosswalk', 'crosswalk', 1, '명사', '횡단보도', 'Use the crosswalk.', '교통', '{}', '길·규칙', 3, 'classbank', null, 1786),
  ('passenger', 'passenger', 1, '명사', '승객', 'The passenger gets on the bus.', '교통', '{}', '사람', 3, 'classbank', null, 1787),
  ('driver', 'driver', 1, '명사', '운전사', 'The driver is kind.', '교통', array['직업']::text[], '사람', 2, 'classbank', null, 1788),
  ('sail', 'sail', 1, '동사', '항해하다', 'We sail on the sea.', '교통', '{}', '탈 것', 4, 'classbank', null, 1789),
  ('technology', 'technology', 1, '명사', '기술', 'Technology is helpful.', '과학기술', '{}', '기기', 4, 'classbank', null, 1790),
  ('laptop', 'laptop', 1, '명사', '노트북 컴퓨터', 'I use a laptop.', '과학기술', '{}', '기기', 2, 'classbank', null, 1791),
  ('smartphone', 'smartphone', 1, '명사', '스마트폰', 'Mom has a smartphone.', '과학기술', '{}', '기기', 2, 'classbank', null, 1792),
  ('phone', 'phone', 1, '명사', '전화기', 'The phone is ringing.', '과학기술', '{}', '기기', 1, 'classbank', null, 1793),
  ('machine', 'machine', 1, '명사', '기계', 'This machine is loud.', '과학기술', '{}', '기기', 3, 'classbank', null, 1794),
  ('screen', 'screen', 1, '명사', '화면', 'The screen is bright.', '과학기술', '{}', '기기', 3, 'classbank', null, 1795),
  ('printer', 'printer', 1, '명사', '프린터', 'The printer is broken.', '과학기술', '{}', '기기', 3, 'classbank', null, 1796),
  ('speaker', 'speaker', 1, '명사', '스피커', 'The speaker is loud.', '과학기술', '{}', '기기', 3, 'classbank', null, 1797),
  ('headphone', 'headphone', 1, '명사', '헤드폰', 'I use headphones.', '과학기술', '{}', '기기', 3, 'classbank', null, 1798),
  ('earphone', 'earphone', 1, '명사', '이어폰', 'I use earphones.', '과학기술', '{}', '기기', 3, 'classbank', null, 1799),
  ('charger', 'charger', 1, '명사', '충전기', 'I need a charger.', '과학기술', '{}', '기기', 3, 'classbank', null, 1800),
  ('battery', 'battery', 1, '명사', '건전지, 배터리', 'The battery is low.', '과학기술', '{}', '기기', 3, 'classbank', null, 1801),
  ('internet', 'internet', 1, '명사', '인터넷', 'I use the internet.', '과학기술', '{}', '인터넷', 3, 'classbank', null, 1802),
  ('website', 'website', 1, '명사', '웹사이트', 'This website is fun.', '과학기술', '{}', '인터넷', 3, 'classbank', null, 1803),
  ('app', 'app', 1, '명사', '앱', 'I have a new app.', '과학기술', '{}', '인터넷', 2, 'classbank', null, 1804),
  ('message', 'message', 1, '명사', '메시지', 'I send a message.', '과학기술', '{}', '인터넷', 2, 'classbank', null, 1805),
  ('email', 'email', 1, '명사', '이메일', 'I send an email.', '과학기술', '{}', '인터넷', 3, 'classbank', null, 1806),
  ('password', 'password', 1, '명사', '비밀번호', 'Do not tell your password.', '과학기술', '{}', '인터넷', 3, 'classbank', null, 1807),
  ('click', 'click', 1, '동사', '클릭하다', 'Click the button.', '과학기술', '{}', '컴퓨터 동작', 2, 'classbank', null, 1808),
  ('type', 'type', 1, '동사', '(글자를) 입력하다', 'Type your name.', '과학기술', '{}', '컴퓨터 동작', 2, 'classbank', null, 1809),
  ('download', 'download', 1, '동사', '내려받다', 'I download a game.', '과학기술', '{}', '컴퓨터 동작', 3, 'classbank', null, 1810),
  ('upload', 'upload', 1, '동사', '올리다', 'I upload a photo.', '과학기술', '{}', '컴퓨터 동작', 4, 'classbank', null, 1811),
  ('delete', 'delete', 1, '동사', '지우다', 'Delete the file.', '과학기술', '{}', '컴퓨터 동작', 3, 'classbank', null, 1812),
  ('turn-on', 'turn on', 1, '숙어', '(전원을) 켜다', 'Turn on the light.', '과학기술', '{}', '컴퓨터 동작', 2, 'classbank', null, 1813),
  ('turn-off', 'turn off', 1, '숙어', '(전원을) 끄다', 'Turn off the TV.', '과학기술', '{}', '컴퓨터 동작', 2, 'classbank', null, 1814),
  ('ugly', 'ugly', 1, '형용사', '못생긴, 보기 흉한', 'The monster is ugly.', '상태', '{}', '모습·느낌', 2, 'classbank', null, 1815),
  ('shiny', 'shiny', 1, '형용사', '반짝이는', 'The coin is shiny.', '상태', '{}', '모습·느낌', 3, 'classbank', null, 1816),
  ('smooth', 'smooth', 1, '형용사', '매끄러운', 'The stone is smooth.', '상태', array['맛/질감']::text[], '모습·느낌', 3, 'classbank', null, 1817),
  ('rough', 'rough', 1, '형용사', '거친', 'The wall is rough.', '상태', array['맛/질감']::text[], '모습·느낌', 3, 'classbank', null, 1818),
  ('smart', 'smart', 1, '형용사', '똑똑한', 'She is smart.', '상태', array['성격']::text[], '평가', 2, 'classbank', null, 1819),
  ('clever', 'clever', 1, '형용사', '영리한', 'The fox is clever.', '상태', array['성격']::text[], '평가', 3, 'classbank', null, 1820),
  ('difficult', 'difficult', 1, '형용사', '어려운', 'This question is difficult.', '상태', '{}', '평가', 2, 'classbank', null, 1821),
  ('dangerous', 'dangerous', 1, '형용사', '위험한', 'Fire is dangerous.', '상태', '{}', '평가', 3, 'classbank', null, 1822),
  ('special', 'special', 1, '형용사', '특별한', 'Today is a special day.', '상태', '{}', '평가', 2, 'classbank', null, 1823),
  ('important', 'important', 1, '형용사', '중요한', 'It is important.', '상태', '{}', '평가', 2, 'classbank', null, 1824),
  ('careful', 'careful', 1, '형용사', '조심하는', 'Be careful.', '상태', array['성격']::text[], '평가', 2, 'classbank', null, 1825),
  ('useful', 'useful', 1, '형용사', '유용한', 'A map is useful.', '상태', '{}', '평가', 3, 'classbank', null, 1826),
  ('light-2', 'light', 2, '형용사', '가벼운', 'The bag is light.', '상태', '{}', '모습·느낌', 2, 'classbank', null, 1827),
  ('above', 'above', 1, '전치사', '~보다 위에', 'The bird is above the tree.', '위치/방향', '{}', null, 2, 'classbank', null, 1828),
  ('next-to', 'next to', 1, '전치사', '~ 옆에', 'I sit next to Ben.', '위치/방향', '{}', null, 1, 'classbank', null, 1829),
  ('in-front-of', 'in front of', 1, '전치사', '~ 앞에', 'The dog is in front of the door.', '위치/방향', '{}', null, 2, 'classbank', null, 1830),
  ('inside', 'inside', 1, '부사', '안에', 'Come inside.', '위치/방향', '{}', null, 2, 'classbank', null, 1831),
  ('outside', 'outside', 1, '부사', '밖에', 'Let us play outside.', '위치/방향', '{}', null, 2, 'classbank', null, 1832),
  ('forward', 'forward', 1, '부사', '앞으로', 'Move forward.', '위치/방향', '{}', null, 3, 'classbank', null, 1833),
  ('backward', 'backward', 1, '부사', '뒤로', 'Step backward.', '위치/방향', '{}', null, 3, 'classbank', null, 1834),
  ('whose', 'whose', 1, '대명사', '누구의', 'Whose bag is this?', '의문사', '{}', null, 3, 'classbank', null, 1835),
  ('how-many', 'how many', 1, '표현', '몇 개', 'How many apples do you have?', '의문사', '{}', null, 2, 'classbank', null, 1836),
  ('how-much', 'how much', 1, '표현', '얼마, 얼마나 많이', 'How much is it?', '의문사', '{}', null, 2, 'classbank', null, 1837),
  ('how-old', 'how old', 1, '표현', '몇 살', 'How old are you?', '의문사', '{}', null, 1, 'classbank', null, 1838),
  ('how-long', 'how long', 1, '표현', '얼마나 오래, 얼마나 긴', 'How long is the river?', '의문사', '{}', null, 3, 'classbank', null, 1839),
  ('how-often', 'how often', 1, '표현', '얼마나 자주', 'How often do you exercise?', '의문사', '{}', null, 3, 'classbank', null, 1840),
  ('what-time', 'what time', 1, '표현', '몇 시', 'What time is it?', '의문사', '{}', null, 1, 'classbank', null, 1841),
  ('what-color', 'what color', 1, '표현', '무슨 색', 'What color is your bag?', '의문사', '{}', null, 1, 'classbank', null, 1842),
  ('what-kind', 'what kind', 1, '표현', '어떤 종류', 'What kind of food do you like?', '의문사', '{}', null, 2, 'classbank', null, 1843),
  ('helpful', 'helpful', 1, '형용사', '도움이 되는', 'She is helpful.', '성격', '{}', null, 2, 'classbank', null, 1844),
  ('active', 'active', 1, '형용사', '활동적인', 'He is an active boy.', '성격', '{}', null, 3, 'classbank', null, 1845),
  ('honest', 'honest', 1, '형용사', '정직한', 'He is honest.', '성격', '{}', null, 3, 'classbank', null, 1846),
  ('polite', 'polite', 1, '형용사', '예의 바른', 'She is polite.', '성격', '{}', null, 3, 'classbank', null, 1847),
  ('patient', 'patient', 1, '형용사', '참을성 있는', 'Be patient.', '성격', '{}', null, 3, 'classbank', null, 1848),
  ('lazy', 'lazy', 1, '형용사', '게으른', 'The cat is lazy.', '성격', '{}', null, 2, 'classbank', null, 1849),
  ('hardworking', 'hardworking', 1, '형용사', '부지런한', 'My mom is hardworking.', '성격', '{}', null, 3, 'classbank', null, 1850),
  ('creative', 'creative', 1, '형용사', '창의적인', 'She is creative.', '성격', '{}', null, 3, 'classbank', null, 1851),
  ('generous', 'generous', 1, '형용사', '너그러운', 'He is generous.', '성격', '{}', null, 4, 'classbank', null, 1852),
  ('selfish', 'selfish', 1, '형용사', '이기적인', 'Do not be selfish.', '성격', '{}', null, 4, 'classbank', null, 1853),
  ('sour', 'sour', 1, '형용사', '신', 'The lemon is sour.', '맛/질감', array['상태']::text[], '맛', 2, 'classbank', null, 1854),
  ('salty', 'salty', 1, '형용사', '짠', 'The soup is salty.', '맛/질감', array['상태']::text[], '맛', 2, 'classbank', null, 1855),
  ('bitter', 'bitter', 1, '형용사', '쓴', 'Medicine is bitter.', '맛/질감', array['상태']::text[], '맛', 3, 'classbank', null, 1856),
  ('spicy', 'spicy', 1, '형용사', '매운', 'Kimchi is spicy.', '맛/질감', array['상태']::text[], '맛', 2, 'classbank', null, 1857),
  ('delicious', 'delicious', 1, '형용사', '아주 맛있는', 'The cake is delicious.', '맛/질감', array['상태']::text[], '맛', 2, 'classbank', null, 1858),
  ('yummy', 'yummy', 1, '형용사', '맛있는', 'This pizza is yummy.', '맛/질감', '{}', '맛', 1, 'classbank', null, 1859),
  ('tasty', 'tasty', 1, '형용사', '맛있는', 'The soup is tasty.', '맛/질감', '{}', '맛', 2, 'classbank', null, 1860),
  ('juicy', 'juicy', 1, '형용사', '즙이 많은', 'The peach is juicy.', '맛/질감', '{}', '식감', 3, 'classbank', null, 1861),
  ('crunchy', 'crunchy', 1, '형용사', '바삭바삭한', 'The apple is crunchy.', '맛/질감', '{}', '식감', 3, 'classbank', null, 1862),
  ('crispy', 'crispy', 1, '형용사', '바삭한', 'The chicken is crispy.', '맛/질감', '{}', '식감', 3, 'classbank', null, 1863),
  ('chewy', 'chewy', 1, '형용사', '쫄깃한', 'The candy is chewy.', '맛/질감', '{}', '식감', 3, 'classbank', null, 1864),
  ('sticky', 'sticky', 1, '형용사', '끈적끈적한', 'My hands are sticky.', '맛/질감', '{}', '식감', 3, 'classbank', null, 1865),
  ('dentist', 'dentist', 1, '명사', '치과 의사', 'The dentist checks my teeth.', '직업', '{}', '의료·과학', 2, 'classbank', null, 1866),
  ('veterinarian', 'veterinarian', 1, '명사', '수의사', 'The veterinarian helps animals.', '직업', '{}', '의료·과학', 4, 'classbank', null, 1867),
  ('scientist', 'scientist', 1, '명사', '과학자', 'The scientist does an experiment.', '직업', '{}', '의료·과학', 3, 'classbank', null, 1868),
  ('engineer', 'engineer', 1, '명사', '기술자, 공학자', 'My dad is an engineer.', '직업', '{}', '의료·과학', 3, 'classbank', null, 1869),
  ('programmer', 'programmer', 1, '명사', '프로그래머', 'She is a programmer.', '직업', '{}', '의료·과학', 4, 'classbank', null, 1870),
  ('police-officer', 'police officer', 1, '명사', '경찰관', 'The police officer helps people.', '직업', '{}', '안전·생활', 2, 'classbank', null, 1871),
  ('firefighter', 'firefighter', 1, '명사', '소방관', 'The firefighter is brave.', '직업', '{}', '안전·생활', 2, 'classbank', null, 1872),
  ('farmer', 'farmer', 1, '명사', '농부', 'The farmer grows rice.', '직업', '{}', '안전·생활', 1, 'classbank', null, 1873),
  ('chef', 'chef', 1, '명사', '요리사', 'The chef makes pasta.', '직업', '{}', '안전·생활', 2, 'classbank', null, 1874),
  ('baker', 'baker', 1, '명사', '제빵사', 'The baker makes bread.', '직업', '{}', '안전·생활', 3, 'classbank', null, 1875),
  ('flight-attendant', 'flight attendant', 1, '명사', '승무원', 'The flight attendant is kind.', '직업', '{}', '안전·생활', 4, 'classbank', null, 1876),
  ('artist', 'artist', 1, '명사', '화가, 예술가', 'The artist paints a picture.', '직업', '{}', '예술·방송', 2, 'classbank', null, 1877),
  ('singer', 'singer', 1, '명사', '가수', 'She is a singer.', '직업', '{}', '예술·방송', 1, 'classbank', null, 1878),
  ('dancer', 'dancer', 1, '명사', '무용수', 'He is a dancer.', '직업', '{}', '예술·방송', 2, 'classbank', null, 1879),
  ('actor', 'actor', 1, '명사', '배우', 'He is an actor.', '직업', '{}', '예술·방송', 2, 'classbank', null, 1880),
  ('writer', 'writer', 1, '명사', '작가', 'She is a writer.', '직업', '{}', '예술·방송', 2, 'classbank', null, 1881),
  ('photographer', 'photographer', 1, '명사', '사진작가', 'The photographer takes photos.', '직업', '{}', '예술·방송', 3, 'classbank', null, 1882),
  ('designer', 'designer', 1, '명사', '디자이너', 'She is a designer.', '직업', '{}', '예술·방송', 3, 'classbank', null, 1883),
  ('athlete', 'athlete', 1, '명사', '운동선수', 'He is an athlete.', '직업', '{}', '운동', 3, 'classbank', null, 1884),
  ('soccer-player', 'soccer player', 1, '명사', '축구 선수', 'He is a soccer player.', '직업', '{}', '운동', 2, 'classbank', null, 1885),
  ('baseball-player', 'baseball player', 1, '명사', '야구 선수', 'He is a baseball player.', '직업', '{}', '운동', 2, 'classbank', null, 1886),
  ('office-worker', 'office worker', 1, '명사', '회사원', 'My dad is an office worker.', '직업', '{}', '안전·생활', 3, 'classbank', null, 1887),
  ('metal', 'metal', 1, '명사', '금속', 'The spoon is metal.', '재료', '{}', null, 3, 'classbank', null, 1888),
  ('plastic', 'plastic', 1, '명사', '플라스틱', 'The bottle is plastic.', '재료', array['환경']::text[], null, 2, 'classbank', null, 1889),
  ('fabric', 'fabric', 1, '명사', '천, 직물', 'The fabric is soft.', '재료', '{}', null, 4, 'classbank', null, 1890),
  ('cloth', 'cloth', 1, '명사', '천', 'I wipe it with a cloth.', '재료', '{}', null, 3, 'classbank', null, 1891),
  ('rubber', 'rubber', 1, '명사', '고무', 'The ball is rubber.', '재료', '{}', null, 3, 'classbank', null, 1892),
  ('clay', 'clay', 1, '명사', '찰흙', 'I make a cup with clay.', '재료', '{}', null, 2, 'classbank', null, 1893),
  ('cotton', 'cotton', 1, '명사', '면, 목화', 'The shirt is cotton.', '재료', '{}', null, 3, 'classbank', null, 1894),
  ('wool', 'wool', 1, '명사', '양털, 털실', 'The sweater is wool.', '재료', '{}', null, 3, 'classbank', null, 1895),
  ('leather', 'leather', 1, '명사', '가죽', 'The bag is leather.', '재료', '{}', null, 3, 'classbank', null, 1896),
  ('solid', 'solid', 1, '명사', '고체', 'Ice is a solid.', '과학', '{}', null, 4, 'classbank', null, 1897),
  ('liquid', 'liquid', 1, '명사', '액체', 'Water is a liquid.', '과학', '{}', null, 4, 'classbank', null, 1898),
  ('material', 'material', 1, '명사', '재료, 물질', 'What is this material?', '과학', '{}', null, 4, 'classbank', null, 1899),
  ('heat', 'heat', 1, '명사', '열, 더위', 'I feel the heat.', '과학', '{}', null, 3, 'classbank', null, 1900),
  ('force', 'force', 1, '명사', '힘', 'Force moves things.', '과학', '{}', null, 4, 'classbank', null, 1901),
  ('energy', 'energy', 1, '명사', '에너지', 'The sun gives us energy.', '과학', array['환경']::text[], null, 3, 'classbank', null, 1902),
  ('magnet', 'magnet', 1, '명사', '자석', 'A magnet pulls a nail.', '과학', '{}', null, 3, 'classbank', null, 1903),
  ('electricity', 'electricity', 1, '명사', '전기', 'A lamp uses electricity.', '과학', '{}', null, 3, 'classbank', null, 1904),
  ('boil', 'boil', 1, '동사', '끓이다', 'Boil the water.', '과학', '{}', null, 3, 'classbank', null, 1905),
  ('float', 'float', 1, '동사', '뜨다', 'The boat floats.', '과학', '{}', null, 3, 'classbank', null, 1906),
  ('dissolve', 'dissolve', 1, '동사', '녹다, 녹이다', 'Sugar dissolves in water.', '과학', '{}', null, 4, 'classbank', null, 1907),
  ('living-thing', 'living thing', 1, '명사', '생물', 'A plant is a living thing.', '과학', '{}', null, 4, 'classbank', null, 1908),
  ('habitat', 'habitat', 1, '명사', '서식지', 'The forest is the bird''s habitat.', '과학', '{}', null, 4, 'classbank', null, 1909),
  ('environment', 'environment', 1, '명사', '환경', 'We protect the environment.', '과학', array['환경']::text[], null, 4, 'classbank', null, 1910),
  ('trash', 'trash', 1, '명사', '쓰레기', 'Put the trash in the bin.', '환경', '{}', null, 2, 'classbank', null, 1911),
  ('garbage', 'garbage', 1, '명사', '쓰레기', 'Take out the garbage.', '환경', '{}', null, 3, 'classbank', null, 1912),
  ('recycle', 'recycle', 1, '동사', '재활용하다', 'We recycle paper.', '환경', '{}', null, 3, 'classbank', null, 1913),
  ('reuse', 'reuse', 1, '동사', '다시 쓰다', 'Reuse the bag.', '환경', '{}', null, 4, 'classbank', null, 1914),
  ('reduce', 'reduce', 1, '동사', '줄이다', 'Reduce trash.', '환경', '{}', null, 4, 'classbank', null, 1915),
  ('protect', 'protect', 1, '동사', '보호하다', 'We protect nature.', '환경', '{}', null, 3, 'classbank', null, 1916),
  ('pollution', 'pollution', 1, '명사', '오염', 'Air pollution is bad.', '환경', '{}', null, 4, 'classbank', null, 1917),
  ('title', 'title', 1, '명사', '제목', 'What is the title?', '독해/이야기', '{}', null, 3, 'classbank', null, 1918),
  ('author', 'author', 1, '명사', '저자, 작가', 'Who is the author?', '독해/이야기', '{}', null, 3, 'classbank', null, 1919),
  ('illustrator', 'illustrator', 1, '명사', '삽화가', 'The illustrator draws the pictures.', '독해/이야기', '{}', null, 4, 'classbank', null, 1920),
  ('character', 'character', 1, '명사', '등장인물', 'Who is the main character?', '독해/이야기', '{}', null, 3, 'classbank', null, 1921),
  ('setting', 'setting', 1, '명사', '배경', 'The setting is a forest.', '독해/이야기', '{}', null, 4, 'classbank', null, 1922),
  ('beginning', 'beginning', 1, '명사', '시작, 처음', 'The beginning is fun.', '독해/이야기', '{}', null, 3, 'classbank', null, 1923),
  ('solution', 'solution', 1, '명사', '해결책', 'Find a solution.', '독해/이야기', '{}', null, 4, 'classbank', null, 1924),
  ('event', 'event', 1, '명사', '사건, 행사', 'What is the main event?', '독해/이야기', '{}', null, 3, 'classbank', null, 1925),
  ('chapter', 'chapter', 1, '명사', '(책의) 장', 'Read chapter one.', '독해/이야기', '{}', null, 3, 'classbank', null, 1926),
  ('predict', 'predict', 1, '동사', '예측하다', 'Predict what happens next.', '독해/이야기', '{}', null, 4, 'classbank', null, 1927),
  ('imagine', 'imagine', 1, '동사', '상상하다', 'Imagine a big castle.', '독해/이야기', '{}', null, 3, 'classbank', null, 1928),
  ('finally', 'finally', 1, '부사', '마침내, 드디어', 'Finally, we arrive.', '독해/이야기', '{}', null, 3, 'classbank', null, 1929),
  ('bat-2', 'bat', 2, '명사', '박쥐', 'A bat flies at night.', '동물', '{}', '야생 동물', 2, 'classbank', null, 1930),
  ('watch-2', 'watch', 2, '명사', '손목시계', 'I have a new watch.', '사물', '{}', null, 1, 'classbank', null, 1931),
  ('free-2', 'free', 2, '형용사', '무료의', 'The book is free.', '쇼핑', '{}', '값', 2, 'classbank', null, 1932),
  ('open-2', 'open', 2, '형용사', '열려 있는, 영업 중인', 'The store is open.', '쇼핑', '{}', '가게 상태', 2, 'classbank', null, 1933),
  ('change-2', 'change', 2, '명사', '거스름돈', 'Here is your change.', '돈', '{}', '돈 종류', 3, 'classbank', null, 1934),
  ('mouse-2', 'mouse', 2, '명사', '(컴퓨터) 마우스', 'Click with the mouse.', '과학기술', '{}', '기기', 2, 'classbank', null, 1935),
  ('circle-2', 'circle', 2, '동사', '동그라미 치다', 'Circle the answer.', '동작', '{}', '교실 동작', 2, 'classbank', null, 1936),
  ('underline', 'underline', 1, '동사', '밑줄을 긋다', 'Underline the word.', '동작', '{}', '교실 동작', 2, 'classbank', null, 1937),
  ('wake-up', 'wake up', 1, '숙어', '잠에서 깨다', 'I wake up at seven.', '일상생활', '{}', '아침', 1, 'classbank', null, 1938),
  ('get-up', 'get up', 1, '숙어', '일어나다', 'I get up at seven.', '일상생활', '{}', '아침', 1, 'classbank', null, 1939),
  ('wash-my-face', 'wash my face', 1, '숙어', '세수하다', 'I wash my face in the morning.', '일상생활', '{}', '아침', 1, 'classbank', null, 1940),
  ('brush-my-teeth', 'brush my teeth', 1, '숙어', '이를 닦다', 'I brush my teeth after meals.', '일상생활', '{}', '아침', 1, 'classbank', null, 1941),
  ('take-a-shower', 'take a shower', 1, '숙어', '샤워하다', 'I take a shower every day.', '일상생활', '{}', '아침', 1, 'classbank', null, 1942),
  ('get-dressed', 'get dressed', 1, '숙어', '옷을 입다', 'I get dressed for school.', '일상생활', '{}', '아침', 2, 'classbank', null, 1943),
  ('eat-breakfast', 'eat breakfast', 1, '숙어', '아침을 먹다', 'I eat breakfast at eight.', '일상생활', '{}', '식사', 1, 'classbank', null, 1944),
  ('eat-lunch', 'eat lunch', 1, '숙어', '점심을 먹다', 'I eat lunch at school.', '일상생활', '{}', '식사', 1, 'classbank', null, 1945),
  ('eat-dinner', 'eat dinner', 1, '숙어', '저녁을 먹다', 'We eat dinner together.', '일상생활', '{}', '식사', 1, 'classbank', null, 1946),
  ('go-to-school', 'go to school', 1, '숙어', '학교에 가다', 'I go to school by bus.', '일상생활', '{}', '하루 일과', 1, 'classbank', null, 1947),
  ('come-home', 'come home', 1, '숙어', '집에 오다', 'I come home at four.', '일상생활', '{}', '하루 일과', 1, 'classbank', null, 1948),
  ('do-homework', 'do homework', 1, '숙어', '숙제를 하다', 'I do homework after school.', '일상생활', '{}', '하루 일과', 1, 'classbank', null, 1949),
  ('watch-tv', 'watch TV', 1, '숙어', 'TV를 보다', 'I watch TV after dinner.', '일상생활', '{}', '저녁', 1, 'classbank', null, 1950),
  ('read-a-book', 'read a book', 1, '숙어', '책을 읽다', 'I read a book before bed.', '일상생활', '{}', '저녁', 1, 'classbank', null, 1951),
  ('take-a-bath', 'take a bath', 1, '숙어', '목욕하다', 'I take a bath at night.', '일상생활', '{}', '저녁', 1, 'classbank', null, 1952),
  ('go-to-bed', 'go to bed', 1, '숙어', '잠자리에 들다', 'I go to bed at nine.', '일상생활', '{}', '저녁', 1, 'classbank', null, 1953),
  ('open-your-book', 'open your book', 1, '표현', '책을 펴세요', 'Open your book to page ten.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1954),
  ('close-your-book', 'close your book', 1, '표현', '책을 덮으세요', 'Close your book, please.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1955),
  ('raise-your-hand', 'raise your hand', 1, '표현', '손을 드세요', 'Raise your hand, please.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1956),
  ('sit-down', 'sit down', 1, '표현', '앉으세요', 'Sit down, please.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1957),
  ('stand-up', 'stand up', 1, '표현', '일어서세요', 'Stand up, please.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1958),
  ('be-quiet', 'be quiet', 1, '표현', '조용히 하세요', 'Be quiet, please.', '교실 영어', '{}', '수업 지시', 1, 'classbank', null, 1959),
  ('work-together', 'work together', 1, '표현', '함께 활동하세요', 'Let us work together.', '교실 영어', '{}', '수업 지시', 2, 'classbank', null, 1960),
  ('make-a-group', 'make a group', 1, '표현', '모둠을 만드세요', 'Make a group of four.', '교실 영어', '{}', '수업 지시', 2, 'classbank', null, 1961),
  ('take-turns', 'take turns', 1, '표현', '차례를 지키다', 'Take turns, please.', '교실 영어', '{}', '수업 지시', 2, 'classbank', null, 1962),
  ('try-again', 'try again', 1, '표현', '다시 해 보세요', 'Try again!', '교실 영어', '{}', '격려', 1, 'classbank', null, 1963),
  ('good-job', 'good job', 1, '표현', '잘했어요', 'Good job!', '교실 영어', '{}', '격려', 1, 'classbank', null, 1964),
  ('well-done', 'well done', 1, '표현', '참 잘했어요', 'Well done!', '교실 영어', '{}', '격려', 1, 'classbank', null, 1965),
  ('are-you-ready', 'are you ready?', 1, '표현', '준비됐나요?', 'Are you ready?', '교실 영어', '{}', '수업 시작', 1, 'classbank', null, 1966),
  ('let-s-start', 'let''s start', 1, '표현', '시작하자', 'Let''s start the game.', '교실 영어', '{}', '수업 시작', 1, 'classbank', null, 1967),
  ('goodbye', 'goodbye', 1, '표현', '안녕히 가세요', 'Goodbye, see you!', '인사/표현', '{}', '인사', 1, 'classbank', null, 1968),
  ('thank-you', 'thank you', 1, '표현', '고맙습니다', 'Thank you very much.', '인사/표현', '{}', '예의', 1, 'classbank', null, 1969),
  ('excuse-me', 'excuse me', 1, '표현', '실례합니다', 'Excuse me, where is the library?', '인사/표현', '{}', '예의', 1, 'classbank', null, 1970),
  ('you-re-welcome', 'you''re welcome', 1, '표현', '천만에요', 'You''re welcome.', '인사/표현', '{}', '예의', 1, 'classbank', null, 1971),
  ('that-s-okay', 'that''s okay', 1, '표현', '괜찮아요', 'That''s okay.', '인사/표현', '{}', '예의', 1, 'classbank', null, 1972),
  ('maybe', 'maybe', 1, '표현', '아마도', 'Maybe I can go.', '인사/표현', '{}', '대답', 2, 'classbank', null, 1973),
  ('really', 'really', 1, '표현', '정말요?', 'Really?', '인사/표현', '{}', '대답', 2, 'classbank', null, 1974),
  ('of-course', 'of course', 1, '표현', '물론이죠', 'Of course you can.', '인사/표현', '{}', '대답', 2, 'classbank', null, 1975),
  ('wow', 'wow', 1, '표현', '와!', 'Wow, it is big!', '인사/표현', '{}', '감탄', 1, 'classbank', null, 1976),
  ('i-think', 'I think', 1, '표현', '내 생각에는', 'I think it is good.', '인사/표현', '{}', '의견', 2, 'classbank', null, 1977),
  ('i-know', 'I know', 1, '표현', '알아요', 'I know the answer.', '인사/표현', '{}', '의견', 1, 'classbank', null, 1978),
  ('i-don-t-know', 'I don''t know', 1, '표현', '모르겠어요', 'I don''t know.', '인사/표현', '{}', '의견', 1, 'classbank', null, 1979),
  ('i-agree', 'I agree', 1, '표현', '동의해요', 'I agree with you.', '인사/표현', '{}', '의견', 3, 'classbank', null, 1980),
  ('i-don-t-agree', 'I don''t agree', 1, '표현', '동의하지 않아요', 'I don''t agree.', '인사/표현', '{}', '의견', 3, 'classbank', null, 1981),
  ('me-too', 'me too', 1, '표현', '나도요', 'Me too!', '인사/표현', '{}', '의견', 1, 'classbank', null, 1982),
  ('not-me', 'not me', 1, '표현', '난 아니에요', 'Not me!', '인사/표현', '{}', '의견', 2, 'classbank', null, 1983),
  ('let-s-go', 'let''s go', 1, '표현', '가자', 'Let''s go to the park.', '인사/표현', '{}', '제안', 1, 'classbank', null, 1984),
  ('come-on', 'come on', 1, '표현', '어서, 힘내', 'Come on, let us play.', '인사/표현', '{}', '제안', 2, 'classbank', null, 1985)
on conflict (id) do nothing;
