-- 025. 이미 있는 단어(기존 812 + 시범 166)가 다른 카테고리에도 걸릴 때 extra_categories 붙이기.
-- 024 다음에 실행. 이미 그 카테고리에 속해 있으면 건드리지 않는다(여러 번 실행해도 안전).
-- app/scripts/vocab/build-batches.mjs 로 생성.

update public.word_bank set extra_categories = array_append(extra_categories, '동작')
where id in ('be', 'have', 'do', 'go', 'come', 'run', 'walk', 'jump', 'hop', 'skip', 'sit', 'stand', 'stop', 'start', 'begin', 'finish', 'move', 'stay', 'wait', 'follow', 'lead', 'turn', 'cross', 'enter', 'leave', 'arrive', 'return', 'travel', 'visit', 'see', 'look', 'hear', 'listen', 'smell', 'taste', 'touch', 'feel', 'say', 'tell', 'speak', 'talk', 'ask', 'answer', 'call', 'shout', 'yell', 'whisper', 'cry', 'laugh', 'smile', 'sing', 'read', 'write', 'spell', 'draw', 'paint', 'make', 'build', 'fix', 'cut', 'fold', 'glue', 'close', 'push', 'pull', 'lift', 'carry', 'hold', 'put', 'take', 'bring', 'give', 'get', 'send', 'show', 'find', 'hide', 'search', 'lose', 'keep', 'throw', 'catch', 'kick', 'hit', 'bounce', 'roll', 'slide', 'climb', 'crawl', 'swim', 'dance', 'ride', 'drive', 'eat', 'drink', 'cook', 'bake', 'wash', 'clean', 'dry', 'wear', 'sleep', 'wake', 'play', 'study', 'learn', 'teach', 'remember', 'forget', 'know', 'think', 'understand', 'guess', 'choose', 'decide', 'try', 'help', 'use', 'need', 'want', 'like', 'love', 'hate', 'hope', 'wish', 'enjoy', 'share', 'join', 'meet', 'work', 'buy', 'sell', 'pay', 'count', 'add', 'grow', 'pick', 'blow', 'freeze', 'melt', 'burn', 'break', 'tear', 'cover', 'fill', 'pour', 'mix', 'shake', 'press', 'knock', 'clap', 'wave', 'nod', 'bow', 'hug', 'kiss', 'cheer', 'win', 'become', 'happen') and category <> '동작' and not ('동작' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '스포츠')
where id in ('run', 'jump', 'lose', 'throw', 'catch', 'kick', 'hit', 'win', 'game', 'sport', 'soccer', 'tennis', 'hiking', 'team', 'ball', 'glove', 'score') and category <> '스포츠' and not ('스포츠' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '과학')
where id in ('move', 'push', 'pull', 'grow', 'freeze', 'melt', 'burn', 'mix', 'gas', 'sound', 'animal') and category <> '과학' and not ('과학' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '과학기술')
where id in ('touch', 'search', 'button', 'game', 'television', 'video', 'camera', 'computer', 'robot', 'print') and category <> '과학기술' and not ('과학기술' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '학교/문구')
where id in ('answer', 'glue', 'lunch', 'school', 'library', 'music', 'book', 'story', 'desk', 'chair', 'computer', 'student', 'class', 'lesson', 'paper', 'pencil', 'pen', 'eraser', 'ruler', 'crayon', 'board', 'test', 'question', 'word', 'page') and category <> '학교/문구' and not ('학교/문구' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '독해/이야기')
where id in ('answer', 'remember', 'guess', 'happen', 'story', 'picture', 'question', 'page', 'middle', 'end', 'problem', 'idea', 'next', 'then', 'because') and category <> '독해/이야기' and not ('독해/이야기' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '건강/질병')
where id in ('cut', 'sleep', 'burn', 'hospital', 'sick', 'ill', 'hurt', 'doctor', 'nurse', 'exercise') and category <> '건강/질병' and not ('건강/질병' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '취미/오락')
where id in ('show', 'dance', 'party', 'game', 'movie', 'film', 'music', 'song', 'book', 'story', 'television', 'video', 'picture', 'camera') and category <> '취미/오락' and not ('취미/오락' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '교통')
where id in ('ride', 'drive', 'street', 'road', 'airport', 'station', 'bridge', 'rocket', 'car', 'train', 'bicycle', 'bus', 'taxi', 'truck', 'subway', 'plane', 'ship', 'boat', 'ticket', 'pilot') and category <> '교통' and not ('교통' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '직업')
where id in ('cook', 'doctor', 'nurse', 'pilot') and category <> '직업' and not ('직업' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '외모')
where id in ('clean', 'tall', 'short', 'big', 'small', 'thin', 'heavy', 'strong', 'weak', 'young', 'old', 'pretty', 'beautiful', 'nice', 'dirty', 'long', 'straight', 'face', 'hair', 'eye', 'nose', 'mouth', 'ear') and category <> '외모' and not ('외모' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '상태')
where id in ('clean', 'dry', 'short', 'big', 'small', 'thin', 'heavy', 'strong', 'weak', 'young', 'old', 'pretty', 'beautiful', 'nice', 'dirty', 'long', 'hungry', 'thirsty', 'hot', 'warm', 'wet', 'square', 'round', 'thick', 'same', 'good', 'bad', 'new', 'fast', 'slow', 'easy', 'soft', 'full', 'loud', 'quiet', 'bright', 'dark', 'sweet', 'busy', 'safe', 'wrong', 'ready') and category <> '상태' and not ('상태' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '환경')
where id in ('clean', 'water', 'dirty', 'air', 'earth', 'paper', 'land', 'bottle') and category <> '환경' and not ('환경' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '자연/날씨')
where id in ('dry', 'water', 'umbrella', 'farm', 'world', 'sky', 'sun', 'moon', 'star', 'cloud', 'rain', 'snow', 'wind', 'rainbow', 'mountain', 'hill', 'river', 'lake', 'sea', 'beach', 'island', 'jungle', 'field', 'tree', 'flower', 'grass', 'leaf', 'rock', 'stone', 'sand', 'fire', 'air', 'earth', 'spring', 'summer', 'autumn', 'winter', 'season', 'weather', 'hot', 'warm', 'wet', 'storm', 'ice') and category <> '자연/날씨' and not ('자연/날씨' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '쇼핑')
where id in ('choose', 'need', 'want', 'buy', 'sell', 'pay', 'small', 'supermarket', 'market', 'store', 'shop', 'basket', 'bag', 'cheap', 'size', 'large') and category <> '쇼핑' and not ('쇼핑' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '돈')
where id in ('buy', 'sell', 'pay', 'bank', 'cheap', 'money', 'coin', 'dollar', 'spend') and category <> '돈' and not ('돈' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '동물')
where id in ('dog', 'puppy', 'cat', 'kitten', 'rabbit', 'hamster', 'rat', 'squirrel', 'hedgehog', 'fox', 'wolf', 'bear', 'deer', 'raccoon', 'monkey', 'gorilla', 'chimpanzee', 'lion', 'tiger', 'leopard', 'cheetah', 'elephant', 'giraffe', 'zebra', 'hippo', 'rhino', 'kangaroo', 'koala', 'panda', 'camel', 'horse', 'pony', 'cow', 'pig', 'sheep', 'goat', 'donkey', 'chick', 'rooster', 'duck', 'goose', 'bird', 'eagle', 'owl', 'parrot', 'penguin', 'flamingo', 'peacock', 'swan', 'crow', 'sparrow', 'frog', 'toad', 'snake', 'lizard', 'turtle', 'crocodile', 'alligator', 'dinosaur', 'shark', 'whale', 'dolphin', 'octopus', 'squid', 'crab', 'lobster', 'shrimp', 'seal', 'starfish', 'jellyfish', 'seahorse', 'bee', 'butterfly', 'ant', 'spider', 'beetle', 'ladybug', 'mosquito', 'grasshopper', 'snail', 'worm') and category <> '동물' and not ('동물' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '음식')
where id in ('food', 'meal', 'breakfast', 'lunch', 'dinner', 'snack', 'rice', 'bread', 'toast', 'cereal', 'noodles', 'pasta', 'pizza', 'hamburger', 'sandwich', 'hot-dog', 'beef', 'pork', 'egg', 'cheese', 'soup', 'salad', 'curry', 'dumpling', 'pancake', 'waffle', 'french-fries', 'potato', 'sweet-potato', 'corn', 'carrot', 'onion', 'tomato', 'cucumber', 'lettuce', 'cabbage', 'mushroom', 'broccoli', 'spinach', 'bean', 'pea', 'apple', 'banana', 'grape', 'strawberry', 'watermelon', 'melon', 'pear', 'cherry', 'pineapple', 'mango', 'kiwi', 'lemon', 'blueberry', 'raspberry', 'coconut', 'avocado', 'cake', 'cookie', 'biscuit', 'chocolate', 'candy', 'ice-cream', 'donut', 'pie', 'pudding', 'yogurt', 'milk', 'water', 'juice', 'soda', 'tea', 'coffee', 'lemonade', 'salt', 'sugar', 'pepper', 'butter', 'jam', 'honey', 'flour') and category <> '음식' and not ('음식' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '휴일/기념일')
where id in ('cake', 'vacation', 'holiday', 'card', 'candle') and category <> '휴일/기념일' and not ('휴일/기념일' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '재료')
where id in ('water', 'gold', 'silver', 'glass', 'rock', 'stone', 'sand', 'air', 'paper', 'ice', 'wood') and category <> '재료' and not ('재료' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '크기')
where id in ('tall', 'short', 'big', 'small', 'thin', 'heavy', 'long', 'size', 'large', 'thick', 'wide', 'narrow', 'little', 'deep', 'high', 'low', 'same') and category <> '크기' and not ('크기' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '모양')
where id in ('short', 'thin', 'long', 'straight', 'heart', 'star', 'shape', 'square', 'line', 'round', 'thick', 'wide', 'narrow', 'corner', 'side', 'center', 'top') and category <> '모양' and not ('모양' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '성격')
where id in ('nice', 'quiet') and category <> '성격' and not ('성격' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '위치/방향')
where id in ('straight', 'in', 'on', 'under', 'over', 'below', 'beside', 'between', 'behind', 'near', 'far', 'around', 'through', 'across', 'up', 'down', 'left', 'here', 'there') and category <> '위치/방향' and not ('위치/방향' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '몸')
where id in ('face', 'hair', 'eye', 'nose', 'mouth', 'ear', 'body', 'head', 'lip', 'tooth', 'neck', 'shoulder', 'arm', 'hand', 'finger', 'leg', 'knee', 'foot', 'heart') and category <> '몸' and not ('몸' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '행사/활동')
where id in ('birthday', 'party', 'picnic', 'vacation', 'holiday') and category <> '행사/활동' and not ('행사/활동' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '옷')
where id in ('clothes', 'shirt', 'sweater', 'coat', 'skirt', 'pants', 'hat', 'cap', 'pocket', 'button', 'umbrella') and category <> '옷' and not ('옷' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '색깔')
where id in ('red', 'yellow', 'green', 'blue', 'pink', 'brown', 'black', 'white', 'gray', 'gold', 'silver') and category <> '색깔' and not ('색깔' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '장소')
where id in ('city', 'town', 'village', 'street', 'road', 'park', 'school', 'library', 'hospital', 'bank', 'supermarket', 'restaurant', 'market', 'zoo', 'hotel', 'airport', 'station', 'church', 'temple', 'bridge', 'apartment', 'office', 'farm') and category <> '장소' and not ('장소' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '집/가구')
where id in ('apartment', 'television', 'picture', 'house', 'home', 'room', 'kitchen', 'garden', 'door', 'window', 'wall', 'floor', 'ceiling', 'stairs', 'roof', 'gate', 'table', 'desk', 'chair', 'bed', 'lamp', 'clock', 'mirror', 'stove', 'computer', 'shower', 'soap', 'cup', 'glass', 'bowl', 'spoon', 'fork', 'knife') and category <> '집/가구' and not ('집/가구' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '나라/세계')
where id in ('country', 'world', 'flag') and category <> '나라/세계' and not ('나라/세계' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '요일/달력')
where id in ('day', 'week', 'month', 'year', 'today', 'yesterday', 'tomorrow', 'morning', 'afternoon', 'evening', 'night', 'date', 'calendar') and category <> '요일/달력' and not ('요일/달력' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '숫자/시간')
where id in ('today', 'yesterday', 'tomorrow', 'morning', 'afternoon', 'evening', 'night', 'clock', 'zero', 'hundred', 'thousand', 'number', 'many', 'few', 'time', 'hour', 'minute', 'half', 'early', 'late', 'now', 'soon', 'before', 'after', 'always', 'often', 'never') and category <> '숫자/시간' and not ('숫자/시간' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '음악')
where id in ('music', 'song', 'piano', 'guitar', 'violin', 'drum', 'bell') and category <> '음악' and not ('음악' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '감정')
where id in ('happy', 'sad', 'angry', 'mad', 'afraid', 'tired', 'hungry', 'thirsty', 'sick') and category <> '감정' and not ('감정' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '장난감')
where id in ('card', 'ball', 'toy', 'doll', 'robot', 'car', 'train', 'balloon', 'bicycle') and category <> '장난감' and not ('장난감' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '우주')
where id in ('sky', 'sun', 'moon', 'star', 'earth', 'space', 'rocket') and category <> '우주' and not ('우주' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '사람/가족')
where id in ('people', 'man', 'woman', 'boy', 'girl', 'baby', 'child', 'kid', 'family', 'parent', 'mother', 'mom', 'father', 'dad', 'brother', 'sister', 'grandmother', 'aunt', 'uncle', 'cousin', 'friend', 'classmate', 'student', 'son', 'daughter') and category <> '사람/가족' and not ('사람/가족' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '맛/질감')
where id in ('hot', 'warm', 'soft', 'sweet', 'fresh') and category <> '맛/질감' and not ('맛/질감' = any(extra_categories));
update public.word_bank set extra_categories = array_append(extra_categories, '의문사')
where id in ('what', 'who', 'where', 'when', 'why', 'which', 'how') and category <> '의문사' and not ('의문사' = any(extra_categories));
