-- 033. 교육부 2022 기본어휘 초등(*) 800개 중 사전에 없던 95개 + 그림 종류(image_kind) 칸.
-- image_kind: object 사물 / scene 인물 장면 / symbol 도식·기호 / none 그림을 만들지 않음(앱이 단서 카드로 보여 줌).
-- 기존 행은 null(= 예전처럼 그림이 있으면 그림). 024 다음에 실행. 여러 번 실행해도 안전(on conflict do nothing).
-- image_url 은 그림이 생긴 뒤 make-image-url-sql.mjs 로 따로 채운다.
-- app/scripts/vocab/build-moe-elem.mjs 로 생성(원본 데이터: batch-moe-elem.mjs).

alter table public.word_bank add column if not exists image_kind text
  check (image_kind is null or image_kind in ('object', 'scene', 'symbol', 'none'));

insert into public.word_bank
  (id, word, sense_number, part_of_speech, meaning, example_sentence, category, extra_categories, subcategory, level, origin, image_url, image_kind, sort_order)
values
  ('against', 'against', 1, '전치사', '~에 맞서, ~에 기대어', 'We played against their team.', '위치/방향', '{}', '관계', 3, 'moe', null, 'symbol', 3000),
  ('agree', 'agree', 1, '동사', '동의하다', 'I agree with you.', '동작', '{}', '말하기·생각', 2, 'moe', null, 'scene', 3001),
  ('ahead', 'ahead', 1, '부사', '앞에, 앞으로', 'Look ahead when you walk.', '위치/방향', '{}', '방향', 3, 'moe', null, 'symbol', 3002),
  ('almost', 'almost', 1, '부사', '거의', 'I am almost done.', '기능어', '{}', '정도', 3, 'moe', null, 'symbol', 3003),
  ('alone', 'alone', 1, '형용사', '혼자', 'The boy is alone in the room.', '상태', '{}', '사람 상태', 2, 'moe', null, 'scene', 3004),
  ('already', 'already', 1, '부사', '이미, 벌써', 'I already ate lunch.', '기능어', '{}', '시간', 3, 'moe', null, 'none', 3005),
  ('alright', 'alright', 1, '형용사', '괜찮은', 'Are you alright?', '인사/표현', '{}', '안부', 2, 'moe', null, 'scene', 3006),
  ('also', 'also', 1, '부사', '또한, ~도', 'I like cats. I also like dogs.', '기능어', '{}', '연결', 2, 'moe', null, 'none', 3007),
  ('another', 'another', 1, '형용사', '또 하나의, 다른', 'Can I have another cookie?', '기능어', '{}', '수량', 2, 'moe', null, 'symbol', 3008),
  ('area', 'area', 1, '명사', '지역, 구역', 'This area is for children.', '장소', '{}', '장소 일반', 3, 'moe', null, 'symbol', 3009),
  ('beauty', 'beauty', 1, '명사', '아름다움', 'We love the beauty of nature.', '자연/날씨', '{}', '자연 일반', 4, 'moe', null, 'scene', 3010),
  ('believe', 'believe', 1, '동사', '믿다', 'I believe you.', '동작', '{}', '말하기·생각', 3, 'moe', null, 'none', 3011),
  ('birth', 'birth', 1, '명사', '탄생, 출생', 'The birth of the baby made us happy.', '사람/가족', '{}', '가족 일', 4, 'moe', null, 'scene', 3012),
  ('borrow', 'borrow', 1, '동사', '빌리다', 'Can I borrow your pencil?', '동작', '{}', '주고받기', 2, 'moe', null, 'scene', 3013),
  ('both', 'both', 1, '대명사', '둘 다', 'Both of them are my friends.', '기능어', '{}', '수량', 2, 'moe', null, 'symbol', 3014),
  ('business', 'business', 1, '명사', '사업, 일', 'My father has his own business.', '직업', '{}', '일', 4, 'moe', null, 'scene', 3015),
  ('campaign', 'campaign', 1, '명사', '캠페인, 운동', 'We joined a clean-up campaign.', '행사/활동', '{}', '학교 행사', 4, 'moe', null, 'scene', 3016),
  ('certain', 'certain', 1, '형용사', '확실한', 'I am certain he will come.', '상태', '{}', '생각 상태', 4, 'moe', null, 'none', 3017),
  ('check', 'check', 1, '동사', '확인하다', 'Please check your answers.', '동작', '{}', '공부', 2, 'moe', null, 'scene', 3018),
  ('clear', 'clear', 1, '형용사', '맑은, 분명한', 'The sky is clear today.', '상태', '{}', '모양·상태', 3, 'moe', null, 'object', 3019),
  ('collect', 'collect', 1, '동사', '모으다', 'I collect stickers.', '동작', '{}', '취미', 2, 'moe', null, 'scene', 3020),
  ('college', 'college', 1, '명사', '대학', 'My sister goes to college.', '장소', '{}', '학교', 3, 'moe', null, 'object', 3021),
  ('company', 'company', 1, '명사', '회사', 'My mom works at a big company.', '장소', '{}', '일터', 3, 'moe', null, 'object', 3022),
  ('compute', 'compute', 1, '동사', '계산하다', 'The machine can compute fast.', '과학기술', '{}', '컴퓨터', 4, 'moe', null, 'scene', 3023),
  ('condition', 'condition', 1, '명사', '상태, 조건', 'The car is in good condition.', '상태', '{}', '모양·상태', 4, 'moe', null, 'none', 3024),
  ('congratulate', 'congratulate', 1, '동사', '축하하다', 'We congratulate you on winning.', '인사/표현', '{}', '축하', 4, 'moe', null, 'scene', 3025),
  ('control', 'control', 1, '동사', '조종하다, 통제하다', 'He can control the robot.', '동작', '{}', '움직임', 3, 'moe', null, 'scene', 3026),
  ('could', 'could', 1, '조동사', '~할 수 있었다', 'I could swim when I was five.', '기능어', '{}', '조동사', 3, 'moe', null, 'none', 3027),
  ('couple', 'couple', 1, '명사', '한 쌍, 부부', 'A couple is walking in the park.', '사람/가족', '{}', '관계', 3, 'moe', null, 'scene', 3028),
  ('court', 'court', 1, '명사', '(운동) 코트, 법정', 'We play tennis on the court.', '스포츠', '{}', '장소', 3, 'moe', null, 'object', 3029),
  ('culture', 'culture', 1, '명사', '문화', 'I want to learn about Korean culture.', '나라/세계', '{}', '문화', 4, 'moe', null, 'none', 3030),
  ('death', 'death', 1, '명사', '죽음', 'The story is about life and death.', '독해/이야기', '{}', '이야기 소재', 4, 'moe', null, 'none', 3031),
  ('design', 'design', 1, '동사', '디자인하다, 설계하다', 'She designs clothes.', '직업', '{}', '만들기', 3, 'moe', null, 'scene', 3032),
  ('dialogue', 'dialogue', 1, '명사', '대화', 'Read the dialogue with your partner.', '교실 영어', '{}', '말하기', 3, 'moe', null, 'scene', 3033),
  ('discuss', 'discuss', 1, '동사', '토론하다, 의논하다', 'Let''s discuss the problem.', '교실 영어', '{}', '말하기', 3, 'moe', null, 'scene', 3034),
  ('double', 'double', 1, '형용사', '두 배의, 두 개의', 'I want a double burger.', '숫자/시간', '{}', '수량', 3, 'moe', null, 'object', 3035),
  ('during', 'during', 1, '전치사', '~ 동안', 'I slept during the movie.', '기능어', '{}', '시간', 3, 'moe', null, 'none', 3036),
  ('fail', 'fail', 1, '동사', '실패하다', 'Don''t be afraid to fail.', '동작', '{}', '결과', 3, 'moe', null, 'scene', 3037),
  ('favorite', 'favorite', 1, '형용사', '가장 좋아하는', 'Pizza is my favorite food.', '감정', '{}', '좋고 싫음', 1, 'moe', null, 'scene', 3038),
  ('file', 'file', 1, '명사', '파일, 서류철', 'Put the paper in the file.', '학교/문구', '{}', '문구', 3, 'moe', null, 'object', 3039),
  ('focus', 'focus', 1, '동사', '집중하다', 'Focus on your work.', '동작', '{}', '공부', 3, 'moe', null, 'scene', 3040),
  ('form', 'form', 1, '명사', '모양, 형태, 서식', 'Ice is a form of water.', '모양', '{}', '모양 일반', 4, 'moe', null, 'none', 3041),
  ('future', 'future', 1, '명사', '미래', 'I want to be a pilot in the future.', '숫자/시간', '{}', '때', 3, 'moe', null, 'scene', 3042),
  ('gentleman', 'gentleman', 1, '명사', '신사', 'He is a kind gentleman.', '사람/가족', '{}', '사람', 3, 'moe', null, 'object', 3043),
  ('gum', 'gum', 1, '명사', '껌', 'Don''t chew gum in class.', '음식', '{}', '간식', 1, 'moe', null, 'object', 3044),
  ('guy', 'guy', 1, '명사', '남자, 녀석', 'He is a nice guy.', '사람/가족', '{}', '사람', 3, 'moe', null, 'object', 3045),
  ('habit', 'habit', 1, '명사', '습관', 'Brushing your teeth is a good habit.', '일상생활', '{}', '생활 습관', 3, 'moe', null, 'scene', 3046),
  ('hang', 'hang', 1, '동사', '걸다, 매달다', 'Hang your coat on the hook.', '동작', '{}', '손동작', 2, 'moe', null, 'scene', 3047),
  ('hero', 'hero', 1, '명사', '영웅', 'The firefighter is my hero.', '사람/가족', '{}', '사람', 2, 'moe', null, 'scene', 3048),
  ('hike', 'hike', 1, '동사', '하이킹하다, 걷다', 'We hike in the mountains.', '취미/오락', '{}', '야외 활동', 2, 'moe', null, 'scene', 3049),
  ('history', 'history', 1, '명사', '역사', 'I like history class.', '학교/문구', '{}', '과목', 3, 'moe', null, 'object', 3050),
  ('however', 'however', 1, '부사', '그러나', 'It was cold. However, we went out.', '기능어', '{}', '연결', 4, 'moe', null, 'none', 3051),
  ('human', 'human', 1, '명사', '인간, 사람', 'Humans need water to live.', '사람/가족', '{}', '사람', 3, 'moe', null, 'scene', 3052),
  ('hunt', 'hunt', 1, '동사', '사냥하다, 찾다', 'Lions hunt for food.', '동물', '{}', '동물 행동', 3, 'moe', null, 'scene', 3053),
  ('husband', 'husband', 1, '명사', '남편', 'Her husband is a doctor.', '사람/가족', '{}', '가족', 3, 'moe', null, 'scene', 3054),
  ('image', 'image', 1, '명사', '이미지, 그림', 'Look at the image on the screen.', '과학기술', '{}', '컴퓨터', 3, 'moe', null, 'object', 3055),
  ('invite', 'invite', 1, '동사', '초대하다', 'I invite you to my party.', '동작', '{}', '주고받기', 2, 'moe', null, 'scene', 3056),
  ('issue', 'issue', 1, '명사', '문제, 쟁점', 'Pollution is a big issue.', '환경', '{}', '환경 문제', 4, 'moe', null, 'none', 3057),
  ('laser', 'laser', 1, '명사', '레이저', 'The laser light is red.', '과학기술', '{}', '과학 기구', 3, 'moe', null, 'object', 3058),
  ('life', 'life', 1, '명사', '삶, 생명', 'Water is important for life.', '자연/날씨', '{}', '자연 일반', 3, 'moe', null, 'scene', 3059),
  ('marathon', 'marathon', 1, '명사', '마라톤', 'My uncle ran a marathon.', '스포츠', '{}', '운동 경기', 3, 'moe', null, 'scene', 3060),
  ('member', 'member', 1, '명사', '회원, 구성원', 'I am a member of the club.', '사람/가족', '{}', '관계', 3, 'moe', null, 'scene', 3061),
  ('memory', 'memory', 1, '명사', '기억, 추억', 'I have a happy memory of the trip.', '감정', '{}', '생각', 3, 'moe', null, 'scene', 3062),
  ('might', 'might', 1, '조동사', '~일지도 모른다', 'It might rain today.', '기능어', '{}', '조동사', 3, 'moe', null, 'none', 3063),
  ('mind', 'mind', 1, '명사', '마음, 생각', 'Keep it in mind.', '감정', '{}', '생각', 4, 'moe', null, 'none', 3064),
  ('nation', 'nation', 1, '명사', '국가, 나라', 'Korea is a small nation.', '나라/세계', '{}', '나라', 4, 'moe', null, 'object', 3065),
  ('newspaper', 'newspaper', 1, '명사', '신문', 'My dad reads the newspaper.', '사물', '{}', '읽을거리', 2, 'moe', null, 'object', 3066),
  ('nothing', 'nothing', 1, '대명사', '아무것도 (없음)', 'There is nothing in the box.', '기능어', '{}', '수량', 3, 'moe', null, 'symbol', 3067),
  ('part', 'part', 1, '명사', '부분', 'This is my favorite part of the movie.', '기능어', '{}', '수량', 3, 'moe', null, 'symbol', 3068),
  ('partner', 'partner', 1, '명사', '짝, 동료', 'Work with your partner.', '교실 영어', '{}', '짝 활동', 2, 'moe', null, 'scene', 3069),
  ('power', 'power', 1, '명사', '힘, 전력', 'The sun gives us power.', '과학', '{}', '에너지', 3, 'moe', null, 'symbol', 3070),
  ('prince', 'prince', 1, '명사', '왕자', 'The prince lives in a castle.', '독해/이야기', '{}', '이야기 인물', 2, 'moe', null, 'object', 3071),
  ('program', 'program', 1, '명사', '프로그램', 'This TV program is fun.', '과학기술', '{}', '미디어', 3, 'moe', null, 'object', 3072),
  ('project', 'project', 1, '명사', '과제, 프로젝트', 'We did a science project.', '학교/문구', '{}', '공부', 3, 'moe', null, 'scene', 3073),
  ('recreation', 'recreation', 1, '명사', '오락, 레크리에이션', 'We have recreation time after lunch.', '취미/오락', '{}', '놀이', 4, 'moe', null, 'scene', 3074),
  ('restroom', 'restroom', 1, '명사', '화장실', 'Where is the restroom?', '장소', '{}', '건물 안', 1, 'moe', null, 'object', 3075),
  ('should', 'should', 1, '조동사', '~해야 한다', 'You should wash your hands.', '기능어', '{}', '조동사', 3, 'moe', null, 'none', 3076),
  ('ski', 'ski', 1, '동사', '스키를 타다', 'We ski in winter.', '스포츠', '{}', '겨울 운동', 2, 'moe', null, 'scene', 3077),
  ('software', 'software', 1, '명사', '소프트웨어', 'This software is easy to use.', '과학기술', '{}', '컴퓨터', 4, 'moe', null, 'object', 3078),
  ('spaghetti', 'spaghetti', 1, '명사', '스파게티', 'I love spaghetti.', '음식', '{}', '요리', 1, 'moe', null, 'object', 3079),
  ('staff', 'staff', 1, '명사', '직원', 'Ask the staff for help.', '직업', '{}', '일', 3, 'moe', null, 'object', 3080),
  ('steak', 'steak', 1, '명사', '스테이크', 'Dad cooked steak for dinner.', '음식', '{}', '요리', 2, 'moe', null, 'object', 3081),
  ('style', 'style', 1, '명사', '스타일, 방식', 'I like your hair style.', '외모', '{}', '인상', 3, 'moe', null, 'scene', 3082),
  ('tail', 'tail', 1, '명사', '꼬리', 'The dog wags its tail.', '동물', '{}', '동물 몸', 1, 'moe', null, 'object', 3083),
  ('tent', 'tent', 1, '명사', '텐트', 'We slept in a tent.', '취미/오락', '{}', '야외 활동', 1, 'moe', null, 'object', 3084),
  ('thirst', 'thirst', 1, '명사', '목마름, 갈증', 'Water helps your thirst.', '건강/질병', '{}', '몸 상태', 4, 'moe', null, 'scene', 3085),
  ('tire', 'tire', 1, '명사', '타이어', 'The car has a flat tire.', '교통', '{}', '자동차 부품', 3, 'moe', null, 'object', 3086),
  ('track', 'track', 1, '명사', '트랙, 길', 'We run on the track.', '스포츠', '{}', '장소', 3, 'moe', null, 'object', 3087),
  ('twenty-first', 'twenty-first', 1, '형용사', '스물한 번째의', 'Today is the twenty-first of May.', '숫자/시간', '{}', '서수', 3, 'moe', null, 'none', 3088),
  ('twenty-second', 'twenty-second', 1, '형용사', '스물두 번째의', 'My birthday is on the twenty-second.', '숫자/시간', '{}', '서수', 3, 'moe', null, 'none', 3089),
  ('twenty-third', 'twenty-third', 1, '형용사', '스물세 번째의', 'We will meet on the twenty-third.', '숫자/시간', '{}', '서수', 3, 'moe', null, 'none', 3090),
  ('voice', 'voice', 1, '명사', '목소리', 'She has a beautiful voice.', '몸', '{}', '소리', 2, 'moe', null, 'scene', 3091),
  ('wife', 'wife', 1, '명사', '아내', 'His wife is a teacher.', '사람/가족', '{}', '가족', 3, 'moe', null, 'scene', 3092),
  ('wine', 'wine', 1, '명사', '와인, 포도주', 'Grapes are used to make wine.', '음식', '{}', '음료', 4, 'moe', null, 'object', 3093),
  ('worry', 'worry', 1, '동사', '걱정하다', 'Don''t worry. It''s okay.', '감정', '{}', '마음', 2, 'moe', null, 'scene', 3094)
on conflict (id) do nothing;
