// 배치 A — 외모·몸·옷·색깔·장소·나라/세계. 형식은 pilot-new-words.mjs 와 같다:
// [단어, 품사, 뜻, 예문, 레벨(1~4), 소분류, 옵션{id, sense}]  (키 = 대표 카테고리)
// 다른 카테고리에도 걸리는 단어는 빌더가 원본 목록을 보고 extra_categories를 자동으로 붙인다(뜻이 다른
// 행은 옵션 id를 준 두 번째 뜻 행으로 따로 만든다).
export const BATCH_A = {
  외모: [
    ['cute', '형용사', '귀여운', 'The baby is cute.', 1, '인상'],
    ['handsome', '형용사', '잘생긴', 'He is a handsome man.', 3, '인상'],
    ['lovely', '형용사', '사랑스러운', 'What a lovely dress!', 3, '인상'],
    ['neat', '형용사', '단정한', 'Her desk is neat.', 3, '인상'],
    ['messy', '형용사', '지저분한', 'My room is messy.', 3, '인상'],
    ['curly', '형용사', '곱슬곱슬한', 'She has curly hair.', 2, '머리카락'],
    ['wavy', '형용사', '물결 모양의', 'He has wavy hair.', 3, '머리카락'],
    // 목록에 blond / blonde 가 둘 다 있어 하나만 둔다.
    ['blond', '형용사', '금발의', 'The boy has blond hair.', 3, '머리카락'],
    ['brown-haired', '형용사', '갈색 머리의', 'She is brown-haired.', 3, '머리카락'],
    ['black-haired', '형용사', '검은 머리의', 'He is black-haired.', 3, '머리카락'],
    ['bald', '형용사', '대머리의', 'My uncle is bald.', 3, '머리카락'],
    ['beard', '명사', '턱수염', 'He has a long beard.', 3, '얼굴 특징'],
    ['mustache', '명사', '콧수염', 'The man has a mustache.', 3, '얼굴 특징'],
    ['freckles', '명사', '주근깨', 'She has freckles.', 3, '얼굴 특징'],
    ['glasses', '명사', '안경', 'I wear glasses.', 1, '얼굴 특징'],
    // 이미 있는 cool(시원한)의 두 번째 뜻
    ['cool', '형용사', '멋진', 'Your bag is cool!', 2, '인상', { id: 'cool-2', sense: 2 }],
  ],

  몸: [
    ['forehead', '명사', '이마', 'My forehead is hot.', 2, '얼굴'],
    ['eyebrow', '명사', '눈썹', 'She has thick eyebrows.', 2, '얼굴'],
    ['eyelash', '명사', '속눈썹', 'The baby has long eyelashes.', 3, '얼굴'],
    ['cheek', '명사', '볼', 'She has a red cheek.', 2, '얼굴'],
    ['chin', '명사', '턱', 'He has a small chin.', 2, '얼굴'],
    ['tongue', '명사', '혀', 'Stick out your tongue.', 2, '얼굴'],
    ['teeth', '명사', '이, 치아 (복수)', 'I brush my teeth.', 2, '얼굴'],
    ['skin', '명사', '피부', 'The baby has soft skin.', 2, '속·피부'],
    ['elbow', '명사', '팔꿈치', 'My elbow hurts.', 2, '팔·손'],
    ['wrist', '명사', '손목', 'She wears a watch on her wrist.', 3, '팔·손'],
    ['thumb', '명사', '엄지손가락', 'I hurt my thumb.', 2, '팔·손'],
    ['chest', '명사', '가슴', 'My chest is warm.', 2, '몸통'],
    ['stomach', '명사', '배, 위', 'My stomach hurts.', 2, '몸통'],
    ['waist', '명사', '허리', 'The belt is on my waist.', 3, '몸통'],
    ['hip', '명사', '엉덩이, 골반', 'She put her hands on her hips.', 3, '몸통'],
    ['ankle', '명사', '발목', 'I hurt my ankle.', 3, '다리·발'],
    ['feet', '명사', '발 (복수)', 'My feet are cold.', 1, '다리·발'],
    ['toe', '명사', '발가락', 'I have ten toes.', 1, '다리·발'],
    ['bone', '명사', '뼈', 'The dog has a bone.', 2, '속·피부'],
    ['brain', '명사', '뇌, 머리', 'Use your brain.', 2, '속·피부'],
    ['blood', '명사', '피', 'The cut has blood.', 2, '속·피부'],
    // 이미 있는 back(부사 뒤에)의 몸 뜻
    ['back', '명사', '등', 'My back hurts.', 1, '몸통', { id: 'back-2', sense: 2 }],
  ],

  옷: [
    ['T-shirt', '명사', '티셔츠', 'I wear a T-shirt.', 1, '윗옷'],
    ['blouse', '명사', '블라우스', 'She wears a white blouse.', 3, '윗옷'],
    ['sweatshirt', '명사', '맨투맨 티셔츠', 'I wear a sweatshirt.', 3, '윗옷'],
    ['hoodie', '명사', '후드티', 'My hoodie is warm.', 3, '윗옷'],
    ['jacket', '명사', '재킷, 점퍼', 'Put on your jacket.', 2, '윗옷'],
    ['vest', '명사', '조끼', 'He wears a vest.', 3, '윗옷'],
    ['trousers', '명사', '바지', 'These trousers are long.', 3, '아래옷'],
    ['jeans', '명사', '청바지', 'I like blue jeans.', 2, '아래옷'],
    ['shorts', '명사', '반바지', 'I wear shorts in summer.', 1, '아래옷'],
    ['pajamas', '명사', '잠옷', 'I wear pajamas at night.', 2, '잠옷·속옷'],
    ['underwear', '명사', '속옷', 'Put your underwear in the bag.', 2, '잠옷·속옷'],
    ['swimsuit', '명사', '수영복', 'I wear a swimsuit at the pool.', 2, '잠옷·속옷'],
    ['uniform', '명사', '교복, 제복', 'I wear a school uniform.', 2, '잠옷·속옷'],
    ['sneakers', '명사', '운동화', 'I run in my sneakers.', 2, '신발·양말'],
    ['boots', '명사', '부츠', 'I wear boots in winter.', 2, '신발·양말'],
    ['sandals', '명사', '샌들', 'I wear sandals in summer.', 2, '신발·양말'],
    ['slippers', '명사', '슬리퍼', 'Put on your slippers.', 2, '신발·양말'],
    ['helmet', '명사', '헬멧', 'Wear a helmet on your bike.', 2, '모자·소품'],
    ['scarf', '명사', '목도리', 'I wear a scarf in winter.', 2, '모자·소품'],
    ['mittens', '명사', '벙어리장갑', 'The baby has red mittens.', 3, '모자·소품'],
    ['belt', '명사', '허리띠', 'He wears a black belt.', 2, '모자·소품'],
    ['zipper', '명사', '지퍼', 'Close the zipper.', 3, '모자·소품'],
    ['sunglasses', '명사', '선글라스', 'I wear sunglasses in summer.', 2, '모자·소품'],
    ['backpack', '명사', '배낭, 책가방', 'My backpack is heavy.', 1, '모자·소품'],
    ['handbag', '명사', '핸드백', 'Mom has a new handbag.', 3, '모자·소품'],
    // 이미 있는 tie(매다)의 명사 뜻
    ['tie', '명사', '넥타이', 'Dad wears a tie.', 3, '모자·소품', { id: 'tie-2', sense: 2 }],
  ],

  색깔: [
    ['purple', '형용사', '보라색의', 'I like purple grapes.', 1, null],
    ['violet', '형용사', '제비꽃색의, 보라색의', 'The flower is violet.', 3, null],
    ['golden', '형용사', '황금빛의', 'She has golden hair.', 3, null],
    ['beige', '형용사', '베이지색의', 'The sofa is beige.', 3, null],
    ['navy', '형용사', '남색의', 'He wears a navy jacket.', 3, null],
    ['sky blue', '형용사', '하늘색의', 'The sky is sky blue.', 2, null],
    ['light blue', '형용사', '연한 파란색의', 'I have a light blue bag.', 2, null],
    ['dark blue', '형용사', '진한 파란색의', 'The sea is dark blue.', 2, null],
    ['light green', '형용사', '연두색의', 'The leaf is light green.', 2, null],
    ['dark green', '형용사', '진한 초록색의', 'The tree is dark green.', 2, null],
    ['turquoise', '형용사', '청록색의', 'The water is turquoise.', 3, null],
    ['mint', '형용사', '민트색의', 'I have a mint bag.', 3, null],
    ['coral', '형용사', '산호색의', 'She wears a coral dress.', 3, null],
    ['colorful', '형용사', '알록달록한', 'The kite is colorful.', 2, null],
    // 이미 있는 orange(오렌지 과일), peach(복숭아), cream(크림)의 색깔 뜻
    ['orange', '형용사', '주황색의', 'The pumpkin is orange.', 1, null, { id: 'orange-2', sense: 2 }],
    ['peach', '형용사', '복숭아색의', 'She has a peach dress.', 3, null, { id: 'peach-2', sense: 2 }],
    ['cream', '형용사', '크림색의', 'The wall is cream.', 3, null, { id: 'cream-2', sense: 2 }],
  ],

  장소: [
    ['neighborhood', '명사', '동네', 'I live in a nice neighborhood.', 2, '동네·건물'],
    ['building', '명사', '건물', 'The building is tall.', 2, '동네·건물'],
    ['factory', '명사', '공장', 'My uncle works in a factory.', 3, '동네·건물'],
    ['bus stop', '명사', '버스 정류장', 'I wait at the bus stop.', 2, '동네·건물'],
    ['subway station', '명사', '지하철역', 'The subway station is near.', 2, '동네·건물'],
    ['playground', '명사', '놀이터, 운동장', 'We play at the playground.', 1, '놀이·문화'],
    ['movie theater', '명사', '영화관', 'We go to the movie theater.', 2, '놀이·문화'],
    ['museum', '명사', '박물관', 'We visit the museum.', 2, '놀이·문화'],
    ['aquarium', '명사', '수족관', 'I see fish at the aquarium.', 2, '놀이·문화'],
    ['clinic', '명사', '병원, 의원', 'The clinic is near my house.', 3, '공공시설'],
    ['pharmacy', '명사', '약국', 'I buy medicine at the pharmacy.', 2, '공공시설'],
    ['post office', '명사', '우체국', 'I send a letter at the post office.', 2, '공공시설'],
    ['police station', '명사', '경찰서', 'The police station is on the street.', 2, '공공시설'],
    ['fire station', '명사', '소방서', 'The fire station has a red truck.', 2, '공공시설'],
    ['bakery', '명사', '빵집', 'I buy bread at the bakery.', 2, '가게'],
    ['cafe', '명사', '카페', 'We drink juice at the cafe.', 2, '가게'],
    ['bookstore', '명사', '서점', 'I buy a book at the bookstore.', 2, '가게'],
    ['toy store', '명사', '장난감 가게', 'I want to go to the toy store.', 2, '가게'],
    ['clothing store', '명사', '옷 가게', 'We go to the clothing store.', 2, '가게'],
    ['department store', '명사', '백화점', 'Mom is at the department store.', 2, '가게'],
    ['shopping mall', '명사', '쇼핑몰', 'The shopping mall is big.', 2, '가게'],
    ['grocery store', '명사', '식료품점', 'We buy milk at the grocery store.', 3, '가게'],
  ],

  '나라/세계': [
    ['Korea', '명사', '한국', 'I live in Korea.', 1, '아시아'],
    ['South Korea', '명사', '대한민국', 'South Korea is in Asia.', 2, '아시아'],
    ['China', '명사', '중국', 'China is a big country.', 1, '아시아'],
    ['Japan', '명사', '일본', 'Japan is near Korea.', 1, '아시아'],
    ['India', '명사', '인도', 'India is a big country.', 2, '아시아'],
    ['Thailand', '명사', '태국', 'I want to visit Thailand.', 2, '아시아'],
    ['Vietnam', '명사', '베트남', 'Vietnam is warm.', 2, '아시아'],
    ['Philippines', '명사', '필리핀', 'The Philippines has many islands.', 3, '아시아'],
    ['Indonesia', '명사', '인도네시아', 'Indonesia has many islands.', 3, '아시아'],
    ['Singapore', '명사', '싱가포르', 'Singapore is a small country.', 3, '아시아'],
    ['Malaysia', '명사', '말레이시아', 'Malaysia is warm all year.', 3, '아시아'],
    ['Australia', '명사', '호주', 'Kangaroos live in Australia.', 2, '아메리카·오세아니아'],
    ['New Zealand', '명사', '뉴질랜드', 'New Zealand has many sheep.', 2, '아메리카·오세아니아'],
    ['Canada', '명사', '캐나다', 'It is cold in Canada.', 2, '아메리카·오세아니아'],
    ['United States', '명사', '미국', 'He is from the United States.', 2, '아메리카·오세아니아'],
    ['America', '명사', '미국, 아메리카', 'She lives in America.', 1, '아메리카·오세아니아'],
    ['Mexico', '명사', '멕시코', 'I want to visit Mexico.', 2, '아메리카·오세아니아'],
    ['Brazil', '명사', '브라질', 'Brazil is a big country.', 2, '아메리카·오세아니아'],
    ['Argentina', '명사', '아르헨티나', 'Argentina is in South America.', 3, '아메리카·오세아니아'],
    ['United Kingdom', '명사', '영국', 'London is in the United Kingdom.', 3, '유럽·아프리카'],
    ['England', '명사', '잉글랜드, 영국', 'England is a country.', 2, '유럽·아프리카'],
    ['France', '명사', '프랑스', 'Paris is in France.', 2, '유럽·아프리카'],
    ['Germany', '명사', '독일', 'Germany is in Europe.', 2, '유럽·아프리카'],
    ['Italy', '명사', '이탈리아', 'Pizza is from Italy.', 2, '유럽·아프리카'],
    ['Spain', '명사', '스페인', 'Spain is a warm country.', 2, '유럽·아프리카'],
    ['Greece', '명사', '그리스', 'Greece is in Europe.', 3, '유럽·아프리카'],
    ['Egypt', '명사', '이집트', 'The pyramids are in Egypt.', 2, '유럽·아프리카'],
    ['South Africa', '명사', '남아프리카 공화국', 'South Africa is in Africa.', 3, '유럽·아프리카'],
    // 이미 있는 turkey(칠면조)와 다른 뜻
    ['Turkey', '명사', '튀르키예(터키)', 'Turkey is a country.', 3, '유럽·아프리카', { id: 'turkey-2', sense: 2 }],
    ['language', '명사', '언어, 말', 'English is a language.', 2, '언어·국적'],
    ['Korean', '명사', '한국어, 한국인', 'I speak Korean.', 1, '언어·국적'],
    ['Chinese', '명사', '중국어, 중국인', 'She speaks Chinese.', 2, '언어·국적'],
    ['Japanese', '명사', '일본어, 일본인', 'He speaks Japanese.', 2, '언어·국적'],
    ['English', '명사', '영어, 영국인', 'I study English.', 1, '언어·국적'],
    ['American', '명사', '미국인, 미국의', 'He is American.', 2, '언어·국적'],
    ['Canadian', '명사', '캐나다인, 캐나다의', 'She is Canadian.', 3, '언어·국적'],
    ['Australian', '명사', '호주인, 호주의', 'He is Australian.', 3, '언어·국적'],
    ['French', '명사', '프랑스어, 프랑스인', 'She speaks French.', 2, '언어·국적'],
    ['German', '명사', '독일어, 독일인', 'He speaks German.', 3, '언어·국적'],
    ['Italian', '명사', '이탈리아어, 이탈리아인', 'I like Italian food.', 3, '언어·국적'],
    ['Spanish', '명사', '스페인어, 스페인인', 'She speaks Spanish.', 3, '언어·국적'],
  ],
};

// 배치 A 보충 — 처음 표에서 빠진 단어들
BATCH_A['외모'].push(
  ['funny', '형용사', '웃긴, 재미있는', 'The clown is funny.', 1, '인상'],
  ['blonde', '형용사', '금발의 (여성)', 'She has blonde hair.', 3, '머리카락'],
);
BATCH_A['옷'].push(
  ['socks', '명사', '양말', 'I wear socks in winter.', 1, '신발·양말'],
  ['shoes', '명사', '신발', 'I put on my shoes.', 1, '신발·양말'],
  ['gloves', '명사', '장갑', 'I wear gloves in winter.', 2, '모자·소품'],
);
BATCH_A['색깔'].push(['grey', '형용사', '회색의', 'The cat is grey.', 2, null]);
