// 배치 C — 음식(보충)·쇼핑·돈·음악·자연/날씨·숫자/시간·사람/가족·학교/문구.
export const BATCH_C = {
  음식: [['noodle', '명사', '국수, 면', 'I eat noodles for lunch.', 1, '곡물·빵·면']],

  쇼핑: [
    ['mall', '명사', '쇼핑센터', 'We go to the mall.', 2, '가게·사람'],
    ['customer', '명사', '손님, 고객', 'The customer buys a toy.', 3, '가게·사람'],
    ['clerk', '명사', '점원', 'The clerk is kind.', 3, '가게·사람'],
    ['cashier', '명사', '계산원', 'I pay the cashier.', 3, '가게·사람'],
    ['seller', '명사', '파는 사람', 'The seller has fruit.', 3, '가게·사람'],
    ['buyer', '명사', '사는 사람', 'The buyer likes the bag.', 4, '가게·사람'],
    ['cart', '명사', '카트, 수레', 'Put it in the cart.', 2, '가게 물건'],
    ['counter', '명사', '계산대', 'Pay at the counter.', 3, '가게 물건'],
    ['receipt', '명사', '영수증', 'Keep the receipt.', 3, '가게 물건'],
    ['price', '명사', '가격', 'What is the price?', 2, '값'],
    ['cost', '명사', '값, 비용', 'The cost is ten dollars.', 3, '값'],
    ['sale', '명사', '할인 판매, 세일', 'The shoes are on sale.', 2, '값'],
    ['discount', '명사', '할인', 'I get a discount.', 3, '값'],
    ['expensive', '형용사', '비싼', 'This bag is expensive.', 2, '값'],
    ['cash', '명사', '현금', 'I pay in cash.', 2, '값'],
    ['closed', '형용사', '닫은, 영업이 끝난', 'The shop is closed.', 2, '가게 상태'],
    ['medium', '형용사', '중간의, M 사이즈의', 'I want a medium size.', 3, '가게 상태'],
  ],

  돈: [
    ['bill', '명사', '지폐, 계산서', 'I have a one-dollar bill.', 3, '돈 종류'],
    ['credit card', '명사', '신용카드', 'Mom pays with a credit card.', 3, '돈 종류'],
    ['wallet', '명사', '지갑', 'My wallet is in my bag.', 2, '돈 종류'],
    ['purse', '명사', '작은 지갑, 핸드백', 'She has a red purse.', 3, '돈 종류'],
    ['won', '명사', '원 (한국 돈)', 'It is one thousand won.', 2, '돈 종류'],
    ['cent', '명사', '센트', 'This candy is fifty cents.', 3, '돈 종류'],
    ['penny', '명사', '1센트 동전', 'I found a penny.', 3, '돈 종류'],
    ['save', '동사', '저축하다, 아끼다', 'I save my money.', 2, '저축'],
    ['account', '명사', '계좌', 'I have a bank account.', 4, '저축'],
    ['allowance', '명사', '용돈', 'I get an allowance every week.', 3, '저축'],
  ],

  음악: [
    ['instrument', '명사', '악기', 'The piano is an instrument.', 3, '악기'],
    ['keyboard', '명사', '건반, 키보드', 'I play the keyboard.', 2, '악기'],
    ['electric guitar', '명사', '전기 기타', 'He plays the electric guitar.', 3, '악기'],
    ['bass', '명사', '베이스 (악기)', 'He plays the bass.', 4, '악기'],
    ['cello', '명사', '첼로', 'She plays the cello.', 3, '악기'],
    ['drums', '명사', '드럼', 'I play the drums.', 2, '악기'],
    ['flute', '명사', '플루트', 'She plays the flute.', 3, '악기'],
    ['recorder', '명사', '리코더', 'I play the recorder.', 2, '악기'],
    ['trumpet', '명사', '트럼펫', 'He plays the trumpet.', 3, '악기'],
    ['trombone', '명사', '트롬본', 'The trombone is loud.', 4, '악기'],
    ['saxophone', '명사', '색소폰', 'He plays the saxophone.', 4, '악기'],
    ['clarinet', '명사', '클라리넷', 'She plays the clarinet.', 4, '악기'],
    ['harmonica', '명사', '하모니카', 'I play the harmonica.', 3, '악기'],
    ['tambourine', '명사', '탬버린', 'I shake the tambourine.', 3, '악기'],
    ['triangle', '명사', '트라이앵글 (악기, 삼각형)', 'I hit the triangle.', 2, '악기'],
    ['xylophone', '명사', '실로폰', 'I play the xylophone.', 3, '악기'],
    ['cymbal', '명사', '심벌즈', 'The cymbal is loud.', 4, '악기'],
    ['microphone', '명사', '마이크', 'I sing into the microphone.', 3, '악기'],
    ['orchestra', '명사', '오케스트라', 'The orchestra plays a song.', 4, '음악 요소'],
    ['melody', '명사', '멜로디, 가락', 'I like this melody.', 3, '음악 요소'],
    ['rhythm', '명사', '리듬', 'Clap to the rhythm.', 3, '음악 요소'],
    ['beat', '명사', '박자', 'I like the beat.', 3, '음악 요소'],
  ],

  '자연/날씨': [
    ['nature', '명사', '자연', 'I love nature.', 2, '자연 풍경'],
    ['valley', '명사', '계곡, 골짜기', 'The valley is green.', 3, '자연 풍경'],
    ['pond', '명사', '연못', 'Ducks swim in the pond.', 2, '자연 풍경'],
    ['ocean', '명사', '바다, 대양', 'The ocean is big.', 2, '자연 풍경'],
    ['waterfall', '명사', '폭포', 'The waterfall is beautiful.', 3, '자연 풍경'],
    ['forest', '명사', '숲', 'Deer live in the forest.', 2, '자연 풍경'],
    ['woods', '명사', '숲, 삼림', 'We walk in the woods.', 3, '자연 풍경'],
    ['desert', '명사', '사막', 'The desert is hot.', 3, '자연 풍경'],
    ['leaves', '명사', '나뭇잎 (복수)', 'The leaves turn red.', 2, '식물'],
    ['branch', '명사', '나뭇가지', 'A bird is on the branch.', 3, '식물'],
    ['root', '명사', '뿌리', 'The plant has long roots.', 3, '식물'],
    ['seed', '명사', '씨앗', 'I plant a seed.', 2, '식물'],
    ['soil', '명사', '흙', 'Plants grow in the soil.', 3, '식물'],
    ['mud', '명사', '진흙', 'My shoes are in the mud.', 3, '식물'],
    ['sunny', '형용사', '화창한', 'It is sunny today.', 1, '날씨'],
    ['cloudy', '형용사', '흐린', 'It is cloudy today.', 1, '날씨'],
    ['rainy', '형용사', '비가 오는', 'It is a rainy day.', 1, '날씨'],
    ['snowy', '형용사', '눈이 오는', 'It is a snowy day.', 1, '날씨'],
    ['windy', '형용사', '바람 부는', 'It is windy today.', 1, '날씨'],
    ['foggy', '형용사', '안개 낀', 'It is foggy this morning.', 3, '날씨'],
    ['stormy', '형용사', '폭풍우 치는', 'It is a stormy night.', 3, '날씨'],
    ['humid', '형용사', '습한', 'Summer is hot and humid.', 4, '날씨'],
    ['freezing', '형용사', '몹시 추운', 'It is freezing outside.', 3, '날씨'],
    ['temperature', '명사', '온도, 기온', 'The temperature is low.', 3, '날씨'],
    ['degree', '명사', '도 (온도 단위)', 'It is twenty degrees.', 3, '날씨'],
    ['sunshine', '명사', '햇빛', 'I like the sunshine.', 3, '날씨'],
    ['fog', '명사', '안개', 'There is fog on the road.', 3, '날씨'],
    ['thunder', '명사', '천둥', 'I hear thunder.', 2, '날씨'],
    ['lightning', '명사', '번개', 'I see lightning.', 2, '날씨'],
    ['snowflake', '명사', '눈송이', 'A snowflake is on my hand.', 3, '날씨'],
  ],

  '숫자/시간': [
    ['one', '수사', '하나, 1', 'I have one pencil.', 1, '기수'],
    ['two', '수사', '둘, 2', 'I have two eyes.', 1, '기수'],
    ['three', '수사', '셋, 3', 'I see three birds.', 1, '기수'],
    ['four', '수사', '넷, 4', 'A cat has four legs.', 1, '기수'],
    ['five', '수사', '다섯, 5', 'I have five fingers.', 1, '기수'],
    ['six', '수사', '여섯, 6', 'I am six years old.', 1, '기수'],
    ['seven', '수사', '일곱, 7', 'There are seven days.', 1, '기수'],
    ['eight', '수사', '여덟, 8', 'A spider has eight legs.', 1, '기수'],
    ['nine', '수사', '아홉, 9', 'I get up at nine.', 1, '기수'],
    ['ten', '수사', '열, 10', 'I have ten toes.', 1, '기수'],
    ['eleven', '수사', '열하나, 11', 'A soccer team has eleven players.', 2, '기수'],
    ['twelve', '수사', '열둘, 12', 'There are twelve months.', 2, '기수'],
    ['thirteen', '수사', '열셋, 13', 'My brother is thirteen.', 2, '기수'],
    ['fourteen', '수사', '열넷, 14', 'She is fourteen.', 2, '기수'],
    ['fifteen', '수사', '열다섯, 15', 'I have fifteen cards.', 2, '기수'],
    ['sixteen', '수사', '열여섯, 16', 'He is sixteen.', 2, '기수'],
    ['seventeen', '수사', '열일곱, 17', 'She is seventeen.', 2, '기수'],
    ['eighteen', '수사', '열여덟, 18', 'He is eighteen.', 2, '기수'],
    ['nineteen', '수사', '열아홉, 19', 'She is nineteen.', 2, '기수'],
    ['twenty', '수사', '스물, 20', 'I have twenty stickers.', 2, '기수'],
    ['thirty', '수사', '서른, 30', 'There are thirty days.', 2, '기수'],
    ['forty', '수사', '마흔, 40', 'My uncle is forty.', 2, '기수'],
    ['fifty', '수사', '쉰, 50', 'I have fifty won.', 2, '기수'],
    ['sixty', '수사', '예순, 60', 'One hour is sixty minutes.', 2, '기수'],
    ['seventy', '수사', '일흔, 70', 'My grandpa is seventy.', 2, '기수'],
    ['eighty', '수사', '여든, 80', 'She is eighty years old.', 2, '기수'],
    ['ninety', '수사', '아흔, 90', 'The bus has ninety seats.', 2, '기수'],
    ['first', '수사', '첫 번째의', 'I am first.', 1, '서수'],
    ['second', '수사', '두 번째의, 초', 'I am second.', 1, '서수'],
    ['third', '수사', '세 번째의', 'She is third.', 1, '서수'],
    ['fourth', '수사', '네 번째의', 'I am in the fourth grade.', 2, '서수'],
    ['fifth', '수사', '다섯 번째의', 'Today is the fifth.', 2, '서수'],
    ['sixth', '수사', '여섯 번째의', 'I am in the sixth grade.', 2, '서수'],
    ['seventh', '수사', '일곱 번째의', 'July is the seventh month.', 2, '서수'],
    ['eighth', '수사', '여덟 번째의', 'August is the eighth month.', 2, '서수'],
    ['ninth', '수사', '아홉 번째의', 'September is the ninth month.', 2, '서수'],
    ['tenth', '수사', '열 번째의', 'October is the tenth month.', 2, '서수'],
    ['plus', '전치사', '더하기', 'Two plus two is four.', 2, '계산'],
    ['minus', '전치사', '빼기', 'Five minus two is three.', 2, '계산'],
    ['equal', '형용사', '같은', 'Two and two equal four.', 3, '계산'],
    ['more', '형용사', '더 많은', 'I want more.', 2, '계산'],
    ['less', '형용사', '더 적은', 'I want less.', 3, '계산'],
    ["o'clock", '부사', '~시 (정각)', "It is three o'clock.", 1, '시간'],
    ['quarter', '명사', '4분의 1, 15분', 'It is a quarter past two.', 3, '시간'],
    ['noon', '명사', '정오', 'We eat lunch at noon.', 3, '시간'],
    ['midnight', '명사', '한밤중, 자정', 'I sleep at midnight.', 3, '시간'],
    ['daily', '형용사', '매일의', 'I have a daily routine.', 3, '빈도'],
    ['every day', '부사', '매일', 'I read every day.', 2, '빈도'],
    ['usually', '부사', '보통, 대개', 'I usually walk to school.', 2, '빈도'],
    ['sometimes', '부사', '가끔', 'I sometimes play games.', 2, '빈도'],
  ],

  '사람/가족': [
    ['person', '명사', '사람', 'He is a nice person.', 2, '사람'],
    ['children', '명사', '아이들 (복수)', 'The children play outside.', 1, '사람'],
    ['adult', '명사', '어른', 'The adult is kind.', 3, '사람'],
    ['neighbor', '명사', '이웃', 'My neighbor is friendly.', 3, '사람'],
    ['teacher', '명사', '선생님', 'My teacher is kind.', 1, '사람'],
    ['grandma', '명사', '할머니', 'I love my grandma.', 1, '가족'],
    ['grandpa', '명사', '할아버지', 'I love my grandpa.', 1, '가족'],
    ['grandfather', '명사', '할아버지', 'My grandfather is old.', 2, '가족'],
    ['parents', '명사', '부모님', 'My parents are kind.', 1, '가족'],
    ['grandparents', '명사', '조부모님', 'I visit my grandparents.', 2, '가족'],
    ['older sister', '명사', '언니, 누나', 'I have an older sister.', 2, '가족'],
    ['younger sister', '명사', '여동생', 'I have a younger sister.', 2, '가족'],
    ['older brother', '명사', '형, 오빠', 'I have an older brother.', 2, '가족'],
    ['younger brother', '명사', '남동생', 'I have a younger brother.', 2, '가족'],
  ],

  '학교/문구': [
    ['classroom', '명사', '교실', 'Our classroom is big.', 1, '학교 공간'],
    ['gym', '명사', '체육관', 'We play in the gym.', 2, '학교 공간'],
    ['cafeteria', '명사', '구내식당', 'We eat in the cafeteria.', 3, '학교 공간'],
    ['recess', '명사', '쉬는 시간', 'We play at recess.', 3, '학교 공간'],
    ['subject', '명사', '과목', 'My favorite subject is art.', 2, '과목'],
    ['math', '명사', '수학', 'I like math.', 1, '과목'],
    ['science', '명사', '과학', 'Science is fun.', 1, '과목'],
    ['social studies', '명사', '사회', 'We study maps in social studies.', 3, '과목'],
    ['art', '명사', '미술', 'I like art.', 1, '과목'],
    ['P.E.', '명사', '체육', 'We have P.E. today.', 2, '과목'],
    ['textbook', '명사', '교과서', 'Open your textbook.', 2, '학용품'],
    ['workbook', '명사', '문제집, 워크북', 'Do your workbook.', 2, '학용품'],
    ['notebook', '명사', '공책', 'I write in my notebook.', 1, '학용품'],
    ['scissors', '명사', '가위', 'I cut paper with scissors.', 1, '학용품'],
    ['marker', '명사', '마커, 매직펜', 'I draw with a marker.', 2, '학용품'],
    ['colored pencil', '명사', '색연필', 'I have colored pencils.', 2, '학용품'],
    ['pencil case', '명사', '필통', 'My pencil case is blue.', 1, '학용품'],
    ['whiteboard', '명사', '화이트보드', 'Write on the whiteboard.', 2, '학용품'],
    ['tablet', '명사', '태블릿', 'I use a tablet in class.', 3, '학용품'],
    ['homework', '명사', '숙제', 'I do my homework.', 1, '수업'],
    ['quiz', '명사', '퀴즈, 간단한 시험', 'We have a quiz today.', 2, '수업'],
    ['sentence', '명사', '문장', 'Read the sentence.', 3, '수업'],
  ],
};
