// 배치 E — 숙어·표현 (part_of_speech = 숙어 / 표현). 사전의 "숙어·표현" 탭에 들어간다.
// 이미 사전에 같은 id의 단어가 있으면(hello, yes 등) 빌더가 알아서 건너뛴다.
export const BATCH_E = {
  일상생활: [
    ['wake up', '숙어', '잠에서 깨다', 'I wake up at seven.', 1, '아침'],
    ['get up', '숙어', '일어나다', 'I get up at seven.', 1, '아침'],
    ['wash my face', '숙어', '세수하다', 'I wash my face in the morning.', 1, '아침'],
    ['brush my teeth', '숙어', '이를 닦다', 'I brush my teeth after meals.', 1, '아침'],
    ['take a shower', '숙어', '샤워하다', 'I take a shower every day.', 1, '아침'],
    ['get dressed', '숙어', '옷을 입다', 'I get dressed for school.', 2, '아침'],
    ['eat breakfast', '숙어', '아침을 먹다', 'I eat breakfast at eight.', 1, '식사'],
    ['eat lunch', '숙어', '점심을 먹다', 'I eat lunch at school.', 1, '식사'],
    ['eat dinner', '숙어', '저녁을 먹다', 'We eat dinner together.', 1, '식사'],
    ['go to school', '숙어', '학교에 가다', 'I go to school by bus.', 1, '하루 일과'],
    ['come home', '숙어', '집에 오다', 'I come home at four.', 1, '하루 일과'],
    ['do homework', '숙어', '숙제를 하다', 'I do homework after school.', 1, '하루 일과'],
    ['watch TV', '숙어', 'TV를 보다', 'I watch TV after dinner.', 1, '저녁'],
    ['read a book', '숙어', '책을 읽다', 'I read a book before bed.', 1, '저녁'],
    ['take a bath', '숙어', '목욕하다', 'I take a bath at night.', 1, '저녁'],
    ['go to bed', '숙어', '잠자리에 들다', 'I go to bed at nine.', 1, '저녁'],
  ],

  '교실 영어': [
    ['open your book', '표현', '책을 펴세요', 'Open your book to page ten.', 1, '수업 지시'],
    ['close your book', '표현', '책을 덮으세요', 'Close your book, please.', 1, '수업 지시'],
    ['raise your hand', '표현', '손을 드세요', 'Raise your hand, please.', 1, '수업 지시'],
    ['sit down', '표현', '앉으세요', 'Sit down, please.', 1, '수업 지시'],
    ['stand up', '표현', '일어서세요', 'Stand up, please.', 1, '수업 지시'],
    ['be quiet', '표현', '조용히 하세요', 'Be quiet, please.', 1, '수업 지시'],
    ['work together', '표현', '함께 활동하세요', 'Let us work together.', 2, '수업 지시'],
    ['make a group', '표현', '모둠을 만드세요', 'Make a group of four.', 2, '수업 지시'],
    ['take turns', '표현', '차례를 지키다', 'Take turns, please.', 2, '수업 지시'],
    ['try again', '표현', '다시 해 보세요', 'Try again!', 1, '격려'],
    ['good job', '표현', '잘했어요', 'Good job!', 1, '격려'],
    ['well done', '표현', '참 잘했어요', 'Well done!', 1, '격려'],
    ['are you ready?', '표현', '준비됐나요?', 'Are you ready?', 1, '수업 시작'],
    ["let's start", '표현', '시작하자', "Let's start the game.", 1, '수업 시작'],
  ],

  '인사/표현': [
    ['hello', '표현', '안녕하세요', 'Hello, Mina!', 1, '인사'],
    ['hi', '표현', '안녕', 'Hi, Tom!', 1, '인사'],
    ['goodbye', '표현', '안녕히 가세요', 'Goodbye, see you!', 1, '인사'],
    ['please', '표현', '제발, 부탁합니다', 'Help me, please.', 1, '예의'],
    ['thank you', '표현', '고맙습니다', 'Thank you very much.', 1, '예의'],
    ['sorry', '표현', '미안해요', 'I am sorry.', 1, '예의'],
    ['excuse me', '표현', '실례합니다', 'Excuse me, where is the library?', 1, '예의'],
    ["you're welcome", '표현', '천만에요', "You're welcome.", 1, '예의'],
    ["that's okay", '표현', '괜찮아요', "That's okay.", 1, '예의'],
    ['yes', '표현', '네', 'Yes, I do.', 1, '대답'],
    ['no', '표현', '아니요', 'No, I do not.', 1, '대답'],
    ['maybe', '표현', '아마도', 'Maybe I can go.', 2, '대답'],
    ['really', '표현', '정말요?', 'Really?', 2, '대답'],
    ['sure', '표현', '물론이죠', 'Sure!', 2, '대답'],
    ['okay', '표현', '좋아요, 알겠어요', 'Okay, let us go.', 1, '대답'],
    ['of course', '표현', '물론이죠', 'Of course you can.', 2, '대답'],
    ['great', '표현', '아주 좋아요', 'Great!', 1, '감탄'],
    ['wow', '표현', '와!', 'Wow, it is big!', 1, '감탄'],
    ['I think', '표현', '내 생각에는', 'I think it is good.', 2, '의견'],
    ['I know', '표현', '알아요', 'I know the answer.', 1, '의견'],
    ["I don't know", '표현', '모르겠어요', "I don't know.", 1, '의견'],
    ['I agree', '표현', '동의해요', 'I agree with you.', 3, '의견'],
    ["I don't agree", '표현', '동의하지 않아요', "I don't agree.", 3, '의견'],
    ['me too', '표현', '나도요', 'Me too!', 1, '의견'],
    ['not me', '표현', '난 아니에요', 'Not me!', 2, '의견'],
    ["let's go", '표현', '가자', "Let's go to the park.", 1, '제안'],
    ['come on', '표현', '어서, 힘내', 'Come on, let us play.', 2, '제안'],
  ],
};
