// 배치 D — 모양·스포츠·크기·우주·장난감·교통·과학기술·상태·위치·의문사·성격·맛·직업·재료·과학·환경·독해,
// 그리고 이미 있는 단어의 다른 뜻 행(다의어)과 교실 동사.
export const BATCH_D = {
  모양: [
    ['rectangle', '명사', '직사각형', 'The door is a rectangle.', 2, '도형'],
    ['oval', '명사', '타원형', 'The mirror is an oval.', 3, '도형'],
    ['diamond', '명사', '마름모, 다이아몬드', 'The kite is a diamond.', 3, '도형'],
    ['pentagon', '명사', '오각형', 'A pentagon has five sides.', 4, '도형'],
    ['hexagon', '명사', '육각형', 'A hexagon has six sides.', 4, '도형'],
    ['octagon', '명사', '팔각형', 'A stop sign is an octagon.', 4, '도형'],
    ['dot', '명사', '점', 'Draw a dot.', 2, '선·모양'],
    ['curve', '명사', '곡선', 'The road has a curve.', 3, '선·모양'],
    ['flat', '형용사', '평평한', 'The table is flat.', 3, '선·모양'],
    ['bottom', '명사', '맨 아래, 바닥', 'Look at the bottom of the page.', 2, '선·모양'],
  ],

  스포츠: [
    ['football', '명사', '축구, 미식축구', 'He plays football.', 2, '구기 종목'],
    ['baseball', '명사', '야구', 'I play baseball.', 1, '구기 종목'],
    ['basketball', '명사', '농구', 'I play basketball.', 1, '구기 종목'],
    ['volleyball', '명사', '배구', 'We play volleyball.', 1, '구기 종목'],
    ['badminton', '명사', '배드민턴', 'We play badminton.', 2, '구기 종목'],
    ['table tennis', '명사', '탁구', 'I play table tennis.', 2, '구기 종목'],
    ['golf', '명사', '골프', 'Dad plays golf.', 2, '구기 종목'],
    ['bowling', '명사', '볼링', 'We go bowling.', 2, '구기 종목'],
    ['swimming', '명사', '수영', 'I like swimming.', 1, '운동 활동'],
    ['running', '명사', '달리기', 'Running is fun.', 1, '운동 활동'],
    ['jogging', '명사', '조깅', 'I go jogging.', 2, '운동 활동'],
    ['cycling', '명사', '자전거 타기', 'Cycling is fun.', 2, '운동 활동'],
    ['skating', '명사', '스케이트 타기', 'I like skating.', 2, '운동 활동'],
    ['skiing', '명사', '스키 타기', 'We go skiing in winter.', 2, '운동 활동'],
    ['snowboarding', '명사', '스노보드 타기', 'Snowboarding is exciting.', 3, '운동 활동'],
    ['surfing', '명사', '서핑', 'Surfing is fun.', 3, '운동 활동'],
    ['boxing', '명사', '권투', 'He likes boxing.', 3, '무술·개인 종목'],
    ['wrestling', '명사', '레슬링', 'Wrestling is a strong sport.', 3, '무술·개인 종목'],
    ['gymnastics', '명사', '체조', 'She does gymnastics.', 3, '무술·개인 종목'],
    ['taekwondo', '명사', '태권도', 'I learn taekwondo.', 2, '무술·개인 종목'],
    ['karate', '명사', '가라테', 'He learns karate.', 3, '무술·개인 종목'],
    ['yoga', '명사', '요가', 'Mom does yoga.', 3, '무술·개인 종목'],
    ['player', '명사', '선수, 경기자', 'He is a good player.', 2, '경기 용어'],
    ['coach', '명사', '코치, 감독', 'The coach is kind.', 3, '경기 용어'],
    ['bat', '명사', '야구 방망이', 'He has a baseball bat.', 2, '경기 용어'],
    ['racket', '명사', '라켓', 'I hold a racket.', 3, '경기 용어'],
    ['goal', '명사', '골, 목표', 'He scores a goal.', 2, '경기 용어'],
    ['race', '명사', '경주, 달리기 시합', 'I win the race.', 2, '경기 용어'],
    ['match', '명사', '경기, 시합', 'We win the match.', 3, '경기 용어'],
  ],

  크기: [
    ['huge', '형용사', '거대한', 'The whale is huge.', 3, null],
    ['giant', '형용사', '아주 큰', 'The giant tree is old.', 3, null],
    ['tiny', '형용사', '아주 작은', 'The ant is tiny.', 3, null],
    ['shallow', '형용사', '얕은', 'The pond is shallow.', 4, null],
    ['different', '형용사', '다른', 'We are different.', 2, null],
    ['bigger', '형용사', '더 큰', 'A lion is bigger than a cat.', 2, null],
    ['smaller', '형용사', '더 작은', 'A mouse is smaller than a cat.', 2, null],
    ['taller', '형용사', '더 키가 큰', 'He is taller than me.', 2, null],
    ['shorter', '형용사', '더 짧은, 더 키가 작은', 'My hair is shorter now.', 2, null],
    ['longer', '형용사', '더 긴', 'The river is longer than the road.', 3, null],
    ['heavier', '형용사', '더 무거운', 'The rock is heavier than the ball.', 3, null],
    ['lighter', '형용사', '더 가벼운', 'The feather is lighter than a coin.', 3, null],
    ['height', '명사', '키, 높이', 'What is your height?', 3, null],
    ['length', '명사', '길이', 'Measure the length.', 3, null],
    ['weight', '명사', '무게', 'What is your weight?', 3, null],
  ],

  우주: [
    ['universe', '명사', '우주', 'The universe is big.', 4, '우주 공간'],
    ['galaxy', '명사', '은하', 'Our galaxy has many stars.', 4, '우주 공간'],
    ['solar system', '명사', '태양계', 'The solar system has eight planets.', 4, '우주 공간'],
    ['planet', '명사', '행성', 'Earth is a planet.', 3, '행성'],
    ['Mercury', '명사', '수성', 'Mercury is near the sun.', 4, '행성'],
    ['Venus', '명사', '금성', 'Venus is bright.', 4, '행성'],
    ['Mars', '명사', '화성', 'Mars is red.', 3, '행성'],
    ['Jupiter', '명사', '목성', 'Jupiter is a big planet.', 4, '행성'],
    ['Saturn', '명사', '토성', 'Saturn has rings.', 4, '행성'],
    ['Uranus', '명사', '천왕성', 'Uranus is a cold planet.', 4, '행성'],
    ['Neptune', '명사', '해왕성', 'Neptune is far from the sun.', 4, '행성'],
    ['comet', '명사', '혜성', 'A comet has a long tail.', 4, '천체·현상'],
    ['asteroid', '명사', '소행성', 'An asteroid is a small rock.', 4, '천체·현상'],
    ['meteor', '명사', '유성', 'I see a meteor at night.', 4, '천체·현상'],
    ['gravity', '명사', '중력', 'Gravity pulls things down.', 4, '천체·현상'],
    ['spaceship', '명사', '우주선', 'The spaceship flies to Mars.', 2, '우주 탐사'],
    ['astronaut', '명사', '우주 비행사', 'The astronaut is in space.', 3, '우주 탐사'],
    ['alien', '명사', '외계인', 'The alien is green.', 3, '우주 탐사'],
    ['satellite', '명사', '인공위성', 'A satellite goes around Earth.', 4, '우주 탐사'],
    ['telescope', '명사', '망원경', 'I see stars with a telescope.', 3, '우주 탐사'],
  ],

  장난감: [
    ['teddy bear', '명사', '곰 인형', 'I hug my teddy bear.', 1, '인형·장난감'],
    ['stuffed animal', '명사', '동물 인형', 'I have a stuffed animal.', 2, '인형·장난감'],
    ['puppet', '명사', '꼭두각시, 손인형', 'The puppet is funny.', 3, '인형·장난감'],
    ['toy car', '명사', '장난감 자동차', 'I have a toy car.', 1, '인형·장난감'],
    ['airplane', '명사', '비행기', 'The airplane flies high.', 1, '인형·장난감'],
    ['helicopter', '명사', '헬리콥터', 'The helicopter is loud.', 2, '인형·장난감'],
    ['block', '명사', '블록, 덩어리', 'I stack a block.', 1, '만들기·놀이'],
    ['blocks', '명사', '블록들, 쌓기 나무', 'I play with blocks.', 1, '만들기·놀이'],
    ['lego', '명사', '레고', 'I build with Lego.', 2, '만들기·놀이'],
    ['kite', '명사', '연', 'I fly a kite.', 1, '만들기·놀이'],
    ['yo-yo', '명사', '요요', 'I play with a yo-yo.', 2, '만들기·놀이'],
    ['marble', '명사', '구슬', 'I have a blue marble.', 2, '만들기·놀이'],
    ['spinning top', '명사', '팽이', 'I spin the spinning top.', 3, '만들기·놀이'],
    ['dice', '명사', '주사위', 'Roll the dice.', 2, '만들기·놀이'],
    ['jump rope', '명사', '줄넘기 줄', 'I jump rope every day.', 2, '탈 것·운동 도구'],
    ['hula hoop', '명사', '훌라후프', 'I spin a hula hoop.', 3, '탈 것·운동 도구'],
    ['scooter', '명사', '킥보드', 'I ride a scooter.', 2, '탈 것·운동 도구'],
    ['bike', '명사', '자전거', 'I ride my bike.', 1, '탈 것·운동 도구'],
    ['skateboard', '명사', '스케이트보드', 'He rides a skateboard.', 3, '탈 것·운동 도구'],
  ],

  교통: [
    ['transportation', '명사', '교통, 교통수단', 'A bus is transportation.', 4, '탈 것'],
    ['van', '명사', '승합차', 'We go by van.', 2, '탈 것'],
    ['motorcycle', '명사', '오토바이', 'He rides a motorcycle.', 3, '탈 것'],
    ['ferry', '명사', '여객선', 'We take a ferry.', 3, '탈 것'],
    ['ambulance', '명사', '구급차', 'The ambulance is fast.', 2, '특수 차량'],
    ['police car', '명사', '경찰차', 'The police car is loud.', 2, '특수 차량'],
    ['fire engine', '명사', '소방차', 'The fire engine is red.', 2, '특수 차량'],
    ['school bus', '명사', '통학 버스', 'I take the school bus.', 2, '특수 차량'],
    ['traffic light', '명사', '신호등', 'Stop at the traffic light.', 2, '길·규칙'],
    ['crosswalk', '명사', '횡단보도', 'Use the crosswalk.', 3, '길·규칙'],
    ['passenger', '명사', '승객', 'The passenger gets on the bus.', 3, '사람'],
    ['driver', '명사', '운전사', 'The driver is kind.', 2, '사람'],
    ['sail', '동사', '항해하다', 'We sail on the sea.', 4, '탈 것'],
  ],

  과학기술: [
    ['technology', '명사', '기술', 'Technology is helpful.', 4, '기기'],
    ['laptop', '명사', '노트북 컴퓨터', 'I use a laptop.', 2, '기기'],
    ['smartphone', '명사', '스마트폰', 'Mom has a smartphone.', 2, '기기'],
    ['phone', '명사', '전화기', 'The phone is ringing.', 1, '기기'],
    ['machine', '명사', '기계', 'This machine is loud.', 3, '기기'],
    ['screen', '명사', '화면', 'The screen is bright.', 3, '기기'],
    ['printer', '명사', '프린터', 'The printer is broken.', 3, '기기'],
    ['speaker', '명사', '스피커', 'The speaker is loud.', 3, '기기'],
    ['headphone', '명사', '헤드폰', 'I use headphones.', 3, '기기'],
    ['earphone', '명사', '이어폰', 'I use earphones.', 3, '기기'],
    ['charger', '명사', '충전기', 'I need a charger.', 3, '기기'],
    ['battery', '명사', '건전지, 배터리', 'The battery is low.', 3, '기기'],
    ['internet', '명사', '인터넷', 'I use the internet.', 3, '인터넷'],
    ['website', '명사', '웹사이트', 'This website is fun.', 3, '인터넷'],
    ['app', '명사', '앱', 'I have a new app.', 2, '인터넷'],
    ['message', '명사', '메시지', 'I send a message.', 2, '인터넷'],
    ['email', '명사', '이메일', 'I send an email.', 3, '인터넷'],
    ['password', '명사', '비밀번호', 'Do not tell your password.', 3, '인터넷'],
    ['click', '동사', '클릭하다', 'Click the button.', 2, '컴퓨터 동작'],
    ['type', '동사', '(글자를) 입력하다', 'Type your name.', 2, '컴퓨터 동작'],
    ['download', '동사', '내려받다', 'I download a game.', 3, '컴퓨터 동작'],
    ['upload', '동사', '올리다', 'I upload a photo.', 4, '컴퓨터 동작'],
    ['delete', '동사', '지우다', 'Delete the file.', 3, '컴퓨터 동작'],
    ['turn on', '숙어', '(전원을) 켜다', 'Turn on the light.', 2, '컴퓨터 동작'],
    ['turn off', '숙어', '(전원을) 끄다', 'Turn off the TV.', 2, '컴퓨터 동작'],
  ],

  상태: [
    ['ugly', '형용사', '못생긴, 보기 흉한', 'The monster is ugly.', 2, '모습·느낌'],
    ['shiny', '형용사', '반짝이는', 'The coin is shiny.', 3, '모습·느낌'],
    ['smooth', '형용사', '매끄러운', 'The stone is smooth.', 3, '모습·느낌'],
    ['rough', '형용사', '거친', 'The wall is rough.', 3, '모습·느낌'],
    ['smart', '형용사', '똑똑한', 'She is smart.', 2, '평가'],
    ['clever', '형용사', '영리한', 'The fox is clever.', 3, '평가'],
    ['difficult', '형용사', '어려운', 'This question is difficult.', 2, '평가'],
    ['dangerous', '형용사', '위험한', 'Fire is dangerous.', 3, '평가'],
    ['special', '형용사', '특별한', 'Today is a special day.', 2, '평가'],
    ['important', '형용사', '중요한', 'It is important.', 2, '평가'],
    ['careful', '형용사', '조심하는', 'Be careful.', 2, '평가'],
    ['useful', '형용사', '유용한', 'A map is useful.', 3, '평가'],
    // 이미 있는 light(빛)의 형용사 뜻
    ['light', '형용사', '가벼운', 'The bag is light.', 2, '모습·느낌', { id: 'light-2', sense: 2 }],
  ],

  '위치/방향': [
    ['above', '전치사', '~보다 위에', 'The bird is above the tree.', 2, null],
    ['next to', '전치사', '~ 옆에', 'I sit next to Ben.', 1, null],
    ['in front of', '전치사', '~ 앞에', 'The dog is in front of the door.', 2, null],
    ['inside', '부사', '안에', 'Come inside.', 2, null],
    ['outside', '부사', '밖에', 'Let us play outside.', 2, null],
    ['forward', '부사', '앞으로', 'Move forward.', 3, null],
    ['backward', '부사', '뒤로', 'Step backward.', 3, null],
  ],

  의문사: [
    ['whose', '대명사', '누구의', 'Whose bag is this?', 3, null],
    ['how many', '표현', '몇 개', 'How many apples do you have?', 2, null],
    ['how much', '표현', '얼마, 얼마나 많이', 'How much is it?', 2, null],
    ['how old', '표현', '몇 살', 'How old are you?', 1, null],
    ['how long', '표현', '얼마나 오래, 얼마나 긴', 'How long is the river?', 3, null],
    ['how often', '표현', '얼마나 자주', 'How often do you exercise?', 3, null],
    ['what time', '표현', '몇 시', 'What time is it?', 1, null],
    ['what color', '표현', '무슨 색', 'What color is your bag?', 1, null],
    ['what kind', '표현', '어떤 종류', 'What kind of food do you like?', 2, null],
  ],

  성격: [
    ['helpful', '형용사', '도움이 되는', 'She is helpful.', 2, null],
    ['active', '형용사', '활동적인', 'He is an active boy.', 3, null],
    ['honest', '형용사', '정직한', 'He is honest.', 3, null],
    ['polite', '형용사', '예의 바른', 'She is polite.', 3, null],
    ['patient', '형용사', '참을성 있는', 'Be patient.', 3, null],
    ['lazy', '형용사', '게으른', 'The cat is lazy.', 2, null],
    ['hardworking', '형용사', '부지런한', 'My mom is hardworking.', 3, null],
    ['creative', '형용사', '창의적인', 'She is creative.', 3, null],
    ['generous', '형용사', '너그러운', 'He is generous.', 4, null],
    ['selfish', '형용사', '이기적인', 'Do not be selfish.', 4, null],
  ],

  '맛/질감': [
    ['sour', '형용사', '신', 'The lemon is sour.', 2, '맛'],
    ['salty', '형용사', '짠', 'The soup is salty.', 2, '맛'],
    ['bitter', '형용사', '쓴', 'Medicine is bitter.', 3, '맛'],
    ['spicy', '형용사', '매운', 'Kimchi is spicy.', 2, '맛'],
    ['delicious', '형용사', '아주 맛있는', 'The cake is delicious.', 2, '맛'],
    ['yummy', '형용사', '맛있는', 'This pizza is yummy.', 1, '맛'],
    ['tasty', '형용사', '맛있는', 'The soup is tasty.', 2, '맛'],
    ['juicy', '형용사', '즙이 많은', 'The peach is juicy.', 3, '식감'],
    ['crunchy', '형용사', '바삭바삭한', 'The apple is crunchy.', 3, '식감'],
    ['crispy', '형용사', '바삭한', 'The chicken is crispy.', 3, '식감'],
    ['chewy', '형용사', '쫄깃한', 'The candy is chewy.', 3, '식감'],
    ['sticky', '형용사', '끈적끈적한', 'My hands are sticky.', 3, '식감'],
  ],

  직업: [
    ['dentist', '명사', '치과 의사', 'The dentist checks my teeth.', 2, '의료·과학'],
    ['veterinarian', '명사', '수의사', 'The veterinarian helps animals.', 4, '의료·과학'],
    ['scientist', '명사', '과학자', 'The scientist does an experiment.', 3, '의료·과학'],
    ['engineer', '명사', '기술자, 공학자', 'My dad is an engineer.', 3, '의료·과학'],
    ['programmer', '명사', '프로그래머', 'She is a programmer.', 4, '의료·과학'],
    ['police officer', '명사', '경찰관', 'The police officer helps people.', 2, '안전·생활'],
    ['firefighter', '명사', '소방관', 'The firefighter is brave.', 2, '안전·생활'],
    ['farmer', '명사', '농부', 'The farmer grows rice.', 1, '안전·생활'],
    ['chef', '명사', '요리사', 'The chef makes pasta.', 2, '안전·생활'],
    ['baker', '명사', '제빵사', 'The baker makes bread.', 3, '안전·생활'],
    ['flight attendant', '명사', '승무원', 'The flight attendant is kind.', 4, '안전·생활'],
    ['artist', '명사', '화가, 예술가', 'The artist paints a picture.', 2, '예술·방송'],
    ['singer', '명사', '가수', 'She is a singer.', 1, '예술·방송'],
    ['dancer', '명사', '무용수', 'He is a dancer.', 2, '예술·방송'],
    ['actor', '명사', '배우', 'He is an actor.', 2, '예술·방송'],
    ['writer', '명사', '작가', 'She is a writer.', 2, '예술·방송'],
    ['photographer', '명사', '사진작가', 'The photographer takes photos.', 3, '예술·방송'],
    ['designer', '명사', '디자이너', 'She is a designer.', 3, '예술·방송'],
    ['athlete', '명사', '운동선수', 'He is an athlete.', 3, '운동'],
    ['soccer player', '명사', '축구 선수', 'He is a soccer player.', 2, '운동'],
    ['baseball player', '명사', '야구 선수', 'He is a baseball player.', 2, '운동'],
    ['office worker', '명사', '회사원', 'My dad is an office worker.', 3, '안전·생활'],
  ],

  재료: [
    ['metal', '명사', '금속', 'The spoon is metal.', 3, null],
    ['plastic', '명사', '플라스틱', 'The bottle is plastic.', 2, null],
    ['fabric', '명사', '천, 직물', 'The fabric is soft.', 4, null],
    ['cloth', '명사', '천', 'I wipe it with a cloth.', 3, null],
    ['rubber', '명사', '고무', 'The ball is rubber.', 3, null],
    ['clay', '명사', '찰흙', 'I make a cup with clay.', 2, null],
    ['cotton', '명사', '면, 목화', 'The shirt is cotton.', 3, null],
    ['wool', '명사', '양털, 털실', 'The sweater is wool.', 3, null],
    ['leather', '명사', '가죽', 'The bag is leather.', 3, null],
  ],

  과학: [
    ['solid', '명사', '고체', 'Ice is a solid.', 4, null],
    ['liquid', '명사', '액체', 'Water is a liquid.', 4, null],
    ['material', '명사', '재료, 물질', 'What is this material?', 4, null],
    ['heat', '명사', '열, 더위', 'I feel the heat.', 3, null],
    ['force', '명사', '힘', 'Force moves things.', 4, null],
    ['energy', '명사', '에너지', 'The sun gives us energy.', 3, null],
    ['magnet', '명사', '자석', 'A magnet pulls a nail.', 3, null],
    ['electricity', '명사', '전기', 'A lamp uses electricity.', 3, null],
    ['boil', '동사', '끓이다', 'Boil the water.', 3, null],
    ['float', '동사', '뜨다', 'The boat floats.', 3, null],
    ['dissolve', '동사', '녹다, 녹이다', 'Sugar dissolves in water.', 4, null],
    ['living thing', '명사', '생물', 'A plant is a living thing.', 4, null],
    ['habitat', '명사', '서식지', 'The forest is the bird\'s habitat.', 4, null],
    ['environment', '명사', '환경', 'We protect the environment.', 4, null],
  ],

  환경: [
    ['trash', '명사', '쓰레기', 'Put the trash in the bin.', 2, null],
    ['garbage', '명사', '쓰레기', 'Take out the garbage.', 3, null],
    ['recycle', '동사', '재활용하다', 'We recycle paper.', 3, null],
    ['reuse', '동사', '다시 쓰다', 'Reuse the bag.', 4, null],
    ['reduce', '동사', '줄이다', 'Reduce trash.', 4, null],
    ['protect', '동사', '보호하다', 'We protect nature.', 3, null],
    ['pollution', '명사', '오염', 'Air pollution is bad.', 4, null],
  ],

  '독해/이야기': [
    ['title', '명사', '제목', 'What is the title?', 3, null],
    ['author', '명사', '저자, 작가', 'Who is the author?', 3, null],
    ['illustrator', '명사', '삽화가', 'The illustrator draws the pictures.', 4, null],
    ['character', '명사', '등장인물', 'Who is the main character?', 3, null],
    ['setting', '명사', '배경', 'The setting is a forest.', 4, null],
    ['beginning', '명사', '시작, 처음', 'The beginning is fun.', 3, null],
    ['solution', '명사', '해결책', 'Find a solution.', 4, null],
    ['event', '명사', '사건, 행사', 'What is the main event?', 3, null],
    ['chapter', '명사', '(책의) 장', 'Read chapter one.', 3, null],
    ['predict', '동사', '예측하다', 'Predict what happens next.', 4, null],
    ['imagine', '동사', '상상하다', 'Imagine a big castle.', 3, null],
    ['finally', '부사', '마침내, 드디어', 'Finally, we arrive.', 3, null],
  ],

  // ─ 이미 있는 단어의 다른 뜻 행 / 교실 동사 ─
  동물: [['bat', '명사', '박쥐', 'A bat flies at night.', 2, '야생 동물', { id: 'bat-2', sense: 2 }]],
  사물: [['watch', '명사', '손목시계', 'I have a new watch.', 1, null, { id: 'watch-2', sense: 2 }]],
  쇼핑_뜻: [
    ['free', '형용사', '무료의', 'The book is free.', 2, '값', { id: 'free-2', sense: 2, category: '쇼핑' }],
    ['open', '형용사', '열려 있는, 영업 중인', 'The store is open.', 2, '가게 상태', { id: 'open-2', sense: 2, category: '쇼핑' }],
  ],
  돈_뜻: [['change', '명사', '거스름돈', 'Here is your change.', 3, '돈 종류', { id: 'change-2', sense: 2, category: '돈' }]],
  과학기술_뜻: [['mouse', '명사', '(컴퓨터) 마우스', 'Click with the mouse.', 2, '기기', { id: 'mouse-2', sense: 2, category: '과학기술' }]],
  동작: [
    ['circle', '동사', '동그라미 치다', 'Circle the answer.', 2, '교실 동작', { id: 'circle-2', sense: 2 }],
    ['underline', '동사', '밑줄을 긋다', 'Underline the word.', 2, '교실 동작'],
  ],
};
