// 배치 B — 행사·요일/달력·취미·감정·휴일·집·건강. 형식은 batch-a.mjs 와 같다.
export const BATCH_B = {
  '행사/활동': [
    ['festival', '명사', '축제', 'We go to the festival.', 2, '축제·대회'],
    ['celebration', '명사', '축하, 기념 행사', 'We have a big celebration.', 3, '축제·대회'],
    ['ceremony', '명사', '의식, 식', 'The ceremony starts at ten.', 3, '축제·대회'],
    ['wedding', '명사', '결혼식', 'We go to a wedding.', 2, '축제·대회'],
    ['concert', '명사', '음악회, 콘서트', 'We go to a concert.', 2, '축제·대회'],
    ['parade', '명사', '퍼레이드, 행진', 'I see a parade.', 3, '축제·대회'],
    ['contest', '명사', '대회, 경연', 'She won the contest.', 3, '축제·대회'],
    ['competition', '명사', '시합, 경쟁', 'We have a dance competition.', 4, '축제·대회'],
    ['talent show', '명사', '장기 자랑', 'I sing in the talent show.', 3, '축제·대회'],
    ['flea market', '명사', '벼룩시장', 'We go to the flea market.', 3, '축제·대회'],
    ['bazaar', '명사', '바자회', 'We sell toys at the bazaar.', 4, '축제·대회'],
    ['field trip', '명사', '현장 학습, 소풍', 'We go on a field trip.', 2, '학교 행사'],
    ['sports day', '명사', '운동회', 'Sports day is in May.', 2, '학교 행사'],
    ['school festival', '명사', '학교 축제', 'We sing at the school festival.', 3, '학교 행사'],
    ['graduation', '명사', '졸업', 'Graduation is in February.', 3, '학교 행사'],
    ['entrance ceremony', '명사', '입학식', 'The entrance ceremony is in March.', 3, '학교 행사'],
    ['summer camp', '명사', '여름 캠프', 'I go to summer camp.', 2, '학교 행사'],
    ['winter camp', '명사', '겨울 캠프', 'I go to winter camp.', 3, '학교 행사'],
    ['family day', '명사', '가족의 날', 'We eat out on family day.', 3, '기념일'],
    ["parents' day", '명사', '어버이날', "Parents' day is in May.", 3, '기념일'],
    ["children's day", '명사', '어린이날', "Children's Day is on May 5.", 2, '기념일'],
    ["teacher's day", '명사', '스승의 날', "I make a card for Teacher's Day.", 3, '기념일'],
  ],

  '요일/달력': [
    ['Monday', '명사', '월요일', 'I go to school on Monday.', 1, '요일'],
    ['Tuesday', '명사', '화요일', 'We have art on Tuesday.', 1, '요일'],
    ['Wednesday', '명사', '수요일', 'I have piano on Wednesday.', 1, '요일'],
    ['Thursday', '명사', '목요일', 'We swim on Thursday.', 1, '요일'],
    ['Friday', '명사', '금요일', 'Friday is fun.', 1, '요일'],
    ['Saturday', '명사', '토요일', 'I play on Saturday.', 1, '요일'],
    ['Sunday', '명사', '일요일', 'I rest on Sunday.', 1, '요일'],
    ['weekday', '명사', '평일', 'I go to school on a weekday.', 3, '요일'],
    ['weekend', '명사', '주말', 'I play soccer on the weekend.', 2, '요일'],
    ['January', '명사', '1월', 'It is cold in January.', 1, '월'],
    ['February', '명사', '2월', 'February is short.', 2, '월'],
    ['April', '명사', '4월', 'Flowers bloom in April.', 1, '월'],
    ['June', '명사', '6월', 'My birthday is in June.', 1, '월'],
    ['July', '명사', '7월', 'It is hot in July.', 1, '월'],
    ['August', '명사', '8월', 'We go to the beach in August.', 2, '월'],
    ['September', '명사', '9월', 'School starts in September.', 2, '월'],
    ['October', '명사', '10월', 'Leaves fall in October.', 2, '월'],
    ['November', '명사', '11월', 'It is cool in November.', 2, '월'],
    ['December', '명사', '12월', 'Christmas is in December.', 2, '월'],
  ],

  '취미/오락': [
    ['cartoon', '명사', '만화 영화', 'I watch a cartoon.', 1, '영상·놀이'],
    ['animation', '명사', '애니메이션', 'I like animation.', 3, '영상·놀이'],
    ['comic', '명사', '만화책', 'I read a comic.', 2, '영상·놀이'],
    ['TV', '명사', '텔레비전', 'I watch TV after dinner.', 1, '영상·놀이'],
    ['YouTube', '명사', '유튜브', 'I watch YouTube.', 2, '영상·놀이'],
    ['theater', '명사', '극장', 'We go to the theater.', 3, '영상·놀이'],
    ['photograph', '명사', '사진', 'This is a photograph of my family.', 3, '영상·놀이'],
    ['photo', '명사', '사진', 'I take a photo.', 2, '영상·놀이'],
    ['puzzle', '명사', '퍼즐', 'I like puzzles.', 2, '게임'],
    ['board game', '명사', '보드게임', 'We play a board game.', 2, '게임'],
    ['card game', '명사', '카드 게임', 'We play a card game.', 2, '게임'],
    ['computer game', '명사', '컴퓨터 게임', 'I play a computer game.', 2, '게임'],
    ['video game', '명사', '비디오 게임', 'He plays a video game.', 2, '게임'],
    ['karaoke', '명사', '노래방', 'We go to karaoke.', 3, '게임'],
    ['magic', '명사', '마술, 마법', 'I like magic.', 2, '게임'],
    ['hobby', '명사', '취미', 'My hobby is drawing.', 2, '취미 활동'],
    ['camping', '명사', '캠핑', 'We go camping.', 2, '취미 활동'],
    ['fishing', '명사', '낚시', 'Dad goes fishing.', 2, '취미 활동'],
    ['drawing', '명사', '그림 그리기', 'Drawing is fun.', 2, '취미 활동'],
    ['painting', '명사', '그림, 색칠하기', 'I like painting.', 2, '취미 활동'],
    ['reading', '명사', '독서', 'Reading is my hobby.', 2, '취미 활동'],
    ['singing', '명사', '노래 부르기', 'Singing is fun.', 2, '취미 활동'],
    ['dancing', '명사', '춤추기', 'I like dancing.', 2, '취미 활동'],
    ['cooking', '명사', '요리하기', 'Cooking is fun.', 2, '취미 활동'],
    ['collecting', '명사', '수집하기', 'Collecting stamps is my hobby.', 3, '취미 활동'],
  ],

  감정: [
    ['excited', '형용사', '신나는, 들뜬', 'I am excited about the trip.', 2, '기쁨'],
    ['cheerful', '형용사', '쾌활한, 명랑한', 'She is a cheerful girl.', 3, '기쁨'],
    ['joyful', '형용사', '아주 기쁜', 'The children are joyful.', 4, '기쁨'],
    ['proud', '형용사', '자랑스러운', 'I am proud of you.', 3, '기쁨'],
    ['thankful', '형용사', '감사하는', 'I am thankful for my friends.', 3, '기쁨'],
    ['grateful', '형용사', '고마워하는', 'I am grateful to my teacher.', 4, '기쁨'],
    ['surprised', '형용사', '놀란', 'I am surprised.', 2, '놀람·두려움'],
    ['scared', '형용사', '무서워하는', 'I am scared of dogs.', 2, '놀람·두려움'],
    ['frightened', '형용사', '겁먹은', 'The kitten is frightened.', 3, '놀람·두려움'],
    ['worried', '형용사', '걱정하는', 'Mom is worried.', 3, '놀람·두려움'],
    ['nervous', '형용사', '긴장한', 'I am nervous before the test.', 3, '놀람·두려움'],
    ['shy', '형용사', '수줍어하는', 'She is shy.', 2, '놀람·두려움'],
    ['embarrassed', '형용사', '부끄러운, 당황한', 'I am embarrassed.', 4, '놀람·두려움'],
    ['sleepy', '형용사', '졸린', 'I am sleepy.', 1, '피곤·지루함'],
    ['bored', '형용사', '지루한', 'I am bored.', 2, '피곤·지루함'],
    ['lonely', '형용사', '외로운', 'The old man is lonely.', 3, '슬픔·화'],
    ['upset', '형용사', '속상한', 'She is upset.', 3, '슬픔·화'],
    ['disappointed', '형용사', '실망한', 'I am disappointed.', 4, '슬픔·화'],
    ['jealous', '형용사', '질투하는', 'He is jealous of his brother.', 4, '슬픔·화'],
    ['confused', '형용사', '혼란스러운', 'I am confused.', 4, '생각·마음 상태'],
    ['interested', '형용사', '관심 있는', 'I am interested in space.', 3, '생각·마음 상태'],
    ['curious', '형용사', '궁금한', 'The cat is curious.', 3, '생각·마음 상태'],
    ['brave', '형용사', '용감한', 'The firefighter is brave.', 2, '생각·마음 상태'],
    ['calm', '형용사', '침착한, 고요한', 'Stay calm.', 3, '생각·마음 상태'],
    ['relaxed', '형용사', '느긋한', 'I feel relaxed.', 3, '생각·마음 상태'],
    ['comfortable', '형용사', '편안한', 'The sofa is comfortable.', 3, '생각·마음 상태'],
    ['uncomfortable', '형용사', '불편한', 'These shoes are uncomfortable.', 4, '생각·마음 상태'],
    ['friendly', '형용사', '친절한, 다정한', 'My teacher is friendly.', 2, '생각·마음 상태'],
    ['silly', '형용사', '어리석은, 우스꽝스러운', 'You are so silly!', 3, '생각·마음 상태'],
    ['serious', '형용사', '진지한', 'He looks serious.', 3, '생각·마음 상태'],
  ],

  '휴일/기념일': [
    ["New Year's Day", '명사', '설날 (1월 1일)', "We eat rice cake soup on New Year's Day.", 2, '명절'],
    ['Lunar New Year', '명사', '설날 (음력 새해)', 'We bow to elders on Lunar New Year.', 3, '명절'],
    ['Seollal', '명사', '설날', 'We wear hanbok on Seollal.', 3, '명절'],
    ['Chuseok', '명사', '추석', 'We see the full moon on Chuseok.', 2, '명절'],
    ["Valentine's Day", '명사', '밸런타인데이', "I give chocolate on Valentine's Day.", 2, '서양 기념일'],
    ['Easter', '명사', '부활절', 'We hunt for eggs at Easter.', 3, '서양 기념일'],
    ['Halloween', '명사', '핼러윈', 'I wear a costume on Halloween.', 2, '서양 기념일'],
    ['Thanksgiving', '명사', '추수감사절', 'We eat turkey on Thanksgiving.', 3, '서양 기념일'],
    ['Christmas', '명사', '크리스마스', 'I love Christmas.', 1, '서양 기념일'],
    ['Christmas Eve', '명사', '크리스마스 이브', 'We eat cake on Christmas Eve.', 2, '서양 기념일'],
    ['gift', '명사', '선물', 'This gift is for you.', 1, '기념일 물건'],
    ['costume', '명사', '의상, 분장 옷', 'I wear a witch costume.', 3, '기념일 물건'],
    ['pumpkin', '명사', '호박', 'The pumpkin is orange.', 2, '기념일 물건'],
    ['Santa Claus', '명사', '산타 할아버지', 'Santa Claus brings gifts.', 1, '기념일 물건'],
    ['reindeer', '명사', '순록', 'The reindeer pulls the sleigh.', 3, '기념일 물건'],
    ['snowman', '명사', '눈사람', 'We make a snowman.', 1, '기념일 물건'],
    ['Christmas tree', '명사', '크리스마스 트리', 'The Christmas tree has lights.', 1, '기념일 물건'],
    ['stocking', '명사', '(크리스마스) 양말', 'I hang a stocking.', 3, '기념일 물건'],
    ['lucky bag', '명사', '복주머니', 'I got a lucky bag.', 3, '기념일 물건'],
    ['rice cake', '명사', '떡', 'We eat rice cake soup.', 2, '기념일 물건'],
  ],

  '집/가구': [
    ['living room', '명사', '거실', 'We watch TV in the living room.', 1, '방·공간'],
    ['bedroom', '명사', '침실', 'I sleep in my bedroom.', 1, '방·공간'],
    ['bathroom', '명사', '욕실, 화장실', 'The bathroom is clean.', 1, '방·공간'],
    ['dining room', '명사', '식당 (집의)', 'We eat in the dining room.', 3, '방·공간'],
    ['balcony', '명사', '발코니', 'I have plants on the balcony.', 3, '방·공간'],
    ['yard', '명사', '마당', 'The dog plays in the yard.', 2, '방·공간'],
    ['garage', '명사', '차고', 'The car is in the garage.', 3, '방·공간'],
    ['sofa', '명사', '소파', 'I sit on the sofa.', 1, '가구'],
    ['couch', '명사', '긴 의자, 소파', 'The cat is on the couch.', 3, '가구'],
    ['pillow', '명사', '베개', 'I hug my pillow.', 2, '가구'],
    ['blanket', '명사', '담요', 'I have a warm blanket.', 2, '가구'],
    ['shelf', '명사', '선반', 'The book is on the shelf.', 2, '가구'],
    ['bookshelf', '명사', '책장', 'The bookshelf has many books.', 2, '가구'],
    ['closet', '명사', '옷장, 벽장', 'My clothes are in the closet.', 3, '가구'],
    ['wardrobe', '명사', '옷장', 'The wardrobe is big.', 4, '가구'],
    ['drawer', '명사', '서랍', 'Open the drawer.', 2, '가구'],
    ['refrigerator', '명사', '냉장고', 'The milk is in the refrigerator.', 2, '가전제품'],
    ['fridge', '명사', '냉장고', 'Put it in the fridge.', 2, '가전제품'],
    ['freezer', '명사', '냉동실', 'The ice cream is in the freezer.', 3, '가전제품'],
    ['oven', '명사', '오븐', 'The cake is in the oven.', 2, '가전제품'],
    ['microwave', '명사', '전자레인지', 'Heat it in the microwave.', 3, '가전제품'],
    ['sink', '명사', '싱크대, 세면대', 'Wash your hands in the sink.', 2, '가전제품'],
    ['dishwasher', '명사', '식기세척기', 'The dishwasher is on.', 4, '가전제품'],
    ['washing machine', '명사', '세탁기', 'The washing machine is loud.', 2, '가전제품'],
    ['fan', '명사', '선풍기, 부채', 'Turn on the fan.', 2, '가전제품'],
    ['air conditioner', '명사', '에어컨', 'Turn on the air conditioner.', 2, '가전제품'],
    ['bathtub', '명사', '욕조', 'I take a bath in the bathtub.', 3, '욕실·식탁'],
    ['toilet', '명사', '변기, 화장실', 'Where is the toilet?', 2, '욕실·식탁'],
    ['towel', '명사', '수건', 'I dry my hands with a towel.', 2, '욕실·식탁'],
    ['toothbrush', '명사', '칫솔', 'This is my toothbrush.', 2, '욕실·식탁'],
    ['toothpaste', '명사', '치약', 'I need toothpaste.', 2, '욕실·식탁'],
    ['plate', '명사', '접시', 'The plate is on the table.', 1, '욕실·식탁'],
    ['chopsticks', '명사', '젓가락', 'I use chopsticks.', 2, '욕실·식탁'],
  ],

  '건강/질병': [
    ['healthy', '형용사', '건강한', 'Vegetables are healthy.', 2, '건강 상태'],
    ['unhealthy', '형용사', '건강하지 않은', 'Too much candy is unhealthy.', 4, '건강 상태'],
    ['health', '명사', '건강', 'Health is important.', 3, '건강 상태'],
    ['pain', '명사', '아픔, 통증', 'I feel pain in my leg.', 3, '증상'],
    ['flu', '명사', '독감', 'I have the flu.', 3, '증상'],
    ['fever', '명사', '열', 'I have a fever.', 2, '증상'],
    ['cough', '명사', '기침', 'I have a cough.', 2, '증상'],
    ['headache', '명사', '두통', 'I have a headache.', 2, '증상'],
    ['stomachache', '명사', '복통', 'I have a stomachache.', 2, '증상'],
    ['toothache', '명사', '치통', 'I have a toothache.', 2, '증상'],
    ['earache', '명사', '귀앓이', 'I have an earache.', 3, '증상'],
    ['sore throat', '명사', '목이 아픔', 'I have a sore throat.', 3, '증상'],
    ['runny nose', '명사', '콧물', 'I have a runny nose.', 3, '증상'],
    ['sneeze', '동사', '재채기하다', 'I sneeze a lot.', 3, '증상'],
    ['bruise', '명사', '멍', 'I have a bruise on my knee.', 4, '증상'],
    ['broken', '형용사', '부러진, 고장 난', 'My arm is broken.', 2, '증상'],
    ['medicine', '명사', '약', 'Take your medicine.', 2, '치료'],
    ['bandage', '명사', '붕대, 반창고', 'I put a bandage on my finger.', 3, '치료'],
    // 이미 있는 cold(추운)의 감기 뜻
    ['cold', '명사', '감기', 'I have a cold.', 2, '증상', { id: 'cold-2', sense: 2 }],
  ],
};
